IA-2402: Org unit changes proposal page
BLSQ/iaso pull request #1000
Opened 2023-12-20 16:20 UTC by beygorghor

[Mock-ups ](https://whimsical.com/georegistry-changes-requests-mobile-and-web-Qpd28e5mkQQuJcJsqjPP5N)

Page to list and approve change request on org unit

Related JIRA tickets : IA-2402

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- list page,
- filters
- dialogs
- typing
- hooks

## How to test

Create some org unit changes in you back-end  ('/admin/iaso/orgunitchangerequest/') and come back to the dashboard.

Click on org units / Review change proposals

Play with the page

## Print screen / video

<img width="1572" alt="Screenshot 2023-12-20 at 16 43 25" src="https://github.com/BLSQ/iaso/assets/12494624/7461a1d9-fdac-4b63-9d4b-d7cada07b2da">
<img width="1645" alt="Screenshot 2023-12-20 at 16 41 31" src="https://github.com/BLSQ/iaso/assets/12494624/625c4844-f52f-439c-bcfd-a85f1b278def">
<img width="1672" alt="Screenshot 2023-12-20 at 16 41 21" src="https://github.com/BLSQ/iaso/assets/12494624/66cf9371-93f3-481e-b72d-47a5321f077c">

## Notes
Multi selection is not done yet, this is much more complex to implement

2024-01-02 16:58 UTC, kemar reviewed
Almost LGTM but there are a few missing French translations and typos.

I will soon update the API doc and I may fix my feedback myself at the same time.

I will then approve this PR.

2024-01-02 16:58 UTC, kemar commented on hat/assets/js/apps/Iaso/utils/permissions.ts
> +const ORG_UNITS_CHANGE_REQUEST_APPROVE = 'iaso_org_unit_change_request_approve';
I would suggest using the term "review" instead of "approve" because you can either **approve** or **reject** a change request:

```suggestion
const ORG_UNITS_CHANGE_REQUEST_REVIEW = 'iaso_org_unit_change_request_review';
```

It's not blocking. It's up to you but it could be more explicit.

2024-01-02 16:58 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.changeRequest.edit": "Validate selected requests",
```suggestion
    "iaso.changeRequest.edit": "Valider les changements sélectionnés",
```

2024-01-02 16:58 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.forms.updated_by": "Updated by",
```suggestion
    "iaso.forms.updated_by": "Mis à jour par",
```

2024-01-02 16:58 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/messages.ts
> +        id: 'iaso.changeRequest.edit',
`defaultMessage` and `id` seems to have a different meaning?

2024-01-02 16:58 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesButtons.tsx
> +    const handlConfirm = useCallback(() => {
```suggestion
    const handelConfirm = useCallback(() => {
```

2024-01-02 16:58 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesButtons.tsx
> +                                onClick={handlConfirm}
```suggestion
                                onClick={handleConfirm}
```

2024-01-03 09:25 UTC, quang-le commented on hat/assets/js/apps/Iaso/utils/permissions.ts
> +const ORG_UNITS_CHANGE_REQUEST_APPROVE = 'iaso_org_unit_change_request_approve';
"Approve selected changes"

2024-01-03 09:26 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.changeRequest.edit": "Validate selected requests",
"Approve selected changes"

2024-01-03 13:00 UTC, quang-le requested changes
### TL;DR
- Blocking for immediate release:
    - Unmodified fields appearing green in Approved changes
- Blocking for short term:
    - Renaming statuses
    - updating "initial status" when a change request for the same irg unit has been approved
- Blocking in medium term (before doing multi select):
    - Moving modal from main page to table (or update front-end guidelines and bring other pages in line)
    - Add missing tooltips on icon buttons
    - Solve the problem of the intercation with Org unit's history tab (which is able to roll back the changes).
    


###Full review

About the interface:
- Statuses: I think we should use other terms 
    - "New" and "Rejected" can confuse with org unit validation status. I propose "Pending" and "Dismissed"
    - "Approved" is confusing as well, since reviewers can choose to approve only part of the request. I propose "Processed".
 - Approved requests:
     - In screenshot below, only the opening date was changed, but the parents and groups are highlighted in green as well, even though there was no difference between the original and the request
     
![Screenshot 2024-01-03 at 11 40 43](https://github.com/BLSQ/iaso/assets/38907762/1ffcbb03-e37c-492c-baae-e6ea8f8b85f8)

- When reviewing requests for the same org unit: if the user reviews and approves changes, then reviews the second change request, the initial org unit will not have been updated. It seems the interface shows the diff between the "initial org unit" and the changed org unit at the time of the request.
- Translations:
   -  Replace "Validate" and "Validation" with "Approve" and "Approval" (the english use of "validate" is not same as the french)
   - In modal, replace "validate or reject changes". with "review changes":
   
![Screenshot 2024-01-03 at 11 47 35](https://github.com/BLSQ/iaso/assets/38907762/4ba4c3df-6998-485e-b56e-f9baa05b23c6)

- Approved changes can still be rolled back via the org unit history tab. Such rollbacks will not be visible in the change request interface.

- Out of scope but related: the groups dropdown list is full of duplicates that can't be told apart:
![Screenshot 2024-01-03 at 11 59 22](https://github.com/BLSQ/iaso/assets/38907762/4549ef64-f253-4570-9cca-d046cbb2285f)

- No tooltip
![Screenshot 2024-01-03 at 12 07 35](https://github.com/BLSQ/iaso/assets/38907762/455f1733-9065-4514-a72d-a6314994991d)
s on table icon buttons?

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/constants/routes.js
> +    component: props => <ApproveOrgUnitChanges {...props} />,
`ReviewOrgUnitChanges` would be better I think (nitpick)

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.changeRequest.edit": "Validate selected requests",
"review"

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.forms.updated_by": "Updated by",
It seems strange that we don't already have a translation for updated by somewhere 🤷‍♂️
Anyway, it would make sense to use a more generic label than `iaso.forms` (nitpick)

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.changeRequest.seeRejectedChanges": "See rejected change(s)",
Not sure it makes much sense to have both titles. The interface is pretty clear about whether changes were approved or not

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesButtons.tsx
> +    const handlConfirm = useCallback(() => {
lol

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesButtons.tsx
> +            approved_fields: [],
Funny that you have to pass a value to `approved_fields`, I would expect the API to just take the status and a comment

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesButtons.tsx
> +            <SimpleModal
❤️

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesButtons.tsx
> +                    </>
That's a component

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesDialog.tsx
> +                            const isCellRejected =
That would be a sub-component as well

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/ApproveOrgUnitChangesDialog.tsx
> +        <IconButtonMui
Why not the IconButton from bluesquare-components?

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/Table/ApproveOrgUnitChangesTable.tsx
> +            ),
this would probably be useful in a table utils

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/Table/ApproveOrgUnitChangesTable.tsx
> +            />
I would put that in the table columns. Also, you won't be able to deep link this way.
To me it would make sense to have a similar setup as polio campaigns:
- a "list" API wit only the data needed for the list view (lighter payload)
- a "details" API that is called when opening the modal and receives the id. That's how we deeplink the campaigns modal in polio.
cf what I'm trying to do [here](https://github.com/BLSQ/iaso/pull/1002)

But it's mostly that I don't like having the modal here, because I like the jsx to "mimic" the interface as close as possible.

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/hooks/useNewFields.tsx
> +export type NewField = {
`NewOrgUnitField` will age better if we have new fields elsewhere in the future

2024-01-03 13:00 UTC, quang-le commented on hat/assets/js/apps/Iaso/utils/permissions.ts
> +const ORG_UNITS_CHANGE_REQUEST_APPROVE = 'iaso_org_unit_change_request_approve';
I agree

2024-01-08 11:01 UTC, madewulf commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/hooks/useNewFields.tsx
> +            longitude={location.latitude}
You inverted longitude and latitude ;-)

2024-01-08 13:38 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.changeRequest.seeRejectedChanges": "See rejected change(s)",
i'm using it in tooltip now

2024-01-08 14:38 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/approveChanges/Table/ApproveOrgUnitChangesTable.tsx
> +            />
I will let it like that, this is working and we still don't know how to manage multiple reviews

2024-01-09 14:41 UTC, quang-le approved these changes
Good for v1

2024-01-09 14:44 UTC, merged