IA-2566: Embedded links - user field : Value not found when the current user has not user permission
BLSQ/iaso pull request #1017
Opened 2024-01-08 08:08 UTC by hakifran

Explain what problem this PR is resolving
- When the current user has no **User management - Admin** the userSelect in embedded link display **a no found error**
- This ticket is about to fix that
Related JIRA tickets : [IA-2566](https://bluesquare.atlassian.net/browse/IA-2566)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Give the possibility to define the value of managedUsersOnly parameter instead of the predefined "true" value
## How to test
- Remove the **User management - Admin** permission from one user
- Connect with the user and try to create a new embedded link or edit one and check if there is no an error in userSelect field
## Print screen / video
[Screencast from 2024-01-08 10-06-40.webm](https://github.com/BLSQ/iaso/assets/19631540/ed5ae061-ead3-4056-b22e-d733b77a4d3c)

2024-01-08 09:11 UTC, hakifran commented
@cypress

2024-01-08 11:44 UTC, quang-le requested changes
I still get an error in a polio page. I don't know if there's anything special with user id 1
![Screenshot 2024-01-08 at 12 37 16](https://github.com/BLSQ/iaso/assets/38907762/19d9c31d-1ef0-4724-bbb1-3860afcd9946)

Otherwise not much to say on the front-end side. I feel you could spare addinga prop and just pass false to `useGetProfiles` since both the dialog and the user select are custom for the embedded link (so they're not used anywhere else).

I have no clue what the backend does, but I guess there was a separate PR for that.

2024-01-08 11:44 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/hooks/useGetProfiles.js
> +            : 'true',
```suggestion
        managedUsersOnly: apiParams.managedUsersOnly ?? 'true',
```

nitpick

2024-01-08 13:06 UTC, hakifran commented
@cypress

2024-01-08 15:36 UTC, hakifran commented
> I still get an error in a polio page. I don't know if there's anything special with user id 1 ![Screenshot 2024-01-08 at 12 37 16](https://private-user-images.githubusercontent.com/38907762/294888184-19d9c31d-1ef0-4724-bbb1-3860afcd9946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjEzMDgsIm5iZiI6MTcwNDcyMTAwOCwicGF0aCI6Ii8zODkwNzc2Mi8yOTQ4ODgxODQtMTlkOWMzMWQtMWVmMC00NzI0LWJiYjEtMzg2MGFmY2Q5OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MTY4ZmM2NjdhOTIzNGU2NzY0YjM0NDY4OWExM2I5NDkyY2E1ZGM3ODVkOTNlMTU0Y2E0NmIxNDRhZDRjOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Idjavsoo15sFllrZE5qI3-cCxF0zPlOZHtLGLAFB7Y)
> 
> Otherwise not much to say on the front-end side. I feel you could spare addinga prop and just pass false to `useGetProfiles` since both the dialog and the user select are custom for the embedded link (so they're not used anywhere else).
> 
> I have no clue what the backend does, but I guess there was a separate PR for that.

@quang-le the user with 1 as id has not a profile linked to it that's why it generates the error. I will talk with Martin to see how to handle situations like this.

2024-01-09 09:33 UTC, hakifran commented
> I still get an error in a polio page. I don't know if there's anything special with user id 1 ![Screenshot 2024-01-08 at 12 37 16](https://private-user-images.githubusercontent.com/38907762/294888184-19d9c31d-1ef0-4724-bbb1-3860afcd9946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTMwNTEsIm5iZiI6MTcwNDc5Mjc1MSwicGF0aCI6Ii8zODkwNzc2Mi8yOTQ4ODgxODQtMTlkOWMzMWQtMWVmMC00NzI0LWJiYjEtMzg2MGFmY2Q5OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5MzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYjAxMDA5OTQxYjJmYzQ5Y2NmMjc0NjU2YTMzMTkzMTg1MzZkMGY1M2EwOWNmMzAyNmNmNDA0ZWYxNWYwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HKuWQ9RFJ70_2HK3DySlu7v7FgX5uazID4auqmSQtTw)
> 
> Otherwise not much to say on the front-end side. I feel you could spare addinga prop and just pass false to `useGetProfiles` since both the dialog and the user select are custom for the embedded link (so they're not used anywhere else).
> 
> I have no clue what the backend does, but I guess there was a separate PR for that.

In the backend there is a filter on managedUserOnly for users

2024-01-09 15:10 UTC, quang-le approved these changes
juste a small optimization suggestion

2024-01-09 15:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/pages/components/UsersSelect.tsx
> +            )}
```suggestion
            value={value?.filter(userId =>
                Boolean(profilesList.find(profile => profile.value===userId))
            )}
```

2024-01-09 15:29 UTC, merged