IA-2529: Completeness stats table use legend color
BLSQ/iaso pull request #1078
Opened 2024-01-25 14:52 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-02-01 12:47 UTC, mathvdh approved these changes
Ok for me on the backend side. These SQL queries are complicated ;)

2024-02-06 09:12 UTC, quang-le requested changes
Works very nicely. Just a small block on `useEffectiveThreshold`. I'll update the guidelines to document it

2024-02-06 09:12 UTC, quang-le commented on docs/pages/dev/reference/guidelines/front-end/front-end.md
This should have been a separate DOC PR

2024-02-06 09:12 UTC, quang-le commented on docs/pages/dev/reference/guidelines/front-end/front-end.md
but ❤️

2024-02-06 09:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/completenessStats/hooks/useEffectiveThreshold.ts
> +    !threshold || isEqual(threshold, {}) ? defaultScaleThreshold : threshold;
In my opinion, if it has no internal state, it shouldn't be a hook, just a normal function

2024-02-07 12:40 UTC, quang-le approved these changes

2024-02-07 12:42 UTC, merged