Polio-620: search districts selected and not selected
BLSQ/iaso pull request #109
Opened 2022-10-25 14:53 UTC by hakifran

On the scope tab there is a list(table) of selected district and the user can't be able to search in the selected districts nor in the unselected(not include) ones

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes
-  Add a search input and a filter button
- Add a check box to specify if the search is in all districts(country) or in scope(already selected) only
- Display districts in table according to the result of search
- Add actions(select or unselect both for district and region) to each district in the result
- The map won't change with the search result

## How to test
- Edit campaign
- Scope tab
- Enter a string in the search input and click on filter button
- In the result try to do action like select or unselect

## Print screen / video

![Peek 2022-10-31 14-24](https://user-images.githubusercontent.com/19631540/199007824-9b6c49ce-ac29-4257-a483-cdf8fb150ecc.gif)

@cypress

2022-10-26 11:22 UTC, beygorghor requested changes
I'm a bit lost on this.

The checkbox is acting on the result of the search, so the search button should be enabled again if you toggle the checkbox.
Also this is not clear that the checkbox will affect the results.

May i suggest a different approach here:
- move checkbox over the results
- apply changes directly on the results while clicking on this checkbox without having to click on search again

2022-10-31 12:22 UTC, hakifran commented
> 

The refactoring is done based on the above comments.thank you

2022-11-02 11:04 UTC, quang-le requested changes
I think you have a problem with your linter. I listed the one most likely to cause bugs and unexpected behaviour in my comments. 
Please check your IDE to make sure it enforces the rules defined in the iaso repo

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +import { csvPreview } from '../../../../../../hat/assets/js/apps/Iaso/domains/dataSources/requests';
defined but never used

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +        [scopes, setScopes, filteredDistricts, setFilteredDistricts],
`searchValue` is missing from the dependencies array.

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    searchDistricts,
`searchDistricts` does not exist in props type

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    const districts = districtShapes
missing `;` 

I don't understand the new `const` here. It seems to me you can use districtShapes directly since you don't mutate it anywhere

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +        (district, selectedVaccine) => {
`selectedVaccine` is already declared line 227, please change the name to avoid confusion

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                            dist.vaccineName = "";
You have type errors here

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                const newFilteredDistricts = filteredDistricts.map(dict => {
you have a type error here

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +        (shape: ShapeRow, selectedVaccine) => {
`selectedVaccine` cf previous comment

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +        [districtShapes, scopes, setScopes, filteredDistricts, setFilteredDistricts],
Missing deps in the array. This can lead to nasty bugs

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    }, [districts, filteredDistricts, searchValue, searchScope])
missing deps in the array ⚠️

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +        searchDistricts.current = searchDistrictByName;
You're mutating a prop directly, which is not recommended. See the [es-lint rule](https://eslint.org/docs/latest/rules/no-param-reassign)

2022-11-02 11:04 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    }, [searchScope]);
missing deps in the array ⚠️

2022-11-02 13:04 UTC, quang-le requested changes
I think you have a problem with your linter. I listed the one most likely to cause bugs and unexpected behaviour in my comments. 
Please check your IDE to make sure it enforces the rules defined in the iaso repo

About the feature itself, I would suggest some changes so that the behaviour matches other search fields in the app:
- Replace the `Filter` button with a `Seach`button (like in Org units)
- Disable the Filter/Search button unless the search term is changed
- Enable the search when clearing the field. eg: I searched for "x", now I empty the search field, I should be able the click the button and see all results
- Show/hide out of scope districts, even when no search is active (same behaviour as "show deleted" elsewhere).

2022-11-10 11:22 UTC, hakifran commented
> I think you have a problem with your linter. I listed the one most likely to cause bugs and unexpected behaviour in my comments. Please check your IDE to make sure it enforces the rules defined in the iaso repo
> 
> About the feature itself, I would suggest some changes so that the behaviour matches other search fields in the app:
> 
> * Replace the `Filter` button with a `Seach`button (like in Org units)
> * Disable the Filter/Search button unless the search term is changed
> * Enable the search when clearing the field. eg: I searched for "x", now I empty the search field, I should be able the click the button and see all results
> * Show/hide out of scope districts, even when no search is active (same behaviour as "show deleted" elsewhere).

I did the refactoring(moving some code from ScopeInput to ScopeForm

2022-11-10 12:20 UTC, hakifran commented
@cypress

2022-11-10 13:45 UTC, hakifran commented
@cypress

2022-11-10 14:08 UTC, beygorghor requested changes
This is not working for me unfortunately:

![Screenshot 2022-11-10 at 15 07 37](https://user-images.githubusercontent.com/12494624/201113254-33f2740a-96ed-4d85-92f5-d80fb67cef2d.png)

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +            if (scope === undefined) {
`!scope`

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                        dist.vaccineName = selectedVaccine;
`const newFilteredDistricts = [...filteredDistricts];
filteredDistricts.forEach((dist, index) => {
  if (dist.id === district.id) {
    newFilteredDistricts[index].vaccineName = selectedVaccine;
  }
}`

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                    });
same here

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                        // eslint-disable-next-line no-param-reassign
same as above, better use another variable

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                    // eslint-disable-next-line no-param-reassign
i'm really not a huge fan of this

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                        // eslint-disable-next-line no-param-reassign
...

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                    onChange={() => onChangeSearchScope()}
why not directly `onChange={onChangeSearchScopeFunction}`?

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +                <Grid container spacing={3} xs={12} md={5}>
you need to add item in order to use xs prop

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            <Grid container spacing={4} justify="space-between">
`justify` => `justifyContent`

2022-11-10 14:08 UTC, beygorghor commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                    onChange={() => onChangeSearchScope()}
also `keyValue` is required

2022-11-11 14:31 UTC, hakifran commented
@cypress

2022-11-14 09:52 UTC, hakifran commented
@cypress

2022-11-15 08:37 UTC, quang-le requested changes
I get a lot of linter errors again, some of which are not trivial and indicative of errors in the code, like this one:

![Screenshot 2022-11-15 at 09 16 45](https://user-images.githubusercontent.com/38907762/201865965-f8964888-47d3-48df-8d59-1bd0367a56e7.png)

Also, there are still  issues:


https://user-images.githubusercontent.com/38907762/201869856-7bec8e11-a949-47bb-8e18-718c2d5e28d5.mov


https://user-images.githubusercontent.com/38907762/201869906-c0626711-64d9-4c75-95b2-521a0286b346.mov

2022-11-15 08:37 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
>                  // eslint-disable-next-line no-param-reassign
Please do not disable this linter rule, it is here for a good reason: [https://eslint.org/docs/latest/rules/no-param-reassign](https://eslint.org/docs/latest/rules/no-param-reassign)

2022-11-15 08:37 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                    // eslint-disable-next-line no-param-reassign
cf supra. It is a blocking issue for this PR

2022-11-15 08:37 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    values: values;
`values` isn't a type. The TS linter should tell you this

2022-11-15 08:37 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +import { values } from 'cypress/types/lodash';
unused import

2022-11-15 08:37 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
>  import { FieldProps } from 'formik/dist/Field';
I get a warning for this import  
![Screenshot 2022-11-15 at 09 36 58](https://user-images.githubusercontent.com/38907762/201870398-0a2c234e-5925-4cd4-92aa-d705870577ab.png)

2022-11-16 15:55 UTC, hakifran commented
@beygorghor , here is what I didn't manage to do: 

-  When the scope is loaded with not "Separate scope per round" not selected it works fine and the search works
- But when the "Separate scope per round" is checked I didn't manage to update the scope and therefore filteredDistricts state is not update end the search don't work and the amount of districts displayed in the table is not the same as in the map's legend.
- What I would like is to be able to update scope accordingly to the "Separate scope per round" selected or not.

2022-11-18 14:32 UTC, beygorghor commented
@quang-le @hakifran @codeKameleon 
I did a refactor of the code, split scopeInput  into smaller components.
Moved ap to the right.
And review a bit the logic to make it work with scope per round or not.
@hakifran honestly it was a very complex task... 


https://user-images.githubusercontent.com/12494624/202727885-e3e57b8e-9cc0-4a4d-ba5e-914d14aec0c8.mov

2022-11-18 14:32 UTC, beygorghor approved these changes

2022-11-21 11:03 UTC, quang-le requested changes
Big work, and nice cleanup of the code. I noted some hiccups with the feature:

- When playing with the add/remove region button in the table, the entire scope in unselected when re-adding a region that was removed (excpet for said region):


https://user-images.githubusercontent.com/38907762/203033605-1743cc30-e6ec-4c0e-b062-dca6bf2db2ff.mov

- When toggling the "Show districts in Scope" check box, the districts' boundary colors change, and the selection changes as well:


https://user-images.githubusercontent.com/38907762/203033920-ee5541ea-3925-43dc-829c-ef8e570855ae.mov

- When making a search including out of scope districts, if the search get 1 hit, the map will focus (change the fit to bounds) to that single district. It's confusing. Also, checking back the "Show districts in scope" check box, will then show an empty map:


https://user-images.githubusercontent.com/38907762/203034393-285da3b6-7de7-4207-bc73-80b775362045.mov

I think there's some clarification needed for that feature, as my understanding was that the search should just facilitate finding some districts in the table, and not impact the map, which should always show the current selected scope.

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
please fill in all deps or leave a comment explaining why it's ok not to list them all

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +                        setSearch={setSearch}
I'm not sure it's always safe to pass a reference to `setSearch`. I remember having to switch to useReducer to be able to pass a reference to the `set_` function of `useState` as prop. 

Just mentioning it in case it comes up in debugging

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            if (search !== '') {
We should discuss this. In my understanding, the search feature was a way to control what's shown in the table to facilitate selecting the scope. The map on the other hand should always show the current scope

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                });
That's a strange use of `.filter`. It's supposed to return a boolean but it returns `FilteredDistricts | undefined`. Maybe you can chain `.filter` to filter out unwanted values with `.map` to change the shape of the `dist` objects?

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +                            addNewScopeId(dist.id, selectedVaccine);
It would be better to avoid side-effects in the `filter` method, if just for easier later debugging.
If possible, I would spin out the side-effect in a `forEach`or something, like:

```
const addedDistricts = districtShapes.filter(filterFn);
addedDist.forEach(dist=>{addNewScopeId(dist.id, selectedVaccine})
```

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
>              newScopes.forEach(s => {
I feel this can be the cause of one of the bugs I recorded

2022-11-21 11:03 UTC, quang-le commented on plugins/polio/js/src/components/Scopes/DistrictScopeTable.tsx
> +            const newScopes: Scope[] = cloneDeep(scopes);
😀

2022-11-21 16:03 UTC, quang-le commented
It's been confirmed that the search should only change the results displayed by the table, and not the map. I updated the [ticket](https://bluesquare.atlassian.net/browse/POLIO-620)

2022-11-28 11:13 UTC, quang-le requested changes
Great rewrite, the code is much more readable and easy to navigate Some changes here and there in the code. I tried to point out potential sources of bugs I found while testing the feature.

- Selecting a region from the table unselects all other regions. Also, if the vaccine has been changed, the region selection ignores it



https://user-images.githubusercontent.com/38907762/204263129-47fb6feb-9fb2-4e39-89ff-ffe41bb7609a.mov



https://user-images.githubusercontent.com/38907762/204263263-be84386e-f2df-4d22-a190-f20619bf3dce.mov


- Adding a round/re-adding a round after removing crashes the page:


https://user-images.githubusercontent.com/38907762/204263523-14a3c31e-16ae-4c80-a703-2bfa6bf9b4cd.mov

- Selecting `Separate Scopes per round` before saving the rounds crashes the app (probably same bug as above):


https://user-images.githubusercontent.com/38907762/204263916-a4ba59c7-dd01-4874-95b1-7086dedf30bc.mov

- The table doesn't show the scope for Round 0: 

![Screenshot 2022-11-28 at 10 48 37](https://user-images.githubusercontent.com/38907762/204264055-5bb86c7a-cd75-4e93-895a-104fd2f88b37.png)


- There's an error in the console:

![Screenshot 2022-11-28 at 10 51 56](https://user-images.githubusercontent.com/38907762/204264128-eb4d2b81-e626-4b60-a437-47a043eb3eae.png)

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
>                  .map((round, roundIndex) => {
Line 46, I think `round` should be `cloneDeep` instead of of spread (complex nested object)

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
>              [...rounds]
As I recently learned at my expense: you should use lodash's cloneDeep here. Round is a nested object.
I would even think that you can skip copying rounds altogether, since .map returns a new array without changing the original

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            const currentRound = sortedRounds[parseInt(currentTab, 10) - 1];
I think this where it breaks with round 0

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            let filtreds: FilteredDistricts[] = [...districtShapes].map(
filtered

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            let filtreds: FilteredDistricts[] = [...districtShapes].map(
Also, I think you could use `const filtered` and use an early return i.o reassigning.

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            }
You could early return here (see previous comment)

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            }
and here (idem)

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +            let filtreds: FilteredDistricts[] = [...districtShapes].map(
Also `[...districtShapes]` is not necessary since you `.map` it

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +                        ...district,
I think shapes are nested objects, so `cloeDeep` i.o spread would be warranted

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
>              />
I would move that out in a separate component

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/forms/ScopeForm.tsx
> +                {!scopePerRound && renderField('scopes')}
moving `renderField` in a separate component would have the advantage that it would appear here as JSX

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Scopes/DistrictScopeTable.tsx
> +    const { setValue: setScopes } = helpers;
wouldn't it be quicker to do `const setScopes = useField(field.name)[3].setValue`? 
Maybe it's not as null safe? I don't know.

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Scopes/DistrictScopeTable.tsx
> +                    .filter(sc => sc.vaccine === selectedVaccine)
I think this is causing the bug when adding a region though the table

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Scopes/DistrictScopeTable.tsx
> +    toggleDistrictInVaccineScope,
why `toggleDistrictInVaccineScope`? It's only used to remove

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Scopes/DistrictScopeTable.tsx
> +    );
No need for `useMemo`here since you're returning a boolean

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    const [, , helpers] = useField(field.name);
cf infra about the declaration

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
> +    const [selectedVaccine, setSelectedVaccine] = useState<string>('mOPV2');
This typing can be stronger. I think I introduce stronger typing for viruses and vaccines in the PR about selecting round in the calendar, FYI

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
>      const toggleRegion = (
useCallback

2022-11-28 11:13 UTC, quang-le commented on plugins/polio/js/src/components/Inputs/ScopeInput.tsx
>      const onSelectOrgUnit = shape => {
useCallback

2022-11-30 12:23 UTC, quang-le approved these changes

2022-11-30 13:56 UTC, merged