IA-2621:  Org unit change request parent shape
BLSQ/iaso pull request #1096
Opened 2024-02-01 12:15 UTC by beygorghor

Add alert on whether the change request location falls within the parent's shape or not

Related JIRA tickets : IA-2621
## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- fixed typescript issues for react-leaflet and removed ts-ignore
- added geo_json on parent org unit in api
- hook to see if a location is within a shape
- customise markermap component to get a parent org unit and display it on map
- add popup if marker is not inside his parent shape
- covering edge case when you change parent too

## How to test

- make sure you have an org unit with a parent
- create a change request with this org unit and change the location  with something like this SRID=4326;POINT Z (23.0449 -2.9820 0)
- open change request dialog and check that everything is fine
- if you location is within the parent shape, edit the change request new location value and change lat or long to 0

## Print screen / video

![Screenshot 2024-02-01 at 12 51 05](https://github.com/BLSQ/iaso/assets/12494624/6c470b86-582a-4463-9696-f9c6cec73502)

2024-02-05 10:18 UTC, quang-le requested changes
Feature works like a charm!
I'm just blocking on the python api test and the useMemo thing

2024-02-05 10:18 UTC, quang-le commented on iaso/api/org_unit_change_requests/serializers.py
Isn't there a python test to update with this change?

2024-02-05 10:18 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.map.locationNotInShape": "The location is not within the bounds of the shape.",
" the parent's shape"?

2024-02-05 10:18 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/messages.js
> +        defaultMessage: 'The location is not within the bounds of the shape.',
idem: parent shape

2024-02-05 10:18 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/hooks/useMarkerWithinBounds.ts
❤️

2024-02-05 10:18 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
> +        type FieldDefinitions = Record<string, FieldDefinition>;
This type definition should be moved

2024-02-05 10:18 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
> +        };
This function definition should be moved out of the `useMemo` hook

2024-02-05 10:18 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/reviewChanges/hooks/useNewFields.tsx
The `useMemo`in this hook is used like a `useEffect`. 
`useMemo` is supposed to return a value, so it's confusing that it's not. 

From what I gather, it's used to calculate the value of `fields`, so it should return the value, and `setFields` should be called in a `useEffect` that depends on the return value of `useMemo`. 

That would make the code easier to understand I think

2024-02-07 08:44 UTC, beygorghor commented on iaso/api/org_unit_change_requests/serializers.py
you are right, the tests are not using / testing nested org unit type. I'll see if i have time to do it

2024-02-07 12:39 UTC, quang-le approved these changes

2024-02-07 12:42 UTC, merged