IA-2642: Payments part 1
BLSQ/iaso pull request #1160
Opened 2024-02-27 10:47 UTC by beygorghor

Api to get potential payments and web interface (filters, order)

# `Potential payment` API

[Mock-ups](https://whimsical.com/supervision-of-the-users-before-payment-9rNU57j31PnFykziJLocbZ)

This API allows to list potential payments linked to multiple `OrgUnitChangeRequest` by the same user to be updated and queried.

The Django model that stores "Potential payment" is `PotentialPayment`.

Whenever the list endpoint is invoked, it evaluates whether a new change request can be incorporated into the potential payment, or if there's a need to generate a new potential payment.

# Get a `PotentialPayment` list

## Permissions

- User must be authenticated
- User needs `iaso_payments` permission

## Query Parameters - Filters

- `page`: Int (optional) - Specifies the current page number. If not provided, the default value is 1.
- `order`: String (optional) - Specifies the order in which the results should be returned. If not provided, the default ordering value is `id`.
- `limit`: Int (optional) - Defines the number of entities to be returned per page. The default value is 20 if not specified.
- `users`: String (optional) - A comma-separated list of User IDs associated with the payments
  - Example: `&user_ids=10,9`
- `user_roles`: String (optional) - A comma-separated list of User Role IDs associated with the payments
  - Example: `&user_role_ids=10,9`
- `parent_id`: Int (optional) - The ID of the parent organization unit linked to the change requests. This should also include child units.
- `change_requests__created_at_after`: Date - 'YYYY-MM-DD' (optional) - The start date for when the change request has been validated. 
- `change_requests__created_at_before`: Date - 'YYYY-MM-DD' (optional) - The end date for when the change request has been validated.

## Possible responses

### 200 - OK

```json
{
  "count": "Long",
  "has_next": "Boolean",
  "has_previous": "Boolean",
  "page": "Long",
  "pages": "Long",
  "limit": "Long",
  "results": [
    "id": "Int - unique id",
    "change_requests": [
      {
        "id": "Int - change request unique id",
        "org_unit_id": "String - id or UUID of the OrgUnit to change",
        "uuid": "String - change request unique id",
      }
    ],
    "user": {
        "id": "Int - user unique id",
        "username": "String - username of user",
        "first_name": "String - first name of user",
        "last_name": "String - last name of user",
        "telephone": "String? - This type of field should be specified - not implemented yes",
    },
  ]
}
```

### 400 - Bad request

- `page` or `limit` cannot be parsed to a correct integer value

### 401 - Unauthorized

- No authentication token or an invalid one was provided

### 403 - Forbidden

- User doesn't have the proper permission to access this resource.

### 404 - Not found

- `users`, `user_roles`, parent_id` not found

Related JIRA tickets : IA-2462

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [x] Are there enough tests
- [x] Documentation has been included (for new feature)

## Doc

Api is documented on swagger [endpoint](http://localhost:8081/swagger/)

## Changes

- new model, api, serializer, filters to get potential payments
- front-end interface to display, filter and ordering potential payments
- back-end test

## How to test

Login with a superuser account or add `iaso_payments` permission to your user.

You need to have a few `VALIDATED` change request on your account (created_by field should be set)

Open the menu and navigate to Payments/To Pay 

Play with the results.

## Print screen / video

https://github.com/BLSQ/iaso/assets/12494624/a3b7d0d6-cf13-4ea1-810a-7dbd22b2710f

## Notes

This is the first part, `Lots` are not working for new

2024-03-05 17:45 UTC, mathvdh requested changes
It would be nice to have only 1 migration file per PR. (potentially 2 with the merge). I can help you with that.

2024-03-05 17:56 UTC, mathvdh requested changes
It would be nice to have only 1 migration file per PR. (potentially 2 with the merge). I can help you with that.

2024-03-05 17:56 UTC, mathvdh commented on iaso/api/payments/views.py
> +        queryset = PotentialPayment.objects.all()
You are not obliged to do `queryset = queryset` .. each time, you can chain. and you don't need to start with all().

2024-03-05 17:56 UTC, mathvdh commented on iaso/api/payments/views.py
> +        queryset = self.filter_queryset(self.get_queryset()).order_by(*orders)
We need to discuss about using this and also `filters.OrderingFilter` and `ordering_fields`

2024-03-05 17:56 UTC, mathvdh commented on iaso/api/payments/views.py
> +    permission_classes = [permissions.IsAuthenticated, HasPermission(permission.PAYMENTS)]
Don't we need `READ PAYMENTS` AND `WRITE PAYMENTS` permissions like in many other places

2024-03-05 17:56 UTC, mathvdh commented on iaso/models/payments.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="payment")
Is it the user who is gonna receive the payment ? Maybe we add a comment about that

2024-03-05 17:57 UTC, mathvdh commented
I didn't check all the tests yet. But I already put a bunch of comments and stuff to discuss ...

2024-03-06 10:02 UTC, mathvdh commented
voilà @beygorghor I have merged the migrations in one file and merged main.

2024-03-06 16:23 UTC, mathvdh requested changes

2024-03-06 16:23 UTC, mathvdh commented on iaso/api/payments/views.py
> +        orders = request.GET.get("order", "user__last_name").split(",")
I don't think this is gonna be taken into consideration, if you look at the code for `filters.OrderingFilter`.

```
def get_ordering(self, request, queryset, view):
        """
        Ordering is set by a comma delimited ?ordering=... query parameter.

        The `ordering` query parameter can be overridden by setting
        the `ordering_param` value on the OrderingFilter or by
        specifying an `ORDERING_PARAM` value in the API settings.
        """
        params = request.query_params.get(self.ordering_param)
        if params:
            fields = [param.strip() for param in params.split(',')]
            ordering = self.remove_invalid_fields(queryset, fields, view, request)
            if ordering:
                return ordering
```

So I guess if you want to override it you should maybe do something add something like this on line 76

`ordering = ['user__last_name']`

and then remove line 129 

(To be tested)

2024-03-07 10:10 UTC, quang-le approved these changes
just minor stuff but nothing blocking

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/constants/messages.js
> +        id: 'iaso.payments.toPay',
Not blocking but we probably need a less ambiguous phrasing, because lots are not necessarily paid

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
> +// import { useDispatch } from 'react-redux';
🚮

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
> +// import { baseUrls } from '../../constants/urls';
🚮

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
> +// import { redirectTo } from '../../routing/actions';
🚮

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
> +    // const columns = useGetUserRolesColumns(deleteUserRole);
🚮 or I guess it will be uncommented in the next PR

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
> +                    pages={data?.pages ?? 1}
You can use `SimpleTableWithDeepLink` to avoid the `data?.results ?? []` boilerplate

2024-03-07 10:10 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/PotentialPayments.tsx
> +                    pages={data?.pages ?? 1}
`SimpleTableWithDeepLink` handles that boilerplate

2024-03-08 15:47 UTC, mathvdh commented
@beygorghor I made the changes and it's ok on the backend side I think

2024-03-11 09:17 UTC, mathvdh approved these changes
👍🏼

2024-03-11 11:14 UTC, merged