POLIO-1126 Multi Round Budget (Frontend)
BLSQ/iaso pull request #1166
Opened 2024-03-04 14:54 UTC by kemar

# WIP

---

Explain what problem this PR is resolving

Related JIRA tickets : POLIO-1126

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-04-11 08:12 UTC, quang-le requested changes
On the front-end side, the only blocking comment is the one about the dependencies array of `useEffect`.
About blocking deletion of finished/advanced processes, I think we can make another ticket for that.

Nice work!

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/budget/api.py
> +
Maybe we could have some safeguards to avoid deleting e.g. completed processes.
It's tricky because the exact state of the process is determined by the json file, and we want to keep that configurable.
Do you think we could add a `block_deletion` field in the json config (in the `nodes`) and have use that to check if we should allow to delete the process?

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetDetails/BudgetDetails.tsx
>      const [showHidden, setShowHidden] = useState<boolean>(
I should have put a redirection here at the time. The hiding feature works, but it's not deep-linked. 
Not blocking. 
I mention it in the review so we can regroup these legacy bugs in a separate ticket

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/CreateBudgetProcessModal.tsx
> +    }, [formik.values.country]);
unless it breaks the interface, good practice would require to include `dropdownsData?.campaigns` in the dependencies array of `useEffect`
```suggestion
    }, [dropdownsData?.campaigns, formik.values.country]);
```

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/CreateBudgetProcessModal.tsx
> +    }, [formik.values.campaign]);
Same

```suggestion
    }, [dropdownsData?.rounds, formik.values.campaign]);
```

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/CreateBudgetProcessModal.tsx
> +                <FormikProvider value={formik}>
Nitpick, but I would replace the Fragment `<>` with the `FormikProvider`. That way the formik `Context` can already initialize while the dropdown data is fetched.
Not blocking, really splitting hairs here

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/EditBudgetProcessModal.tsx
> +                <FormikProvider value={formik}>
same as the other modal

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/hooks/api/useDeleteBudgetProcess.ts
> +    });
A `snackSuccessMessage` would be nice here.

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/hooks/api/useGetBudgetProcessAvailableRounds.ts
> +    }, []);
You don't really need `useCallback` if the dependencies array is empty. You can simply hoist the function outside of the hook

2024-04-11 08:12 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/hooks/api/useGetBudgetProcessAvailableRounds.ts
> +    }, []);
same

2024-04-15 09:10 UTC, kemar commented on plugins/polio/js/src/domains/Budget/BudgetProcess/CreateBudgetProcessModal.tsx
> +    }, [formik.values.country]);
@quang-le I can see the ESLint warning but I don't understand this one.

Why is it a good practice to include `dropdownsData?.campaigns` in the dependencies array of `useEffect`?

What is the benefit of adding it?

2024-04-17 09:15 UTC, quang-le approved these changes
Awesome!

2024-05-02 08:10 UTC, merged