IA-2396: Payments part 2 - Lots
BLSQ/iaso pull request #1168
Opened 2024-03-06 14:41 UTC by beygorghor

# `Payment Lots` API

    This API allows for the management and querying of payment lots. Payment lots are collections of payments that can be processed together.

    The Django model that stores "Payment Lot" is `PaymentLot`.

    This API supports creating new payment lots, updating existing ones, and querying for payment lots based on various criteria such as creation date, status, and associated user.

    ## Permissions

    - User must be authenticated
    - User needs `iaso_payments` permission

    ## Status Computing

    The status of a payment lot is dynamically computed based on the statuses of the payments it contains. The possible statuses are:

    - `new`: Default status, indicating a newly created lot or a lot with no payments sent.
    - `sent`: Indicates that all payments in the lot have been sent.
    - `paid`: Indicates that all payments in the lot have been paid.
    - `partially_paid`: Indicates that some, but not all, payments in the lot have been paid.

    The status is computed every time a payment lot is saved, ensuring that the payment lot status accurately reflects the current state of its associated payments.

    # `Payment Lots` Front-end:
- Allow user to select potential payments and create new lot of payments.
- Possibility to mark a lot as sent
- export list of payment to xlsx

Related JIRA tickets : IA-2396

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- See swagger for api doc

## Changes

- use foreign keys to link change requests, payments and potential payments
- new api endpoint for lots 
- payments lots frontend (filters, ordering, mark as sent, export to xlsx)

## How to test

Make sure you have superuser right or iaso_payment permission.

You also need approved change request on org unit with the field created by well set.

Visit payments/to pay and create new lots of payments
Visit lots of payment page and play with filters, mark one as send and try to export it.

## Print screen / video

https://github.com/BLSQ/iaso/assets/12494624/e70ef5b9-068c-4a64-8856-5cb5fb1b4f02

## Notes

@mathvdh i could not add `mark_payments_as_sent` parameter on patch request in swagger doc, if you have an idea.

2024-03-07 12:12 UTC, quang-le requested changes
Please check the `useSavePyamentLot` hook, especially the ignored error code.
There's also dead python code

2024-03-07 12:12 UTC, quang-le commented on iaso/api/payments/views.py
> +        return queryset
dead code

2024-03-07 12:12 UTC, quang-le commented on iaso/api/payments/views.py
> +                created_by_id=user["created_by"], status=OrgUnitChangeRequest.Statuses.APPROVED, payment__isnull=True
I think this should be `created_by__id`

2024-03-07 12:12 UTC, quang-le commented on iaso/api/payments/views.py
> +                potential_payment.delete()
shouldn't we soft delete, so we can keep the history of the whole process through `Audit`?

2024-03-07 12:12 UTC, quang-le commented on iaso/api/payments/views.py
> +                    change_request.save()
I think you can skip this loop by using `payment.change_requests.add(potential_payment.change_requests)` or something similar ( not 100% sure about the syntax)

2024-03-07 12:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/types.ts
> +};
```suggestion
type NestedPayment = Omit<Payment,"created_at", "updated_at","created_by","updated_by">
```

`Omit` will need to be imported

2024-03-07 12:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentLot.ts
> +const putPaymentLot = async (body: Partial<SavePaymentLotQuery>) => {
```suggestion
const patchPaymentLot = async (body: Partial<SavePaymentLotQuery>) => {
```

2024-03-07 12:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentLot.ts
> +    }
I think you could spare a `useMutation` hook:

```typescript
const createEditPaymentLot(body: Partial<SavePaymentLotQuery>, type:' create' | 'edit') => {
    if (type==="edit"){
        return patchPaymentLot(body)
    }
    if if (type==="create"){
        return postPaymentLot(body)
    }
    throw new Error(
                `wrong type expected: create or edit, got: ${type}`,
            );
}

// Then in the hook:
    const savePaymentLot = useSnackMutation({
        mutationFn: (data: Partial<SavePaymentLotQuery>) => createEditPaymentLot(data,type),
        invalidateQueryKey: ['paymentLots', 'potentialPayments'],
        ignoreErrorCodes,
        options: { onSuccess },
    });
```

I think there is a way to tell TS "if type === create then body should be SavePaymentLotQuery" and avoid a type error but I'd need to look it up

2024-03-07 12:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useGetPotentialPayments.tsx
> +            : undefined,
I have the feeling this ternary check could go  in a utils file, it's not the only place we do it

2024-03-07 12:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/LotsPayments.tsx
>                  <TableWithDeepLink
`SimpleTableWithDeepLink`

2024-03-07 12:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentLot.ts
> +    const ignoreErrorCodes = [400];
I don't think it's safe to ignore 400 error: the validation schema does not use the hook that handles backend errors, so I think it will just fail silently

2024-03-07 12:15 UTC, beygorghor commented on iaso/api/payments/views.py
> +                    change_request.save()
yes but this will not trigger the compute status of the lot ...

2024-03-07 12:16 UTC, beygorghor commented on iaso/api/payments/views.py
> +                potential_payment.delete()
basically the potential payment is saved to a payment directly

2024-03-11 11:43 UTC, beygorghor commented on iaso/api/payments/views.py
> +                created_by_id=user["created_by"], status=OrgUnitChangeRequest.Statuses.APPROVED, payment__isnull=True
Both lines of code will correctly filter OrgUnitChangeRequest objects where the created_by user's ID matches user["created_by"]. The choice between created_by_id and created_by__id is mostly stylistic in this context, as both achieve the same result.

2024-03-11 11:55 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentLot.ts
> +    }
```
type CreateEditPaymentLotFunction<T extends 'create' | 'edit'> = (
    // eslint-disable-next-line no-unused-vars
    body: T extends 'create'
        ? SavePaymentLotQuery
        : Partial<SavePaymentLotQuery>,
    // eslint-disable-next-line no-unused-vars
    type: T,
) => Promise<any>;
```

2024-03-11 12:16 UTC, quang-le approved these changes

2024-03-11 14:39 UTC, mathvdh requested changes
Very nice PR. See my one comment AND please we need to reduce the number of migrations : 6 migrations seems like a lot

2024-03-11 14:39 UTC, mathvdh commented on iaso/api/payments/views.py
> +        orders = request.GET.get("order", "updated_at").split(",")
Same remark as previous PR.
Is this compatible with `filters.OrderingFilter` ??

2024-03-12 04:50 UTC, mathvdh approved these changes
Ok let's go

2024-03-12 08:01 UTC, merged