POLIO-1516: Calendar to TSX
BLSQ/iaso pull request #1183
Opened 2024-03-12 13:51 UTC by beygorghor

In order to apply some changes in the future on the calendar it can be very useful to have it working with tsx

Related JIRA tickets : POLIO-1516

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Pass all js files to JSX, create /adapt calendar types

## How to test

Go to to calendar page and check everything is working nice !

2024-03-18 16:01 UTC, quang-le requested changes
The only blocking change in the code is with `useGetCampaignGroups`

Otherwise I saw the following:

- The cell outer limit is not correctly aligned when ending witha "round cell":
![Screenshot 2024-03-18 at 16 52 23](https://github.com/BLSQ/iaso/assets/38907762/e37c80d7-3e18-460d-80a7-d7d3807184b3)

- The country filter seems broken, both in the calendar and in the dashboard:

https://github.com/BLSQ/iaso/assets/38907762/6e1e97c1-1a5c-498a-b471-28bf6d980a69


https://github.com/BLSQ/iaso/assets/38907762/eea74c74-08e5-427e-8ebd-4017f42b7c70

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/Calendar.tsx
> +    },
❤️

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/Calendar.tsx
> +    const isLogged = useSelector((state: State) =>
I think you use the same selector somewhere else, so you could reuse the `State` type (maybe rename it)

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/Calendar.tsx
> +                : undefined,
curious, how this wasn't breaking before?

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/ExportCsvModal.tsx
> +                dateTo={roundStartTo || undefined}
why not set the default value of `roundStartFrom` and `roundStartTo` to `undefined`? (line 23 and 24)

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Body.tsx
> +                {campaigns.map(campaign => (
```suggestion
                {campaigns.map((campaign :MappedCampaign) => (
```
Doesn' t cost much, but could save checking the props while debugging. (especially since we have so many variations on Campaign, between here and LQAS/IM)

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +import { IntlMessage, useSafeIntl } from 'bluesquare-components';
```suggestion
import { IntlFormatMessage, useSafeIntl } from 'bluesquare-components';
```

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +const campaignTypeOptions = (formatMessage: IntlMessage, showTest = false) => {
```suggestion
const campaignTypeOptions = (formatMessage: IntlFormatMessage, showTest = false) => {
```

Wrong type. There's a typo in your type (hu hu)

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +                countries: countries?.join(','),
How did work before? Did we convert the array to a string in the input component?

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
>  export { wrappedFilters as Filters };
I would export with a more specific name: since it's wrapped, the IDE will not find uses of the component, and the name "Filters" is too widely used to search by name in the codebase

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
Not blocking, but we should move that component. We use it in the main polio dashboard as well, so it's not really the campaignCalendar.

Not blocking

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +                showOnlyDeleted: showOnlyDeleted ? 'true' : undefined,
```suggestion
                showOnlyDeleted: showOnlyDeleted && showOnlyDeleted !== "false" ? 'true' : undefined,
```

Just to avoid `/dashboard/polio/list/accountId/1/showOnlyDeleted/false/campaignType/regular/filterLaunched/true` to show deleted campaigns

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +        useGetGroupedCampaigns(params);
I think this is wrong, as it will get you the first page of paginated results instead of the whole list, so your dropdown may be incomplete. The hook should be changed instead to make `params` optional. 
Blocking

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Head.tsx
> +    headers: CalendarData['headers'];
TIL

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Head.tsx
> +                        .map((_, i) => (
I still have a gist for a utils generating an empty array somewhere if you want  😛

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Nav.tsx
> +                                date ? handleDateChange(moment(date).format(dateFormat)) : null
We convert `null` to `undefined` in the `ExportToCSvModal`'s `DateRangePicker` , why sticking with `null` here?
Genuinely curious about the reason, as I never quite know which is the right way to go when I use these components

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/cells/HeadStaticFields.tsx
> +const HeadStaticFieldsCells: FunctionComponent<Props> = ({ orders, router, isPdf }) => {
Funny, my linter complains here

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/cells/RoundCell.tsx
> +    const isLogged = useSelector((state: { users: { current: User } }) =>
cf comment &about `State` type

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/map/CalendarMapPanesRegular.tsx
> +                                    region={shape.parent_name ?? undefined}
Does it make any difference if it's `null` or `undefined`? If it's just to avoid a TS error, I'd rather change the typing: we remove all TS when we compile, but the ternary will still be run at runtime.

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/map/CampaignsLegend.tsx
> +                    {formatMessage(MESSAGES.campaigns)}
❤️

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/map/CampaignsLegend.tsx
> +                    {formatMessage(MESSAGES.campaigns)}
I hate `<FormattedMessage/>` so much, for no apparent reason 🤷‍♂️

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/map/VaccinesLegend.tsx
> +                    {formatMessage(MESSAGES.vaccines)}
❤️ again

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/map/utils.ts
> +                round.scopes.forEach(scope => {
There's a `Scope` type in `plugins/polio/src/constants/types.ts`

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/popper/RoundPopper.tsx
>                          </Grid>
🥳 lol

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/types.ts
> +    queryKey: (string | Record<string, string>)[];
```suggestion
    queryKey: (string | Record<string, unknown>)[];
```

You can pass add objects in the queryKey array

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
> +    spans = parseInt(`${spans / 7}`, 10);
I don't understand : you're converting a number to a string, then passing it to `parseInt`?
The `colSpan` prop seems to reliably be a `number` across the codebase.

2024-03-18 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
There are a few changes in the logic that go beyond TS conversion. Can you pls explain them, there's nothing mentioned in the PR description. I guess it has to do with rounds without dates

2024-03-18 16:03 UTC, quang-le commented
Additonal comment: Maybe not related to the PR, but the map doesn't fit to bounds when changing the country or country group selection. But maybe it's on purpose, as recentering the map at every filter change  maybe tedious for users
https://github.com/BLSQ/iaso/assets/38907762/3e0caf68-a524-466a-bb96-bc6799c36d84

2024-03-19 09:39 UTC, beygorghor commented on plugins/polio/js/src/domains/Calendar/Calendar.tsx
> +                : undefined,
don't know

2024-03-19 09:57 UTC, beygorghor commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +                countries: countries?.join(','),
yes you are right i broke the filter by doing this

2024-03-19 10:00 UTC, beygorghor commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/Filters.tsx
> +                showOnlyDeleted: showOnlyDeleted ? 'true' : undefined,
This comparison appears to be unintentional because the types 'boolean' and 'string' have no overlap.

2024-03-19 10:21 UTC, beygorghor commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/map/utils.ts
> +                round.scopes.forEach(scope => {
scope is implicitly defined by `MappedCampaign`

2024-03-19 10:25 UTC, beygorghor commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/utils.tsx
Yes basically calendar should not crash if a round doesn't have a stard or a end date like it can be the case in prod

2024-03-20 11:36 UTC, quang-le approved these changes

2024-03-20 11:36 UTC, quang-le commented on plugins/polio/js/src/domains/Calendar/campaignCalendar/CampaignsFilters.tsx
> -export { wrappedFilters as Filters };
❤️

2024-03-20 11:37 UTC, merged