IA-2774 add payment edition modal
BLSQ/iaso pull request #1186
Opened 2024-03-13 17:50 UTC by quang-le

Explain what problem this PR is resolving

Related JIRA tickets : IA-2774

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
In the code (jsdocs)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

- Add `useMarkPaymentAsSent` hook to handle the patch request, so the "edit" part of `useSavePaymentLot` can be used to update payments' statuses in the lot
- Add separate modal for edition with individual buttons to edit payment lot fields and without formik or yup validation
- Use value from table row to populate table and get initial state value
- update `patchRequest` of `useSavePaymentLots`: commented out actual patch request (already formatted for use with API). log body in the console for the time being
- use `patchRequest` in `PaymentLotEditionDialog` to create callbacks for "save name "and "save comment" buttons
- Refactor `usePotentialPaymentsColumns` -> `usePaymentsColumns`, with a `potential` prop
- Add `useTableSelection` convenience hook
- Add `EditPaymentDialog`:
    - Update a single table row
    - API mocked at the moment 
- Add `BulkEditPaymentDialog`:
    - Update selection of rows
    - Add custom "select all" and "unselect all" buttons 
    - Add warning modal on confirm. Layout taken from org unit bulk update, but the underlying component is `ConfirmCancelDialog`

## Print screen / video

https://github.com/BLSQ/iaso/assets/38907762/05aea426-cbaf-4a6c-8b30-d4f606e62740

## Notes

Has to be merged after IA-2791, as it already implements it. PR: https://github.com/BLSQ/iaso/pull/1184

2024-03-15 09:36 UTC, beygorghor requested changes
Nice job, a few remarks:

- i have a ghost dialog while saving name or comment:

https://github.com/BLSQ/iaso/assets/12494624/e5c74515-bf77-4de9-842c-2781db7242a0


- we are missing the payment status paid
- As discussed you can use a paper to display payment lot infos, remove the divider and use only one save button

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditPaymentsDialog.tsx
> +        });
Why not using onSuccess here ?

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditWarning.tsx
> +        // />
🗑️

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/components/EditPaymentLot/EditPaymentLotDialog.tsx
> +type Props = { isOpen: boolean; closeDialog: () => void; paymentLot: any };
We have a type `PaymentLot` no ?

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/components/EditPaymentLot/EditPaymentLotDialog.tsx
> +                                {/* <Box> */}
🗑️

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/components/EditPaymentLot/EditPaymentLotDialog.tsx
> +                                {/* </Box> */}
🗑️

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/hooks/config/usePaymentColumns.tsx
> +                    },
only a string is enough i think

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/utils/table.ts
❤️

2024-03-15 09:36 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/hooks/requests/useSavePaymentStatus.ts
Maybe just specify on the description this is just the frontend part

2024-03-15 09:38 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditPaymentsDialog.tsx
> +        });
Maybe this is because we have only the front-end part on this PR

2024-03-15 10:59 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditPaymentsDialog.tsx
> +        });
It seemed a bit more readable to me to have keep this logic in the component, since it's all related to the components own state

2024-03-15 10:59 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/payments/components/BulkEditPayment/BulkEditWarning.tsx
> +        // />
Yeah, I wasn't sure about that at first

2024-03-15 17:28 UTC, quang-le commented
@beygorghor  Update:

![Screenshot 2024-03-15 at 18 23 46](https://github.com/BLSQ/iaso/assets/38907762/98fa6fe5-9ce9-4733-9387-2b2611a4e6af)
![Screenshot 2024-03-15 at 18 23 52](https://github.com/BLSQ/iaso/assets/38907762/8688a41f-2126-4102-8619-3186dab4acd3)

2024-03-18 08:16 UTC, beygorghor approved these changes

2024-03-18 09:14 UTC, merged