POLIO-1519: Adding campaign types columns on calendar and map
BLSQ/iaso pull request #1187
Opened 2024-03-14 09:19 UTC by beygorghor

Adding campaign types columns on calendar and map pages

Related JIRA tickets : POLIO-1519

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Added columns to static columns on calendar page and campaign list page

## How to test

Open campaigns page and check that type columns is displaying correct infos, play with the sort.
Make the same thing on calendar page

## Print screen / video

![Screenshot 2024-03-14 at 10 19 25](https://github.com/BLSQ/iaso/assets/12494624/cb1aab58-9e98-477c-90a8-1e5fb0527ff0)
![Screenshot 2024-03-14 at 10 19 20](https://github.com/BLSQ/iaso/assets/12494624/8e2d26d2-2000-43bc-b090-4f932be024ef)

2024-03-15 11:07 UTC, mathvdh approved these changes
Please apply the suggest change and we can merge it !
it's ok on the backend side for me

2024-03-15 11:07 UTC, mathvdh commented on plugins/polio/api/campaigns/campaigns.py
> +        "campaign_types__name",
```suggestion
```

Please let's remove this line as it doesn't make sense for the moment

2024-03-15 11:09 UTC, mathvdh commented
I applied the suggestion myself. I think we can merge this

2024-03-18 16:17 UTC, quang-le requested changes

2024-03-18 16:17 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/CampaignsList/useCampaignsTableColumns.tsx
> +                Header: formatMessage(MESSAGES.campaign_types),
This will lead to confusion with the existing  "campaign type"  filter, which filters on "regular", "test" and "preventive" campaign types. We need different words for the 2 types of types

2024-03-19 11:46 UTC, beygorghor commented on plugins/polio/js/src/domains/Campaigns/CampaignsList/useCampaignsTableColumns.tsx
> +                Header: formatMessage(MESSAGES.campaign_types),
This filter has been changed on this [PR](https://github.com/BLSQ/iaso/pull/1185)

2024-03-20 11:38 UTC, quang-le approved these changes

2024-03-20 11:40 UTC, merged