IA-2817 no dash in app
BLSQ/iaso pull request #1240
Opened 2024-04-08 13:48 UTC by quang-le

Explain what problem this PR is resolving

Related JIRA tickets : IA-2817

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [X] Is my code clear enough and well documented
- [X] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
NA

## Changes
- Add a check on dash and whitespace when creating/updating appId in web front-end

## How to test

- Go to Profiles
- Try to edit and create projects. If app id has a dash or whitespace, the field will error and save will be disabled

## Print screen / video

https://github.com/BLSQ/iaso/assets/38907762/a7312ed7-4a03-4c62-880c-39cab2a59468

## Notes

The `ProjectDialog` component should be refactored to use the new modal (more performant) and formik, but that's for another ticket

2024-04-08 13:57 UTC, beygorghor requested changes
Woeking nice, i would remove all special char or at least also "_"

2024-04-08 14:03 UTC, quang-le commented
> Woeking nice, i would remove all special char or at least also "_"

you sure about removing the underscore??

it doesn't break anything as far as i know

2024-04-09 09:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/constants/filters.js
> -};
dead code

2024-04-09 09:17 UTC, beygorghor approved these changes

2024-04-09 09:32 UTC, merged