POLIO-658: create widget for budget timelines frontend
BLSQ/iaso pull request #125
Opened 2022-11-02 08:13 UTC by codeKameleon

Explain what problem this PR is resolving

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (Github already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2022-11-02 09:40 UTC, quang-le requested changes

2022-11-02 09:40 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/hooks/api/useGetBudget.ts
> +                const newData = {
what does that do?

2022-11-02 09:40 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
> +                        style={{
use a classname instead

2022-11-02 09:40 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
> +                                                display: 'flex',
idem

2022-11-02 09:40 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
> +                                            display: 'flex',
idem

2022-11-02 09:40 UTC, quang-le commented on plugins/polio/js/src/styles/constants.js
> +export const BUDGET_INACTIVE_COLOR = 'grey';
maybe get the gray from the theme

2022-11-04 10:37 UTC, codeKameleon commented
@cypress

2022-11-04 16:38 UTC, quang-le commented
The json you link to is invalid

2022-11-04 16:45 UTC, quang-le requested changes
The json you link to has been made from an out of date version of the workflow. Please take the latest version and update it

2022-11-07 09:02 UTC, quang-le requested changes
The code is pretty clean, nice work.
In hindsight, greying the icon is confusing when you start a new budget flow. It looks a bit as if the whole process as been completed:

![Screenshot 2022-11-07 at 09 54 51](https://user-images.githubusercontent.com/38907762/200268445-67edbaea-7a03-491d-bb04-c8867939886c.png)

There seems to be a config error as "WHO sent budget" is never marked as completed. Please make sure to use a copy of the workflow used in campaigns-staging:

![Screenshot 2022-11-07 at 09 30 47](https://user-images.githubusercontent.com/38907762/200268554-57e48533-2cf6-43be-87f8-42bc0eb5bd4f.png)

There's not enough contrast between the colors for active and inactive. I know I suggested to use the gray from the theme. It was a bad idea:

![Screenshot 2022-11-07 at 09 31 20](https://user-images.githubusercontent.com/38907762/200269468-c06a6e3f-333e-49e0-8519-29fb8e0d5429.png)


Step 2 should appear as completed. It doesn't. I don't know if it's a config problem or a problem with the component:

![Screenshot 2022-11-07 at 09 32 03](https://user-images.githubusercontent.com/38907762/200269619-4d24ac97-3a7c-4d4c-9035-0aef9339b980.png)

The console is full of errors, please clean it up:

![Screenshot 2022-11-07 at 09 34 39](https://user-images.githubusercontent.com/38907762/200269767-bd8c08d5-1f73-45a9-b2c2-9f1688de35e3.png)

And as mentioned before: please make sure to update a copy of the workflow used in campaigns-staging with your changes, or we won't be able to show the changes to the client

2022-11-08 11:11 UTC, beygorghor commented
I have fixed errors and change the lay-out a bit
![Screenshot 2022-11-08 at 10 14 50](https://user-images.githubusercontent.com/12494624/200549624-def06173-269c-4b43-8ff0-b61fdebff561.png)
![Screenshot 2022-11-08 at 10 14 32](https://user-images.githubusercontent.com/12494624/200549632-ac512d70-1267-4bd3-809a-c2bedb446fe4.png)

2022-11-08 13:40 UTC, codeKameleon commented
switch the PR to Draft vbecause of the budget worflow approval issues : https://bluesquare.atlassian.net/browse/POLIO-681

2022-11-14 08:52 UTC, beygorghor commented
@codeKameleon just hide he widget for now

2022-11-14 12:18 UTC, merged