POLIO-1102: scope only valid org units
BLSQ/iaso pull request #1254
Opened 2024-04-16 14:47 UTC by beygorghor

In polio prod go to campaign CHD-2023-05-1_nOPV

In scope tab, the list will show both MICHEMIRE and MICHEMERE. The second one has been rejected. the name is actually an alias of the first one

Related JIRA tickets :POLIO-1102

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

only fetch valid org units

## How to test

Select a campaign, edit the scope and get the name of an org unit.
Edit the org unit and set the status to rejected.
Refresh the campaign scope, org unit should be present anymore

## Print screen / video

https://github.com/BLSQ/iaso/assets/12494624/bbefcff1-dd2f-4480-901e-e3c8a903c380

2024-04-18 09:40 UTC, quang-le requested changes
If an org unit is already in the scope but changes status, it will not be displayed on the map or in the list, though it's still part of the scope.
I think this problem is adjacent to "what do we do if an org unit is split in 2"

https://github.com/BLSQ/iaso/assets/38907762/38251caa-5da9-466a-8c96-82e5b3694264

2024-04-22 13:02 UTC, beygorghor commented
@quang-le   Now it displays REJECTED or NEW org unit if they are already part of the scope.

2024-04-26 08:46 UTC, quang-le reviewed
If the `reduce` can be refactored as `filter().map()` without breaking the feature, I think that would be great for future maintenance

2024-04-26 08:46 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
> +        }
If we ever remake the API, it would be great to have that map coming straight from the backend

2024-04-26 08:46 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
> +        return filtered;
This would be much easier to read as a combination of `filter` and `map`

2024-04-26 08:46 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
> +                ...cloneDeep(district),
There's now `structuredClone` that comes free with JS

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

2024-04-26 08:46 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
> +            );
Why is this check needed? We already look for a scope line 92

2024-04-26 08:46 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/Scope/Scopes/MapScope.tsx
> +                    (ogrUnit.has_geo_json ||
`ogr_unit`  lol

2024-04-29 07:44 UTC, beygorghor commented on plugins/polio/js/src/domains/Campaigns/Scope/ScopeForm.tsx
> +                ...cloneDeep(district),
we need at least node 17 or to install a polyfill for that

2024-05-06 07:15 UTC, quang-le approved these changes

2024-05-06 09:41 UTC, merged