IA-2786: Add data download (CSV/Excel) blurred buttons on the submissions page
BLSQ/iaso pull request #1261
Opened 2024-04-18 10:29 UTC by butofleury

Explain what problem this PR is resolving

Related JIRA tickets : [IA-2786](https://bluesquare.atlassian.net/browse/IA-2786)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-04-22 13:18 UTC, beygorghor requested changes
I would keep the download buttons always visible but disable of a filter is not applied, using the tooltip around the download buttons. TIp: Tooltip from mui is not opening if title is an empty string normally.

2024-04-23 08:30 UTC, beygorghor approved these changes

2024-04-23 08:30 UTC, beygorghor commented
![Screenshot 2024-04-23 at 10 25 51](https://github.com/BLSQ/iaso/assets/12494624/cdddf7db-0442-4a6a-9ef6-bdd7f2b8f3c3)

2024-04-23 08:43 UTC, quang-le approved these changes

2024-04-23 08:44 UTC, merged