Polio 1237 multi round budget tab front
BLSQ/iaso pull request #1279
Opened 2024-04-26 08:28 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-04-29 09:39 UTC, kemar approved these changes
Backend LGTM

I suggest some changes but only if you're OK with it. Nothing mandatory.

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> +from pprint import pformat
This could be removed.

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> +class BudgetProcessUWriteRoundSerializer(serializers.ModelSerializer):
```suggestion
class BudgetProcessWriteRoundSerializer(serializers.ModelSerializer):
```

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> +            "cost",
It's terrifying how the addition of a _single_ field in a nested writable serializer can generate so much extra code in the parent validation logic…

There should be a simpler solution, but I can't find it…
So I've got nothing better to suggest.

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> -        # Link new rounds.
These comments added a little bit of explanation: "Unlink old rounds", then "Link new rounds".

Tt would have been nice to leave them ;)

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> +    def create(self, validated_data):
```suggestion
    def create(self, validated_data: dict) -> BudgetProcess:
```

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> +        if rounds_to_unlink:
👍

2024-04-29 09:39 UTC, kemar commented on plugins/polio/js/src/domains/Budget/BudgetProcess/BudgetProcessApproval.tsx
> +                // setFieldValue('budget_status', fieldKey);
Comments could probably be deleted.

2024-04-29 09:39 UTC, kemar commented on plugins/polio/budget/serializers.py
> +    def handle_rounds(self, budget_process, rounds_data):
```suggestion
    def handle_rounds(self, budget_process: BudgetProcess, rounds_data: dict) -> None:
```

Let's be consistent :)

2024-04-30 14:25 UTC, quang-le requested changes
There's this crash:
https://github.com/BLSQ/iaso/assets/38907762/e4391945-66c5-4a45-ba34-8113c1321120

2024-04-30 14:25 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/BudgetProcessCostPerChild.tsx
> +const placeholder = '--';
import `textPlaceholder` from bluesquare-components

2024-04-30 14:25 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/BudgetProcessCostPerChild.tsx
> +        </Table>
That's a component

2024-04-30 14:25 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/BudgetProcessRelease.tsx
> +export const BudgetProcessRelease: FunctionComponent = () => {
BudgetProcessFundsRelease

2024-04-30 14:25 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/CreateBudgetProcessModal.tsx
> +                                returnFullObject
I managed to crash the modal while playing with rounds. I think it maybe when you have this prop to `true` and the value is `null`

2024-04-30 14:25 UTC, quang-le commented on plugins/polio/js/src/domains/Budget/BudgetProcess/validation.ts
> +                /^\d{4}-\d{2}-\d{2}$/,
You should save this regex somewhere in a constant either in iaso or bluesquare-components

2024-05-02 08:04 UTC, merged