IA-2985: org unit tree use new api
BLSQ/iaso pull request #1339
Opened 2024-05-30 12:41 UTC by beygorghor

- use the new backend APIs to display and search the tree by one or multiple status

- use the DataSource config (if it exists) to customize the display of the tree

Related JIRA tickets : IA-2985

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- pass org unit tree modal and component to tsx
- use new api to get result
- link default visible validation status to the source config
- add infos over the source an the version used
- allow to hide valid org unit too

## How to test

Edit 3 sources and add different validation status, one should be the default one

Open submissions page and click on org unit select. Check that the correct source and version is displayed. try to find n org unit and select it.
Make the same thing while trying to export a data source (last icon on a source row). There you can select a version of a source.

## Print screen / video
<img width="703" alt="Screenshot 2024-05-30 at 14 40 35" src="https://github.com/BLSQ/iaso/assets/12494624/18f6818e-7d68-4af2-a1cc-0de5d92a1b4d">

<img width="1208" alt="Screenshot 2024-05-30 at 14 40 10" src="https://github.com/BLSQ/iaso/assets/12494624/720f37dd-0dd2-42fc-a56e-5fdaf75d7704">

2024-06-10 15:13 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.tsx
> +            onConfirm(undefined);
I could learn something here, what is the rationale behind using `undefined` rather than `null` here?

2024-06-11 13:43 UTC, quang-le requested changes
Great job, it was not the easiest code to modify. Thanks for converting everything to TS.

In the org unit search, if the source or version is changed, the treeview is empty, and the footer with the source+version only updates the source (not the version)

https://github.com/BLSQ/iaso/assets/38907762/93e79097-ca54-490d-ab7f-277b325f784a

The text search works though:

https://github.com/BLSQ/iaso/assets/38907762/eebd24c5-fbda-42b5-b1c4-5994ff282633

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsSmallInfos.js
> +function OrgUnitsSmallInfos({ orgUnit }) {
Why the change from the arrow function? We use arrow functions for all our function components so I don't understand the reason behind the change

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.tsx
> +            onConfirm(undefined);
Not sure it's the case here, but sometimes using `null` will prompt React to complain that we're switching between controlled and uncontrolled inputs, so most times using `undefined` will have the desired effect without popping errors in the console.

I used to use `null` when the value was set by my components, to differentiate from cases where no value was received but, in practice, we sometimes receive `null` from the backend, so 🤷‍♂️.

Also `typeof null` is `object`, so there's that as well... [insert JS rant here]

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.tsx
> +            });
Wouldn't using a function solve the exhaustive deps problem?

```suggestion
            setSettings(value => ({...value, statusSettings: sourceSettings}));
```

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.ts
> +    return `${baseApiUrl}?ignoreEmptyNames=true${idParam}${validationStatusString}`;
Unless the order of the params is important, I think we could use early returns in the switch statement. 
I prefer when we can avoid re-assigning value, but I can also live with it

```suggestion
    const defaultUrl = `${baseApiUrl}?ignoreEmptyNames=true${validationStatusString}`;
    if(!id) return defaultUrl;
    switch (type) {
        case 'version':
            return `${defaultUrl}&version=${id};
        case 'source':
            return `${defaultUrl}&data_source_id=${id};
        default:
            return  defaultUrl;
    }
```

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.ts
> +    return `search=${input1}${typeParam}${validationStatusString}`;
Same as above

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.ts
> +        throw error;
Should we still `throw`? We already handle the snack bar here and the internal hook of the treeview doesn't do anything `onError`

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/useSourceConfig.ts
> +            };
shouldn't the version have priority on the source?

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/registry/hooks/useGetOrgUnit.ts
I think `useFetchOrgUnits` should be moved out of registry

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.tsx
> +                        )}
This doesn't need to be a component. The `DynamicSelect` in bluesquare-components just puts its return value in a `Typography`.
 (es-lint complains that we pass a component that way)

2024-06-11 13:43 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.tsx
> +                        )}
This one is a bit harder to get rid off 😅

2024-06-12 09:33 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsSmallInfos.js
> +function OrgUnitsSmallInfos({ orgUnit }) {
auto complete ...

2024-06-12 09:59 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/useSourceConfig.ts
> +            };
it was implemented like that before...

2024-06-12 11:36 UTC, beygorghor commented
@kemar I have some strange behaviour in the result while changing default data source and filtering org unit on version id

Uploading Screen Recording 2024-06-12 at 13.33.46.mov…

2024-06-17 08:47 UTC, quang-le approved these changes

2024-06-17 08:54 UTC, merged