IA-2967 Add calculated fields to submissions filter
BLSQ/iaso pull request #1349
Opened 2024-06-03 09:50 UTC by bramj

In the dashboard, on the form submissions page, when you filter results on a specific form, you can choose to filter on attributes in the forms (modal with title "Search in submitted fields").

Here, I've now made the calculated fields also available since it makes a lot of sense to search on these in the light of searching in reference forms for entities.

2024-06-04 07:49 UTC, beygorghor requested changes
This will work in most of the cases, anyway i think now we have the type of the result that is present in the suffix of the label. See related ticket in JIRA

2024-06-07 09:30 UTC, bramj commented
@beygorghor Is this supposed to be in the `possible_fields`? :thinking: 
I can't really see any type suffix on Trypelim, e.g.:
```json
[
    { "name": "trypelim_profile", "type": "calculate", "label": "Trypelim profile" },
    { "name": "serie_id", "type": "calculate", "label": "Serie ID" },
    { "name": "absent", "type": "select one", "label": "Absent" },
    { "name": "position", "type": "select one", "label": "position" },
    { "name": "result", "type": "select one", "label": "Résultat" },
    { "name": "is_suspect", "type": "calculate", "label": "Est suspect (Sérologie Positive)" },
    { "name": "is_not_done", "type": "calculate", "label": "Pas fait" },
    { "name": "first_test_done", "type": "calculate", "label": "Premier test" },
    { "name": "is_absent", "type": "calculate", "label": "Est absent" },
    { "name": "instanceID", "type": "calculate", "label": "" }
]
```

2024-06-25 07:16 UTC, beygorghor commented
So let's merge this ! We can always make it better after !

2024-06-25 07:16 UTC, beygorghor approved these changes

2024-06-25 07:16 UTC, merged