IA-2972: Double check the mobile feature flags descriptions
BLSQ/iaso pull request #1374
Opened 2024-06-11 16:02 UTC by hakifran

Explain what problem this PR is resolving
- Double check the mobile feature flags descriptions
- Have mobile feature flags available in French
Related JIRA tickets : [IA-2972](https://bluesquare.atlassian.net/browse/IA-2972)
## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Add french translations for featureFlags
- Fix tooltip description

## How to test

- Go in projects
- Change the language to french
- Check if featureFlags descriptions are correct

[IA-2972]: https://bluesquare.atlassian.net/browse/IA-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-17 08:23 UTC, beygorghor requested changes, later dismissed
Some capitalising issues

2024-06-17 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.projets.featureflag.mobile_entity_warn_when_found": "Mobile: display a message when an entity is found on the duplicate search",
Display

2024-06-17 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.projets.featureflag.show_detail_map_on_mobile": "Mobile: Show Map of org unit",
map

2024-06-17 12:04 UTC, quang-le requested changes, later dismissed
Flagged some missing uppercase in default messages. pls check the json file as well

2024-06-17 12:04 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/projects/messages.ts
> +            'Mobile: enforce users are within reach of the org unit before starting the form',
Enforce

2024-06-17 12:04 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/projects/messages.ts
> +            'Mobile: limit download of org unit to what the user has access to',
Limit

2024-06-18 14:50 UTC, mathvdh approved these changes

2024-06-18 14:51 UTC, merged