IA-1606: remove unnessecary loader
BLSQ/iaso pull request #145
Opened 2022-11-08 16:17 UTC by codeKameleon

Explain what problem this PR is resolving

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

- removed the main loader as there is already one on table and on each filters's select inputs

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2022-11-09 08:19 UTC, beygorghor requested changes

2022-11-09 08:19 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/index.js
> -            {fetching && <LoadingSpinner />}
Maybe repove the unused import of `LoadingSpinner `. 
Also `fetching`, `loadingList` and  `fetchingDetail` are not used anymore

2022-11-09 10:03 UTC, codeKameleon commented
@cypress

2022-11-10 13:19 UTC, codeKameleon commented
@cypress

2022-11-10 13:22 UTC, beygorghor approved these changes

2022-11-10 13:24 UTC, merged