Wc2-106: small adjustments to the get storage blacklisted endpoint
BLSQ/iaso pull request #146
Opened 2022-11-09 08:21 UTC by niconoe

The response to GET /api/mobile/storage/blacklisted had a few differences to what was specified in https://bluesquare.atlassian.net/browse/WC2-65, in particular:

.- `updated_at` and `created_at` fields were returned at the root (device) and shouldn’t be.
- the `status` dict/object should be renamed `storage_status`
- `storage_status.updated_at` returned an ISO8601 string rather than a timestamp
- details about the orgunit and entity linked to the storage should not be returned

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are there enough tests

## How to test

- Make sure you have at least one device in the database with the `BLACKLISTED` status
- Go to `/api/mobile/storage/blacklisted/`
- Make sure the response conforms to what is described at https://bluesquare.atlassian.net/browse/WC2-65
- (after the mobile app has been updated): make sure the interactions to detect the blacklisted devices still work

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

@bmonjoie: I think the backend now complies fully with the specs, can you do the adjustments to the mobile app and make sure all works as expected?

2022-11-14 08:50 UTC, bmonjoie requested changes

2022-11-14 08:50 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "status": {
This should be `storage_status`

2022-11-14 08:50 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "status": {
This should be `storage_status`

2022-11-14 08:50 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "status": {
This should be `storage_status`

2022-11-14 08:50 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "status": {
This should be `storage_status`

2022-11-14 08:50 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                            "updated_at": None,
`None` is not an acceptable response.

2022-11-14 10:57 UTC, SimonDus commented on iaso/tests/api/test_storage.py
> +                    "status": {
Indeed

2022-11-18 11:39 UTC, niconoe commented
Remaining changes noted by @bmonjoie were implemented. @bmonjoie / @beygorghor : can you make sure the mobile and frontend are also ajusted to deal with those last changes (status -> storage_status for both the storage list and and the "logs per device" endpoints)?

2022-11-18 13:58 UTC, bmonjoie requested changes

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-18 13:58 UTC, bmonjoie commented on iaso/tests/api/test_storage.py
> +                    "storage_status": {"status": "OK", "reason": "", "comment": "", "updated_at": None},
I believe that when status is "OK", the reason and comment should be null. Updated at should be set

2022-11-21 08:25 UTC, merged