IA-1593: Stocks: replace the icons "settings" with an icon "edit"
BLSQ/iaso pull request #1461
Opened 2024-07-08 09:22 UTC by hakifran

Explain what problem this PR is resolving
- Stocks: replace the icons "settings" with an icon "edit"
Related JIRA tickets : [POLIO-1593](https://bluesquare.atlassian.net/browse/POLIO-1593)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- replace the icons "settings" with an icon "edit" in stock management

## How to test
- Go in Polio -> Vaccine module -> stock management -> stock variation
- Check Form A, Destruction report and incident report and check the edit ico

## Print screen / video
[Screencast from 2024-07-08 11-21-12.webm](https://github.com/BLSQ/iaso/assets/19631540/ea6bd5c3-36f9-472c-b3c2-69b974d6182a)

2024-07-08 09:28 UTC, hakifran commented
@cypress

2024-07-09 16:14 UTC, quang-le requested changes, later dismissed
See suggestions. Just typos really. I still think that if we change the icon in stock, we should also change it in supply chain, as the 2 modules are quite interconnected

2024-07-09 16:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/Buttons/EditIconButton.tsx
> +    overridedIcon,
overridedIcon --> overrideIcon ( to stay consistent)
```suggestion
    overrideIcon,
```

2024-07-09 16:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/Buttons/EditIconButton.tsx
> +            overrideIcon={overridedIcon}
```suggestion
            overrideIcon={overrideIcon}
```

2024-07-09 16:14 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
> +                                iconProps={{ overridedIcon: EditIcon }}
```suggestion
                                iconProps={{ overrideIcon: EditIcon }}
```

2024-07-09 16:14 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
> +                                iconProps={{ overridedIcon: EditIcon }}
```suggestion
                                iconProps={{ overrideIcon: EditIcon }}
```

2024-07-09 16:14 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
> +                                iconProps={{ overridedIcon: EditIcon }}
```suggestion
                                iconProps={{ overrideIcon: EditIcon }}
```

2024-07-10 13:19 UTC, hakifran commented
> See suggestions. Just typos really. I still think that if we change the icon in stock, we should also change it in supply chain, as the 2 modules are quite interconnected

@quang-le the edit ico has been added to supply chain too

2024-07-15 07:07 UTC, butofleury approved these changes

2024-07-15 07:47 UTC, merged