add correct props
BLSQ/iaso pull request #15
Opened 2022-09-16 11:33 UTC by beygorghor

Verification score should be blocked for number data entry only 

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included

## Changes

adding type and input props to adapt TextInput as a number input

## How to test

Edit a campaign , go to risk tab, verification score input should accept only numbers

## Print screen / video

<img width="674" alt="Screenshot 2022-09-16 at 13 31 03" src="https://user-images.githubusercontent.com/12494624/190629500-301dfb55-d9b8-4ab2-ab51-dbfd41a3b761.png">

2022-09-19 15:29 UTC, codeKameleon commented
@beygorghor shouldn't we add a limite to 20 or add a error validation if the user put a number above ?

2022-09-19 15:34 UTC, quang-le requested changes
I can still input text and save it as such:
Uploading Screen Recording 2022-09-19 at 17.33.35.mov…

2022-09-20 07:54 UTC, beygorghor commented
> I can still input text and save it as such:
> 
>  Screen.Recording.2022-09-19.at.17.33.35.mov

It's a firefox issue in fact, on chrome you can only enter 'e'.

2022-09-20 07:56 UTC, quang-le approved these changes

2022-09-20 07:57 UTC, merged