IA-3264 Order by created/updated
BLSQ/iaso pull request #1524
Opened 2024-07-31 10:08 UTC by bramj

The introduction of the `source_created_at` and `source_updated_at` fields resulted in some issues:
- Filters on creation timestamps
- Columns in the frontend that sort on incorrect db columns

I've decided on the following:
- On the instance list page:
  - timestamps shown are source_* with fallback to db timestamps
  - for this to work correctly, the order by on timestamps now uses `COALESCE` for the fallback
- On the instance details page:
  - Show both the device creation + db creation timestamps + the `updated_at`, which we can call the "last synced". (I decided against showing the `source_updated_at` since that's the least useful one and it will cause more confusion than value)

Related JIRA tickets : https://bluesquare.atlassian.net/browse/IA-3264

Some other fixes and improvements:
- Improved some logic: the frontend should only send the date, e.g.
"2024-07-10", without time. It's the backend that will add the "start of
day" or "end of day" to make sure we fetch all records. The previous
code would not find instances created in the last minute before
midnight.
- Refactored to be able to reuse existing code, changed some range
queries for simpler >= and <= date comparisons.
- Remove unused `instance.as_dict_with_parents()`

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-08-22 09:52 UTC, quang-le reviewed
LGTM but I don't know if the changes to docker-compose are part of the PR or should be merged.

I made a commit to remove a (now) unnecessary null check in `DateTimeCell`(related to your PR on blsq-comp)

2024-08-22 09:52 UTC, quang-le commented on docker-compose.yml
Why is that part of the PR?

2024-08-22 09:52 UTC, quang-le commented on iaso/models/base.py
> -
was this not used?

2024-08-22 10:04 UTC, quang-le requested changes
There may be a commit that needs pushing, because `source_created_at` is not in the API response for instances (both list and details)

![Screenshot 2024-08-22 at 11 59 19](https://github.com/user-attachments/assets/f544d4cb-9edb-4750-abbf-3bf324867959)

2024-08-22 12:50 UTC, bramj commented on docker-compose.yml
:grimacing: sorry, that's a bad oversight

2024-08-26 10:38 UTC, quang-le approved these changes

2024-08-27 12:26 UTC, merged