[IA-3275] Fix csv instance export when no data
BLSQ/iaso pull request #1527
Opened 2024-07-31 16:24 UTC by tdethier

Fixed an error 500 when there is no form data during an instance csv export.

Explain what problem this PR is resolving

Related JIRA tickets : IA-3275

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
/

## Changes
- Update frontend to block the csv/xlsx buttons to be active if there is no form in the current tab
- Update backend to return a `400` error if there is no `form` nor `form_ids` parameters in the query

## How to test
- Go on the "registry" page
- Select a level which doesn't have any form, and make sure you can't click on the csv/xlsx buttons
- Select a level which has at least one form but no submissions, and make sure you can't click on the csv/xlsx buttons
- (optional) Query the instances API directly and make sure you get a `400` error.

## Print screen / video

![image](https://github.com/user-attachments/assets/1730b8a6-eee5-44ce-905d-c13914310d58)

## Notes

There were a few comments in the backend code, mentioning some weird logic and the fact that the frontend will always send a `form` or `form_ids` parameter. There were also some mypy annotations to ignore cases where `Form` is `None`. 

Since we somehow ended up in a situation where the frontend didn't this parameter and now there's a check to make sure that there is actually a `form` value, I got rid of these comments. But we might need to check the logic behind all of this again, because there might be a few edge cases that will still trigger issues.

2024-08-07 16:50 UTC, hakifran requested changes

2024-08-07 16:50 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/registry/components/Instances.tsx
> +                                                formIds === undefined ||
Not very important but I think this `!formIds` can represent the formIds === undefined || formIds === null

2024-08-07 16:50 UTC, hakifran commented on iaso/tests/api/test_instances.py
> +        self.assertJSONResponse(response, 400)
```suggestion
        self.assertJSONResponse(response, status.HTTP_400_BAD_REQUEST)
```

2024-08-20 08:44 UTC, tdethier commented
Thanks @hakifran for the comments!

I made some changes.

2024-08-20 12:19 UTC, hakifran approved these changes
LGTM

2024-08-20 12:24 UTC, merged