IA-3206 IA-3207:  Frontend: move Project(s) filters on the different pages AND Frontend: add Project(s) columns on the different pages
BLSQ/iaso pull request #1534
Opened 2024-08-05 11:15 UTC by hakifran

Explain what problem this PR is resolving
- Frontend: move Project(s) filters on the different pages
- Frontend: add Project(s) columns on the different pages
Related JIRA tickets : [IA-3206](https://bluesquare.atlassian.net/browse/IA-3206) [IA-3207](https://bluesquare.atlassian.net/browse/IA-3207)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Add projects filter on some pages
- Move projects filter from one place to another
- Add projects columns on some pages
- Remove columns from some pages

## How to test
- https://whimsical.com/multi-project-web-interfaces-modifications-LRbazNKxybyqpULUQiKcJx
- Check if all pages on this mock-up

2024-08-05 11:58 UTC, hakifran commented
@cypress

2024-08-06 14:04 UTC, kemar requested changes
I've done a first pass on the backend only.

I think there are some N+1 problems in the backend queries.

I left some questions and guidance on how to address them.

2024-08-06 14:04 UTC, kemar commented on iaso/tests/api/test_orgunits.py
> +        with self.assertNumQueries(8):
That's strange, what is triggering this increase in the number of queries?

A proper prefetching should trigger only one additional query. Or am I missing something?

2024-08-06 14:04 UTC, kemar commented on iaso/tests/api/org_unit_change_requests/test_org_unit_change_requests.py
> +            #  13. PREFETCH OrgUnitChangeRequest.old_org_unit_type.projects
I think this comment is wrong because `projects` are not prefetched neither for `new_org_unit_type` or `old_org_unit_type`.

You should [prefetch these relations](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#prefetch-related) properly in `OrgUnitChangeRequestViewSet.get_queryset` and test it in (at least) one test of your choice.

The best way might be:

- add at least two related projects for `new_org_unit_type`
- add at least two related projects for `old_org_unit_type`
- ensure that the result of `self.assertNumQueries` stays stable

This will ensure that there is no hidden `N+1` because I spent a lot of time chasing and fixing them 😄

2024-08-06 14:04 UTC, kemar commented on iaso/api/query_params.py
> +PROJECTIDS = "projectIds"
Why do we have two ways of writing the same param?

I think we should have just one way. But there might be a reason I don't know?

2024-08-12 14:19 UTC, closed without merging