SLEEP-1458 Add instance-like filters on entities
BLSQ/iaso pull request #1542
Opened 2024-08-08 13:44 UTC by bramj

I'm really excited about this one!

This PR adds JSON logic filters to the entities page to allow searches such as 'give me all entities that have a form instance with "A" == "100"'.

It uses the `react-awesome-query-builder` in the frontend, formatting the data as "subfields", and add support in the backend to turn this into SQL `EXISTS` subqueries.

Related JIRA tickets : https://bluesquare.atlassian.net/browse/SLEEP-1458

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Print screen / video

https://github.com/user-attachments/assets/311c8ad4-db7c-4767-a15d-6666ad4d332f

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-08-09 10:03 UTC, quang-le requested changes
Some code style changes + 2 blocking:
- Please adapt `useGetFormDescriptor` to avoid double fetch + fetching all forms on instances page
- Dependencies array of `useMemo` should not be incomplete

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/requests/forms.ts
> +    }
nitpick but I'm not a big fan of this pattern
```suggestion
    const apiUrl = '/api/forms/?fields=id,name,latest_form_version'; // I would even hoist that outside of the hook
    const url = fields ? `${apiUrl},${fields.join(',')}` : apiUrl;
```

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/requests/forms.ts
> +        queryFn: () => getRequest(url),
If you merge the previous suggestion:

```suggestion
        queryFn: () => getRequest(apiUrl),
```

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetFormDescriptor.ts
> +    return getRequest(`/api/formversions/?form_id=&fields=descriptor`);
If you need to skip the form id for the feature to work, I would split the code or add a parameter to `useGetFormDescriptor` as it needlessly increases the payload of the request for the submission/instances page (where the form id is known).

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetFormDescriptor.ts
> +            // enabled: Boolean(formId), TODO
Same as above: removing this duplicates the API call on the submissions page

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
> +    }, [isFetchingForms]);
```suggestion
    }, [isFetchingForms, allForms]);
```
You need to update the return value if `allForms` change. Normally your linter should warn you if your deps array is incomplete.

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
> +        let allPossibleFields: PossibleFieldsForForm[] = [];
```suggestion
        const allPossibleFields: PossibleFieldsForForm[] = [];
```
Pushing values into the array doesn't change its reference, so its safe (and preferred) to declare it with `const`

2024-08-09 10:03 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
> +    }, [isFetchingForms]);
If done on purpose, please leave a comment explaining the reason why, and why it's safe to do so

2024-08-09 13:38 UTC, kemar reviewed
Backend LGTM

Kudos because this is advanced work with the ORM.

I'm also concerned with performance and curious to hear about how Trypelim's going to handle it.

2024-08-09 13:38 UTC, kemar commented on iaso/utils/jsonlogic.py
>          )
I know that was implemented before and this is largely a personal preference but… every time I see a `reduce()` call, I need to go read the doc to understand what's actually happening.

I tend to think that an accumulation loop is easier to understand, e.g.

```python
sub_query = Q()
for lookup in jsonlogic["and"]:
    sub_query = operator.and_(sub_query, func(lookup, field_prefix))
return sub_query
```

2024-08-09 13:38 UTC, kemar commented on iaso/tests/api/test_entities.py
> +        # )
Maybe this could be deleted then?

2024-09-04 11:44 UTC, bramj commented
> Backend LGTM
> 
> Kudos because this is advanced work with the ORM.
> 
> I'm also concerned with performance and curious to hear about how Trypelim's going to handle it.

So far so good! But it's only on about 100K beneficiaries for now. The good part about the QueryBuilder is that the frontend is already prepared for if/when we want to use something like Elastic search to return the results from the backend.

2024-09-04 11:44 UTC, bramj commented on hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetFormDescriptor.ts
> +    return getRequest(`/api/formversions/?form_id=&fields=descriptor`);
Yes absolutely, it needs to be a separate hook, totally forgot this TODO

2024-09-04 11:44 UTC, bramj commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/requests/forms.ts
> +    }
Not sure I find it more readable, but changed :+1:

2024-09-04 11:44 UTC, bramj commented on hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
> +    }, [isFetchingForms]);
Hm good catch, my linter didn't tell me anything about this, should it come from the `show-lint-problems` task?

2024-09-04 11:44 UTC, bramj commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/requests/forms.ts
> +        queryFn: () => getRequest(url),
I've made the changes you proposed :+1: there it's the `url` we want though

2024-09-05 11:45 UTC, beygorghor approved these changes
Small remarks, i'm just wondering if the call to get all forms and their possible field won't crash at some point, do we use some cache in this ?

2024-09-05 11:45 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetQueryBuildersFields.ts
> +    }
```suggestion
export const useGetQueryBuilderFieldsForAllForms = (
    formDescriptors?: FormDescriptor[],
    allPossibleFields?: PossibleFieldsForForm[],
): QueryBuilderFields => {
    if (!allPossibleFields || !formDescriptors) return {};
    
    return allPossibleFields.reduce((fields, { form_id, name, possibleFields }) => {
        fields[form_id] = {
            label: name,
            type: '!group',
            mode: 'array',
            conjunctions: ['AND', 'OR'],
            operators: ['some', 'all', 'none'],
            defaultOperator: 'some',
            subfields: useGetQueryBuildersFields(formDescriptors, possibleFields),
        };
        return fields;
    }, {} as QueryBuilderFields);
};
```

2024-09-05 11:45 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/forms/fields/hooks/useGetQueryBuildersFields.ts
> +    }
not a big fan of iterators

2024-09-05 11:45 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
> +};
😮  Do you really get all possible fields for all forms ? this is a huge query to the backend and can be a big payload. This is one reason why we have to preselect a form to enable querybuilder on instances page

2024-09-05 12:30 UTC, beygorghor commented
can you please move those fields 
<img width="1653" alt="Screenshot 2024-09-05 at 14 24 51" src="https://github.com/user-attachments/assets/ccf68700-bc66-4a05-ad0d-3667f7d9c503">

2024-09-12 12:59 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/useGetPossibleFields.ts
> +    }, [isFetchingForms]);
It's from `react-hooks/exhaustive-deps`

2024-09-12 13:21 UTC, quang-le approved these changes

2024-09-12 13:21 UTC, merged