IA-3206-IA-3207: Move and add projects columns and filters on User and OrgUnit pages
BLSQ/iaso pull request #1543
Opened 2024-08-08 14:06 UTC by hakifran

Explain what problem this PR is resolving
- Move and add projects columns and filters on User and OrgUnit pages
- Remove some columns and move others on User and OrgUnit Pages
Related JIRA tickets : [IA-3206](https://bluesquare.atlassian.net/browse/IA-3206) [IA-3207](https://bluesquare.atlassian.net/browse/IA-3207)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes
- Move projects filter on both user and org unit page
- Removed groups column from org unit page
- Move created column on org unit page

## How to test
- Go on User page and check if the change are same as on the [mockup](https://whimsical.com/multi-project-web-interfaces-modifications-LRbazNKxybyqpULUQiKcJx)
- Go on org unit page and check also if change are same as on the [mockup](https://whimsical.com/multi-project-web-interfaces-modifications-LRbazNKxybyqpULUQiKcJx)

## Print screen / video
### Org unit page
![Screenshot-from-2024-08-08-16-02-01](https://github.com/user-attachments/assets/5992a4ab-3a28-48e9-9adf-a6601466cbe3)
### User page
![Screenshot-from-2024-08-08-16-02-12](https://github.com/user-attachments/assets/6224c449-459c-4a0e-8186-815ab20cc30c)

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-08-08 14:12 UTC, hakifran commented
@cypress

2024-08-09 08:00 UTC, hakifran commented
@cypress

2024-08-09 08:33 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/users/components/Filters.js
>          <Grid container spacing={2}>
Shouldn't this file be only in #1543? https://github.com/BLSQ/iaso/pull/1543/files#diff-ccea35154e8e5addc9406224be919591e706ee788f0b33c25084e1234afbf295

2024-08-09 08:36 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/users/components/Filters.js
>          <Grid container spacing={2}>
Sorry, my mistake, I think I mixed up some PRs.

2024-08-09 09:14 UTC, kemar requested changes
I suggested a way to fix a N+1 problem in backend queries here https://github.com/BLSQ/iaso/pull/1547

Also Cypress tests are failing, can you please fix them?

2024-08-09 09:14 UTC, kemar commented on iaso/tests/api/test_orgunits.py
> +        with self.assertNumQueries(8):
You have a N+1 here.

I suggest this to fix it https://github.com/BLSQ/iaso/pull/1547

2024-08-12 08:03 UTC, kemar approved these changes
LGTM

2024-08-12 09:36 UTC, merged