IA-3102: Permissions : Org unit “view only” permission
BLSQ/iaso pull request #1558
Opened 2024-08-19 12:25 UTC by hakifran

Explain what problem this PR is resolving
- Permissions : Org unit “view only” permission
Related JIRA tickets : [IA-3102](https://bluesquare.atlassian.net/browse/IA-3102)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Add new Organisation units - Read permission
- Check on create_org_unit and edit org unit the Organisation units management permission
- Hide some button and action if the user has not Organisation units management permission on frontend

## How to test
- Create or update a user and remove the Organisation units management and add Organisation units - Read permission to it
- Check all the actions for create and update org units are possible

## Print screen / video
[Screencast from 2024-08-19 14-23-35.webm](https://github.com/user-attachments/assets/781f2a0b-29a3-4287-a6f6-1f022fe8121d)

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-08-21 13:58 UTC, kemar requested changes
I've testes it locally by adding just the read-only perm to a user but I can't see any org unit in the list and I've got a bunch of 403.

Is this normal?

https://github.com/user-attachments/assets/47f63fb9-47ae-4f89-a0f5-db70934d9518

2024-08-21 13:58 UTC, kemar commented on iaso/tests/api/test_orgunits.py
> +        """Check tha we can only modify a part of the fille"""
```suggestion
        """Check that we can only modify a part of the file"""
```

Is this docstring really accurate?

This test seems to ensure that an update is not possible with the read perm.

It looks very much like the test above.

2024-08-21 15:59 UTC, hakifran commented
> I've tested it locally by adding just the read-only perm to a user but I can't see any org unit in the list and I've got a bunch of 403.
> 
> Is this normal?
> Screen.Recording.2024-08-21.at.15.54.46.mov

That's right, I omitted the read permission on the groups, data source. It is fixed with the [commit](https://github.com/BLSQ/iaso/pull/1558/commits/728fcb1dba3c45c81f931936893a2679fdeb5dff)

2024-08-22 09:01 UTC, kemar commented on iaso/tests/api/test_orgunits.py
> +        """Check tha we can only modify a part of the fille"""
@hakifran what do you think about that? Is this test required? Because it seems like a duplicate of the one above?

2024-08-22 09:18 UTC, hakifran commented on iaso/tests/api/test_orgunits.py
> +        """Check tha we can only modify a part of the fille"""
Refactored too, I just pushed the changes

2024-08-22 09:34 UTC, kemar commented
Almost good to me.

My last concern is a UI problem:

- if you can just READ org units
- only form buttons are removed
- so you still see inputs elements
- this can make a user believe an input can be changed

I guess it's OK because there are no spec on this in the Jira ticket…

What do you think?

![ui](https://github.com/user-attachments/assets/750abbe8-7e55-45ac-b2a9-bcec8bef336a)

2024-08-22 09:42 UTC, hakifran commented
> Almost good to me.
> 
> My last concern is a UI problem:
> 
>     * if you can just READ org units
> 
>     * only form buttons are removed
> 
>     * so you still see inputs elements
> 
>     * this can make a user believe an input can be changed
> 
> 
> I guess it's OK because there are no spec on this in the Jira ticket…
> 
> What do you think?
> 
> ![ui](https://private-user-images.githubusercontent.com/281139/360373113-750abbe8-7e55-45ac-b2a9-bcec8bef336a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk5ODksIm5iZiI6MTcyNDMxOTY4OSwicGF0aCI6Ii8yODExMzkvMzYwMzczMTEzLTc1MGFiYmU4LTdlNTUtNDVhYy1iMmE5LWJjZWM4YmVmMzM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwOTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTFjODM0OGQ1YTg2ZWZmYmQ0NGFkMzAyMjFhNTJjMGQxNjhhNzYwZTNlMTU2OWEzMWJmMzczMjk0MDZlMjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5IT-7x-guMll478hmJl_D9vHo42kKoPCip_qDVev91w)

I think you are right we should disable the inputs too. Thank you, let me fix it!

2024-08-22 13:28 UTC, hakifran commented
> Almost good to me.
> 
> My last concern is a UI problem:
> 
>     * if you can just READ org units
> 
>     * only form buttons are removed
> 
>     * so you still see inputs elements
> 
>     * this can make a user believe an input can be changed
> 
> 
> I guess it's OK because there are no spec on this in the Jira ticket…
> 
> What do you think?
> 
> ![ui](https://private-user-images.githubusercontent.com/281139/360373113-750abbe8-7e55-45ac-b2a9-bcec8bef336a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk1NjUsIm5iZiI6MTcyNDMxOTI2NSwicGF0aCI6Ii8yODExMzkvMzYwMzczMTEzLTc1MGFiYmU4LTdlNTUtNDVhYy1iMmE5LWJjZWM4YmVmMzM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwOTM0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzEyYjQ3OWI5ZjAyNmIxN2VhN2Q5YTcyMTNlY2U0NWY3NTExYTY0NzUyYTU0NzQ2ZTgyM2M5YjE4NzZlNGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cy3-Dri0PEFdLQIJj_R-pUvptwORP9vpj7A2JFnUU-M)

I'v just pushed the commit about disabling inputs when the use has not org unit managament permission. But there is on input  `<InputComponent
                keyValue="aliases"
                onChange={onChangeInfo}
                value={orgUnitState.aliases.value}
                type="arrayInput"
            />` Which I made a fix but which I think the change(disabled should be added to bluesquare-component)

2024-08-22 13:44 UTC, kemar approved these changes
LGTM

2024-08-22 13:48 UTC, merged