POLIO-1645 POLIO-1646  IA-1647  incident reports improvements
BLSQ/iaso pull request #1575
Opened 2024-08-22 14:05 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : POLIO-1645 POLIO-1646  IA-1647  

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
Some doc is present on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx

## Changes

- added title and comment to incident report model + migrations
- added those field in form
- added Other option in types, not displayed in the frontend for now as POLIO-1650 ticket is hold due to the complexity of the feature
- review number inputs logic on the frontend to make it clear and match to this:
<img width="845" alt="Screenshot 2024-08-22 at 12 23 26" src="https://github.com/user-attachments/assets/664d6ca7-02e0-4a48-bd65-7c6a92a4a82c">

## How to test

Open a stock variation for a country with existing data. 
<img width="350" alt="Screenshot 2024-08-22 at 16 03 04" src="https://github.com/user-attachments/assets/fb379ed0-2a2a-4757-aa9e-cfd638030885">

open the details for one entry and click on stock variation.
Select Incident reports tab .
Edit and create reports, check it matches the sheet
Add title and comment and save.

## Print screen / video

<img width="809" alt="Screenshot 2024-08-22 at 15 58 01" src="https://github.com/user-attachments/assets/6e6346f5-af69-47df-8bee-da22ef7fbb66">
<img width="977" alt="Screenshot 2024-08-22 at 15 57 55" src="https://github.com/user-attachments/assets/b1643050-134a-415c-be56-36b5a7cc9581">
<img width="742" alt="Screenshot 2024-08-22 at 15 57 49" src="https://github.com/user-attachments/assets/16b2769e-52f8-40e2-833a-419735c53978">
<img width="1646" alt="Screenshot 2024-08-22 at 15 57 43" src="https://github.com/user-attachments/assets/e7a21147-5d44-45ec-ae49-81f81aac36ef">

2024-08-23 10:03 UTC, quang-le requested changes
Some movements are not translated in the usable/unusable tables:
![Screenshot 2024-08-23 at 11 56 03](https://github.com/user-attachments/assets/5d0cd073-a154-4d30-a9ad-12101416b2d5)

Otherwise nothing really blocking front-end side

Changes should be made in the backend for the movements that remove usable vials without adding the equivalent unusable vials.
I don't know if it's ok to merge the front-end changes without the backend fix, but without it, such movements are not shown in the main tables :

https://github.com/user-attachments/assets/6acbb5d6-1541-4c0d-8855-48922f04cd38

Jira ticket created for this issue: https://bluesquare.atlassian.net/browse/POLIO-1655

Adjacent to this PR, the table of incident reports is not very legible, since the columns "usable vials" and unusable vials show In and OUT movements in the same column:

![Screenshot 2024-08-23 at 10 21 07](https://github.com/user-attachments/assets/c52f54d9-dc25-4a59-9d42-48410f572795)

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/api/vaccines/stock_management.py
> +                or report.stock_correction == IncidentReport.StockCorrectionChoices.OTHER
This is another PR no?

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/api/vaccines/stock_management.py
> +                or report.stock_correction == IncidentReport.StockCorrectionChoices.OTHER
same same

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
> +    }, [incident]);
Couldn't you use `useMemo` instead, to pass the return value directly to formik?
Honest question, I can imagine that we would want the value passed to `initialValues` to be static, and not "stateful".

Alternately, I think you can move the function outside of the component:
```typescript
const getInitialMovement = (incident) => {
        if (!incident) return 0;
        const movementType = incidentReportConfig[incident.stock_correction];
        return movementType === 'inventory' ? 0 : incident.usable_vials;
    }
```

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
> +    };
Can be moved out of the component

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
> +    };
same same

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Modals/CreateEditIncident.tsx
> +                {currentMovementType && currentMovementType === 'inventory' && (
`currentMovementType` cannot be equal to `'inventory'` if it's falsy 😉

2024-08-23 10:03 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/StockVariation/Table/columns.tsx
> +            },
You could use `BreakWordCell` here

2024-08-23 16:01 UTC, quang-le approved these changes

2024-08-23 16:01 UTC, quang-le commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/useGetMovementDescription.ts
> +};
That should be `useCallback` no?

2024-08-26 08:14 UTC, beygorghor commented on plugins/polio/js/src/domains/VaccineModule/StockManagement/hooks/useGetMovementDescription.ts
> +};
This is o, fact returning a string, so not necessary i would say

2024-08-26 08:30 UTC, merged