POLIO-1627 Allow to filter chronograms by campaign
BLSQ/iaso pull request #1584
Opened 2024-08-26 14:33 UTC by kemar

# WIP

---

Allow to filter chronograms by campaign.

Related JIRA tickets : [POLIO-1627](https://bluesquare.atlassian.net/browse/POLIO-1627)

## Changes

TODO

## How to test

TODO

## Print screen / video

TODO

2024-08-28 09:11 UTC, quang-le requested changes
1 question and 1 small blocking change in the front-end.

Question: The spec doesn't mention it but wouldn't it be "safer"  to enable multi select on the campaign filter? 

Blocking change: remove conditional rendering of the filters and use loading state for the campaign filter instead

2024-08-28 09:11 UTC, quang-le commented on plugins/polio/api/chronogram/views.py
> +            .order_by("round__campaign__id")
Wouldn't it make more sense to order by `obr_name` for the front-end?

2024-08-28 09:11 UTC, quang-le commented on plugins/polio/js/src/domains/Chronogram/Chronogram/index.tsx
> +
You could call that hook directly in `ChronogramFilters` since you don't use the data here and just pass it as props

2024-08-28 09:11 UTC, quang-le commented on plugins/polio/js/src/domains/Chronogram/Chronogram/Filters/ChronogramFilters.tsx
> +                    />
you should pass `isFetchingMetaData` as `loading` prop

2024-08-28 09:11 UTC, quang-le commented on plugins/polio/js/src/domains/Chronogram/Chronogram/index.tsx
> +            {!isFetchingMetaData && (
It would be better to render the filters and pass `isFetchingMetaData` as `loading` to the `InputComponent` in your filters

2024-08-28 09:11 UTC, quang-le commented on plugins/polio/js/src/domains/Chronogram/api/useOptionChronogram.ts
> +                    campaigns: mapChoices(data.campaigns_filter_choices),
I knew this one would be useful 😁

2024-08-28 12:11 UTC, kemar commented on plugins/polio/api/chronogram/views.py
> +            .order_by("round__campaign__id")
Seems legit 😄

2024-08-28 12:41 UTC, kemar commented
> Question: The spec doesn't mention it but wouldn't it be "safer" to enable multi select on the campaign filter?

It could be a bit of laziness but the spec doesn't mention it 🤣 Anyway it's done here https://github.com/BLSQ/iaso/pull/1584/commits/8d8cacd6457b3e229256c204a004c71b249fd51e

> Blocking change: remove conditional rendering of the filters and use loading state for the campaign filter instead

This has been fixed too.

2024-08-29 08:23 UTC, quang-le approved these changes

2024-08-29 08:24 UTC, merged