IA-3375: Export user role and project as name not as id in csv and xlsx user export
BLSQ/iaso pull request #1602
Opened 2024-08-29 14:55 UTC by hakifran

Explain what problem this PR is resolving
- The user csv export on userrole column doesn't fite the import template
Related JIRA tickets : [IA-3375](https://bluesquare.atlassian.net/browse/IA-3375)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes
- Display user role as name not as id
- Display project name instead of id

## How to test
- Go in user management
- Export csv or xlsx file
- Check the user role and project columns

## Print screen / video
[Screencast from 2024-08-29 16-53-08.webm](https://github.com/user-attachments/assets/72d5debb-dfc3-49df-98e7-85454d26f2e5)

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-08-30 09:49 UTC, quang-le requested changes
It works well, just add the missing test pls

2024-08-30 09:49 UTC, quang-le commented on iaso/tests/api/test_profiles.py
Could you add a test on the value of user roles?

2024-08-30 13:35 UTC, hakifran commented on iaso/tests/api/test_profiles.py
@quang-le I added the tests on both csv and xlsx

2024-09-11 09:25 UTC, quang-le approved these changes

2024-09-11 09:27 UTC, merged