IA-3338: Add fiter "Project" on Form statistics
BLSQ/iaso pull request #1606
Opened 2024-09-02 15:00 UTC by hakifran

Explain what problem this PR is resolving
- Add fiter "Project" on Form statistics
Related JIRA tickets : [IA-3338](https://bluesquare.atlassian.net/browse/IA-3338)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes
- Added projects filter on front-end form stats page
- Add projects filter in back-end on form stats api

## How to test
- Forms --> Form statistics
- Check if the projects filter works where

## Print screen / video
[Screencast from 2024-09-02 16-59-12.webm](https://github.com/user-attachments/assets/824a9929-712a-4d44-9962-6ea4fc99acf2)
## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-09-04 09:45 UTC, quang-le requested changes
The alignment of the filter and the button is off.

![Screenshot 2024-09-04 at 11 08 02](https://github.com/user-attachments/assets/331ad07d-557c-4d1b-8c8d-afb860c6edd4)

Code comments are for style/good practice.

2024-09-04 09:45 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/stats.tsx
tsx, nice 😀

2024-09-04 09:45 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/UseGetFormStats.tsx
> +};
Nice re-usable hook. 
What I would do is make a wrapper on this hook for each stat (stat and stat sum). 
That way we won't have to go to the component to figure out what the query key when debugging.

2024-09-04 09:45 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/UseGetFormStats.tsx
> +    baseUrl,
Pass `params`instead, they are already available in the parent

2024-09-04 09:45 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/UseGetFormStats.tsx
> +        queryKey: [queryKey, params],
Pass `apiUrl` instead of `params`. Not especially blocking, but the idea is that the API call will change when the `apiUrl` changes.
It doesn't make a difference here, but with paginated calls, we sometimes don't get the pagination params from the params and add them when formatting the `apiUrl`, so different sets of params can result in the same `apiUrl`. Using `apiUrl` in the `queryKey` is a small optimization of cache use

2024-09-04 09:45 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/UseGetFormStats.tsx
> +    };
Cf above: you can save yourself a hook call by passing the `params` as props

2024-09-04 09:45 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/hooks/UseGetFormStats.tsx
> +        queryKey: [queryKey, params],
Something like:
```typescript
export const useGetFormsStatsSum = params => {
    return useGetFormStats({
        params,
        url: '/api/instances/stats_sum/',
        queryKey: ['instances', 'stats_sum'],
    });
};
```

I would also use named arguments, that makes the code more legible when you have more than 2 arguments

2024-09-04 13:10 UTC, hakifran commented
> The alignment of the filter and the button is off.
> 
> ![Screenshot 2024-09-04 at 11 08 02](https://private-user-images.githubusercontent.com/38907762/364322750-331ad07d-557c-4d1b-8c8d-afb860c6edd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDM3ODksIm5iZiI6MTcyNTQ0MzQ4OSwicGF0aCI6Ii8zODkwNzc2Mi8zNjQzMjI3NTAtMzMxYWQwN2QtNTU3Yy00ZDFiLThjOGQtYWZiODYwYzZlZGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiY2Y4N2RkYWU0ZGQwNTQ4YTg5OGJiNDExYjc2NTA3MzIzYmUzMTBiNDdlMDJhYzc3YjIyNGJhNGU0ZmEyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u02tm297XDhgz9foG8MoYQGbY4kzKKBMulixJiPN7kI)
> 
> Code com
![Screenshot from 2024-09-04 14-32-06](https://github.com/user-attachments/assets/3604c5bf-0ef9-44de-8f14-ab98c7e0293a)
ments are for style/good practice.

2024-09-05 12:00 UTC, quang-le approved these changes

2024-09-05 12:01 UTC, merged