Feat: improve profile api performance
BLSQ/iaso pull request #1607
Opened 2024-09-02 15:49 UTC by madewulf

By removing useless data and prefetching useful data

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-09-06 10:39 UTC, hakifran requested changes
I don't know if it's only on my local machine but these changes crushed test_upload_valid_csv and test_upload_valid_csv_with_perms test.

2024-09-06 10:39 UTC, hakifran commented on iaso/models/base.py
> +            print("not small")
I think this print should be removed

2024-09-06 10:39 UTC, hakifran commented on iaso/models/org_unit.py
> +        res = {
Not blocking but I think this dict should be return directly without passing it to res before to return it

2024-09-09 07:59 UTC, madewulf commented
@hakifran there are changes to the test files https://github.com/BLSQ/iaso/pull/1607/files#diff-bc4da97802d782f1e9e50fc072a80ed8b252157a2e01b866130dfada1634e964 but that should not delete the files on your machine

2024-09-09 09:30 UTC, hakifran approved these changes

2024-09-09 09:35 UTC, merged