Ia 3364 user history front end
BLSQ/iaso pull request #1615
Opened 2024-09-09 10:58 UTC by quang-le

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-09-11 11:30 UTC, beygorghor requested changes
- you need to invalid logs while updating a user profile, i had to refresh logs to see changes 
https://github.com/user-attachments/assets/72d17b70-300b-4414-bc8f-37b555f64ed8


- While on a user management or history, this is not reflected in the side menu
Uploading Screen Recording 2024-09-11 at 13.23.45.mov…

- introducing a wrong phone number should show an error above the field
<img width="989" alt="Screenshot 2024-09-11 at 13 24 57" src="https://github.com/user-attachments/assets/924eab63-6e52-4399-8bc3-551cc835bf93">

2024-09-11 11:33 UTC, beygorghor commented
We can also probably only display when password has been changed also:

<img width="1573" alt="Screenshot 2024-09-11 at 13 32 40" src="https://github.com/user-attachments/assets/0bac5461-4809-47c6-8a6c-28595fa5ae01">

2024-09-12 13:25 UTC, quang-le commented
> * you need to invalid logs while updating a user profile, i had to refresh logs to see changes
>       https://github.com/user-attachments/assets/72d17b70-300b-4414-bc8f-37b555f64ed8
> 
>     * While on a user management or history, this is not reflected in the side menu
>       Uploading Screen Recording 2024-09-11 at 13.23.45.mov…
> 
>     * introducing a wrong phone number should show an error above the field
> 
> 
> <img alt="Screenshot 2024-09-11 at 13 24 57" width="989" src="https://private-user-images.githubusercontent.com/12494624/366437488-924eab63-6e52-4399-8bc3-551cc835bf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDc1OTIsIm5iZiI6MTcyNjE0NzI5MiwicGF0aCI6Ii8xMjQ5NDYyNC8zNjY0Mzc0ODgtOTI0ZWFiNjMtNmU1Mi00Mzk5LThiYzMtNTUxY2M4MzViZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDEzMjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZGFiMmE3M2JjM2I5MDlmMTczYzYyMjA2ODM0YWVjNTJkOTQ5NjNkMWNmMzY5OWY4ZWNiYzI4OWUwNzA0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dzQja14ya-5yemOunjdE4wpkDMSSy8681tMVtjvXtjc">

Showing errors in phone number field is a bit out of scope for this PR in my opinion. Anyway, it would require using the exact same validation list as the backend. I didn't use it in the `PhoneNumber` component, because it's not always reliable (I managed to invalidate a valid belgian number when testing)  and I didn't want to exclude valid phone numbers.

2024-09-13 08:20 UTC, beygorghor approved these changes

2024-09-13 09:43 UTC, merged