Ia 3443 oucrc web create update
BLSQ/iaso pull request #1645
Opened 2024-09-20 10:43 UTC by tdethier

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-09-25 13:37 UTC, tdethier commented
@beygorghor I've just committed my latest changes. You'll find the todo list in the PR description :wink:

2024-09-27 14:03 UTC, beygorghor commented
For the filtering of types and add some test on creation an update we created 2 other tickets:
IA-3461 and IA-3460.

https://github.com/user-attachments/assets/650e7425-a19b-4f7e-aa0d-3f5696d159e0

2024-09-30 13:39 UTC, quang-le commented on .eslintrc.json
> +      "prefer-arrow-callback": "error",
❤️

2024-09-30 15:20 UTC, quang-le requested changes
In the code, the onmy blocking change is the one in the python code with the raised exception.

The feature works foinr for the golden path, but I can't figure out the edge cases.

On the layout side, the filter button should be aligned on the right:
![Screenshot 2024-09-30 at 17 17 16](https://github.com/user-attachments/assets/01bad373-1433-4016-abc1-d50f0819ce16)

And its layout is broken on 1200 wide screens:

![Screenshot 2024-09-30 at 17 17 11](https://github.com/user-attachments/assets/2bf843e9-1e07-4453-89b3-b47980b0a8ca)

Nice job, that was quite a complex layout

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                Project: {config.project.name}
"Project" should be translated

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                Org Unit Type: {config.orgUnitType.name}
"Org Unit Type" should be translated

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                values.editableFields.includes('possibleTypeIds') && (
```suggestion
            {values?.editableFields?.includes('possibleTypeIds') && (
```

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                values.editableFields.includes('possibleParentTypeIds') && (
```suggestion
            {values?.editableFields?.includes('possibleParentTypeIds') && (
```

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                values.editableFields.includes('editableReferenceFormIds') && (
```suggestion
            {values?.editableFields?.includes('editableReferenceFormIds') && (
```

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                values.editableFields.includes('otherGroupIds') && (
```suggestion
            {values?.editableFields?.includes('otherGroupIds') && (
```

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialogCreateFirstStep.tsx
> +        useGetOUCRCCheckAvailabilityDropdownOptions(values.projectId);
dat name 😂

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Tables/EditableFieldsCell.tsx
> +    const editableFields = computeEditableFields(original);
useMemo

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useSaveOrgUnitChangeRequestConfiguration.ts
> +    };
move it out of `mapValuesForSaving` , like `cleanEditableFieldsForSaving`

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useSaveOrgUnitChangeRequestConfiguration.ts
> +const patchOrgUniType = async (
`patchOrgUnitType`?

Also, why not `patchOUCRC` or something in that vein?

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/api/useSaveOrgUnitChangeRequestConfiguration.ts
> +const postOrgUnitType = async (body: ApiValues): Promise<any> => {
same same

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/useValidationSchemaOUCRC.ts
> +            otherwise: yup.string().nullable(),
This looks the same to me as `otherGroupIds: yup.string().nullable()`

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/useValidationSchemaOUCRC.ts
> +                otherwise: yup.string().nullable(),
same

2024-09-30 15:20 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/hooks/useValidationSchemaOUCRC.ts
> +            otherwise: yup.string().nullable(),
same

2024-09-30 15:20 UTC, quang-le commented on iaso/api/group_sets/views.py
> +            project = Project.objects.get_for_user_and_app_id(user, app_id)
This will `raise` if no project is found

2024-10-01 08:31 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/configuration/Dialog/OrgUnitChangeRequestConfigDialog.tsx
> +                Project: {config.project.name}
c

2024-10-01 09:41 UTC, quang-le approved these changes

2024-10-01 10:16 UTC, merged