IA-3123: Review the look and feel of permissions list (with Read/Write)
BLSQ/iaso pull request #1664
Opened 2024-10-01 11:04 UTC by hakifran

Explain what problem this PR is resolving
- Review the look and feel of permissions list (with Read/Write)
Related JIRA tickets : [IA-3123](https://bluesquare.atlassian.net/browse/IA-3123)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

- Added a READ_EDIT_PERMISSIONS constant in hat/menupermissions/constants.py
- Format Permissions to include the matching read-edit
- Display the matching read-edit permission
- Replace Switch component by checkbox
- Add translations

## How to test
- Go Admin ---> Users ---> Management and Go to Admin ---> User Roles
- Create or edit a user and a user role
- Add and remove permissions and specifically those with read and edi permission

## Print screen / video
[Screencast from 2024-10-01 13-02-18.webm](https://github.com/user-attachments/assets/e043fb8d-b0f1-4aa9-95a2-c214e5b434c1)
 
[Screencast from 2024-10-01 13-02-55.webm](https://github.com/user-attachments/assets/3930ed07-bc43-43a9-b10b-726f08bd14ae)

2024-10-02 09:04 UTC, beygorghor requested changes
Good job, We will improve lay-out a bit after. I'm just wondering why you have read twice in the checkboxes? it should be read and write no ?

<img width="594" alt="Screenshot 2024-10-02 at 10 46 39" src="https://github.com/user-attachments/assets/7ece565e-b9ba-4845-812f-a4bd70c6ecd0">

2024-10-02 09:04 UTC, beygorghor commented on docs/pages/dev/how_to/add_new_permission/add_new_permission.md
> +
In order to display a new permission in the dashboard you need to add it to PERMISSIONS_PRESENTATION too no ?

2024-10-02 09:04 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/PermissionCheckBoxs.tsx
PermissionCheckBoxes

2024-10-02 09:04 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/PermissionCheckBoxs.tsx
> +    type,
This is never used

2024-10-02 09:04 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/PermissionCheckBoxs.tsx
> +    const handleCheckboxChange = (
useCallback can be nice here

2024-10-02 09:04 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/config.js
>                  Cell: settings => {
Thie cell is too big, we need to create another component aside for this

2024-10-02 09:04 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/config.js
> +                                            <Stack
never used this, well done ❤️

2024-10-02 09:11 UTC, hakifran commented
> Good job, We will improve lay-out a bit after. I'm just wondering why you have read twice in the checkboxes? it should be read and write no ?
> <img alt="Screenshot 2024-10-02 at 10 46 39" width="594" src="https://private-user-images.githubusercontent.com/12494624/372803201-7ece565e-b9ba-4845-812f-a4bd70c6ecd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjA0ODMsIm5iZiI6MTcyNzg2MDE4MywicGF0aCI6Ii8xMjQ5NDYyNC8zNzI4MDMyMDEtN2VjZTU2NWUtYjliYS00ODQ1LTgxMmYtYTRiZDcwYzZlY2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA5MDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZmEzMjhiN2Y5ZDljYWVkZGEzOTEwNjg2ZmQ1NTRmZTFhN2RkYjg4MmFjZDMxNTk0NzczMjg2Y2Y5ZTg5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xoIF73nkEe4pHZMvP4YApL5322gF_V6MTGOLHc5zqnI">

Yeah it's a translation issue: `"iaso.permissions.readEdit.edit": "Read",`. I Will fix that

2024-10-02 13:11 UTC, hakifran commented on docs/pages/dev/how_to/add_new_permission/add_new_permission.md
> +
It's done on third point before the added description(4th)

2024-10-04 11:04 UTC, beygorghor approved these changes
I have updated your branch with main and resolve conflicts. I have tested it after and works like a charm

2024-10-04 11:24 UTC, merged