POLIO-681 Mark node as completed when there is an alternative path
BLSQ/iaso pull request #167
Opened 2022-11-14 13:30 UTC by olethanh

When we use a diamond to modelize that  a double approval is neeeded, add a way to mark the 'skipped' path as completed
 We do this by adding a mark_nodes_as_completed property on Node

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [] Did I add translations
- [x] My migrations file are included
- [x]  Are there enough tests

## Changes

- Add a `mark_nodes_as_completed` property in the workflow definition. When we pass by a node that has this property mark all the node listed (in the same category) as completed at the same time
- Re active the widget
- Fix crash in it.
- Fix calculation for Active and completed Category

## How to test

See wiki page on wikijs

The workflow definition in the fixture has been updated (for GPEI consolidation) so if you update your database with it you should have a correct workflow.

2022-11-14 15:38 UTC, quang-le requested changes
I'm afraid limiting the scope of `mark_nodes-as_completed` the the nodes in the same category will be too limiting. For example, final  approval for polio budgets is in another category as the steps/nodes that lead to it.

Other than that it's very neat. It means also that we must be careful with the config or the widget may display wrong information, but I guess it would have been true of any solution that decouples the widget state from the workflow state

2022-11-14 15:38 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
> +    }, [categories]);
nice !

2022-11-14 15:38 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
> +                        // active={category.active}
I think we can just keep a comment and delete the commented props

2022-11-14 15:38 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetTimeline.tsx
> +                        // active={category.active}
nitpick

2022-11-14 15:38 UTC, quang-le commented on plugins/polio/budget/workflow.py
> +    # must be in the same category
This will not work for final approval I think

2022-11-15 15:24 UTC, olethanh commented
As discussed in meeting. We have decided on modifying the definition to resolve the last issues raised. We will move "Approval" out of it's own category. We will also move the feedback loop to new nodes which will be in the same category  as for approval.

2022-11-15 15:27 UTC, quang-le commented
> As discussed in meeting. We have decided on modifying the definition to resolve the last issues raised. We will move "Approval" out of it's own category. We will also move the feedback loop to new nodes which will be in the same category as for approval.

Which can all be handled by modifying the json config

2022-11-15 15:28 UTC, quang-le approved these changes

2022-11-16 07:13 UTC, merged