IA-3482:  popups + remove Redux
BLSQ/iaso pull request #1729
Opened 2024-10-18 14:17 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc
- Tell us where the doc can be found (docs folder, wiki, in the code...)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2024-10-23 16:28 UTC, quang-le requested changes
Awesome job.! The architecture of these components is much less complicated now.

I just have a bug in Org Units > details> map tab: the org unit id is undefined so the pop up won't fetch and stays loading for ever:

https://github.com/user-attachments/assets/6dbb70c2-3876-452a-9c23-67316644793b

2024-10-23 16:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/actions.js
YES!

2024-10-23 16:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/ExportInstancesDialogComponent.js
> -)(injectIntl(ExportInstancesDialogComponent));
❤️

2024-10-23 16:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/index.js
> +        useState(false);
Couldn't we move this state to the child?

2024-10-23 16:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/hooks/speedDialActions.tsx
> -                                isDisabled={isInstancesFilterUpdated}
should we not disable it anymore?

2024-10-24 09:52 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/hooks/speedDialActions.tsx
> -                                isDisabled={isInstancesFilterUpdated}
nope isInstancesFilterUpdated is for the list of submissions, this hook is used only on the detail page (SpeedDialInstance => details)

2024-10-24 10:02 UTC, quang-le approved these changes

2024-10-24 10:04 UTC, merged