WC2-523: [WEB] NFC card field shows 0 for all beneficiaries even when card is assigned
BLSQ/iaso pull request #1735
Opened 2024-10-23 09:20 UTC by hakifran

Explain what problem this PR is resolving
- [WEB] NFC card field shows 0 for all beneficiaries even when card is assigned
Related JIRA tickets : [WC2-523](https://bluesquare.atlassian.net/browse/WC2-523)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Add nfc_cards count in the entity dict and serializer
- Link the StorageLogEntry to the right entity if the import is from mobile(entity_uuid)

## How to test
- 

## Print Screen/video
[Screencast from 2024-10-23 11-18-46.webm](https://github.com/user-attachments/assets/0e4f4e57-a314-4fdd-b97c-5c6d0d571793)

2024-10-24 09:49 UTC, bramj requested changes
Nice! The counts work :+1: I have a few doubts about performance issues as the logs table grows, but I think it might be difficult to fix, see comments.

Main thing is I think there's something missing on this screen:
http://localhost:8081/dashboard/storages/
![image](https://github.com/user-attachments/assets/6e518b80-dc5f-45ec-a160-b6f49698fecb)
I did the setup as per instructions in the PR, but I see no beneficiary on the "General" or "Logs" entries. The status on the log is also missing (I set it to "OK" in my db).

2024-10-24 09:49 UTC, bramj commented on iaso/api/storage.py
> +                    concerned_entity = Entity.objects.get(uuid=entity_id)
:+1:

2024-10-24 09:49 UTC, bramj commented on iaso/api/entity.py
> +
I think we should be careful to add this extra query on the EntitySerializer. I also expect the amount of records in `StorageLogEntry` to grow.
 Did you try to do it with a relation and `prefetch_related`? If it's complicated then it's okay for me to go with it like this.

2024-10-24 15:01 UTC, hakifran commented
> Nice! The counts work 👍 I have a few doubts about performance issues as the logs table grows, but I think it might be difficult to fix, see comments.
> 
> Main thing is I think there's something missing on this screen: http://localhost:8081/dashboard/storages/ ![image](https://private-user-images.githubusercontent.com/2719739/379713858-6e518b80-dc5f-45ec-a160-b6f49698fecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Nzk4NDAsIm5iZiI6MTcyOTc3OTU0MCwicGF0aCI6Ii8yNzE5NzM5LzM3OTcxMzg1OC02ZTUxOGI4MC1kYzVmLTQ1ZWMtYTE2MC1iNmY0OTY5OGZlY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTQxOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThjZDdhNGY5NjY3ZDRkMGE4Yzg0Yjc1MWRkOGI3NDIwODU0NGY2MjBmNzEwNTA4OGNhNmE0MzBlZTk2ZWExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iW8GTfH_EEorSc2hZgRyGggob-OjhsKMJlR3MQr3szg) I did the setup as per instructions in the PR, but I see no beneficiary on the "General" or "Logs" entries. The status on the log is also missing (I set it to "OK" in my db).



> Nice! The counts work 👍 I have a few doubts about performance issues as the logs table grows, but I think it might be difficult to fix, see comments.
> 
> Main thing is I think there's something missing on this screen: http://localhost:8081/dashboard/storages/ ![image](https://private-user-images.githubusercontent.com/2719739/379713858-6e518b80-dc5f-45ec-a160-b6f49698fecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODIyMzksIm5iZiI6MTcyOTc4MTkzOSwicGF0aCI6Ii8yNzE5NzM5LzM3OTcxMzg1OC02ZTUxOGI4MC1kYzVmLTQ1ZWMtYTE2MC1iNmY0OTY5OGZlY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTQ1ODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI5NTc1MGVjZDBmMzQyM2E4M2Y0ZTQ3ZDczYTQ3NDRlN2Y0MmVkZDhjYWY5OWQ5YWQ0MTdlOGYxNzBlYjIzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AnSdpAHo37xtrbKPI1W0aksin4_8NgyXUiPkUldvjts) I did the setup as per instructions in the PR, but I see no beneficiary on the "General" or "Logs" entries. The status on the log is also missing (I set it to "OK" in my db).



> Nice! The counts work 👍 I have a few doubts about performance issues as the logs table grows, but I think it might be difficult to fix, see comments.
> 
> Main thing is I think there's something missing on this screen: http://localhost:8081/dashboard/storages/ ![image](https://private-user-images.githubusercontent.com/2719739/379713858-6e518b80-dc5f-45ec-a160-b6f49698fecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODIyNjYsIm5iZiI6MTcyOTc4MTk2NiwicGF0aCI6Ii8yNzE5NzM5LzM3OTcxMzg1OC02ZTUxOGI4MC1kYzVmLTQ1ZWMtYTE2MC1iNmY0OTY5OGZlY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTQ1OTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg2ZmNmODU0NmI3ZmNjNGNjZjkyYmM4MjE1NjNiYzZlNjM4YjM0NWFjMTZhZmQ2Y2RlZGY5NGZjNDc5NGEzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q-RcJUsTNBtoVrTTUHn6gDyStRGEqWM3J6HPVn3arvQ) I did the setup as per instructions in the PR, but I see no beneficiary on the "General" or "Logs" entries. The status on the log is also missing (I set it to "OK" in my db).



> Nice! The counts work 👍 I have a few doubts about performance issues as the logs table grows, but I think it might be difficult to fix, see comments.
> 
> Main thing is I think there's something missing on this screen: http://localhost:8081/dashboard/storages/ ![image](https://private-user-images.githubusercontent.com/2719739/379713858-6e518b80-dc5f-45ec-a160-b6f49698fecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODIzMDEsIm5iZiI6MTcyOTc4MjAwMSwicGF0aCI6Ii8yNzE5NzM5LzM3OTcxMzg1OC02ZTUxOGI4MC1kYzVmLTQ1ZWMtYTE2MC1iNmY0OTY5OGZlY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTUwMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVhNmFhZTVlOWU2YzU4NzU0NmE1YTc3OWVkMTY5Y2MwNzA1MmY5NjFjMmMyNzBjZjE2ODA1MWYzZmJkOTEyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6SgNomp8gagVZmVqZpOVloO5LGJbth9HeQTvpxdmn0k) I did the setup as per instructions in the PR, but I see no beneficiary on the "General" or "Logs" entries. The status on the log is also missing (I set it to "OK" in my db).

Did you link the storageDevice with the entity?
`class StorageSerializer(serializers.ModelSerializer):
    storage_id = serializers.CharField(source="customer_chosen_id")
    storage_type = serializers.CharField(source="type")
    storage_status = StorageStatusSerializer(source="*")
    entity = EntityNestedSerializer(read_only=True)
    org_unit = OrgUnitNestedSerializer(read_only=True)
    created_at = TimestampField(read_only=True)
    updated_at = TimestampField(read_only=True)

    class Meta:
        model = StorageDevice
        fields: Tuple[str, ...] = (
            "updated_at",
            "created_at",
            "storage_id",
            "storage_type",
            "storage_status",
            "org_unit",
            "entity",
        )`

2024-10-25 08:05 UTC, bramj commented
@hakifran Yes I think it's a misalignment between the returned JSON and the frontend

![image](https://github.com/user-attachments/assets/f568fdc7-b6b3-4003-b591-80151b5f081a)

Btw, I see the `name` is blank on the Entity, but in reality this will almost always be the case. So better to just display the `id` in the frontend.

2024-10-31 13:06 UTC, bramj approved these changes
Tested again and this looks very good to me :+1:

2024-10-31 13:06 UTC, bramj commented on iaso/api/entity.py
> +        )["total_logs"]
Nice! Looking good to me :+1:

2024-10-31 13:08 UTC, merged