IA-3609 Avoid `PermissionDenied` when `projects` is an empty list `[]`
BLSQ/iaso pull request #1761
Opened 2024-10-31 14:57 UTC by kemar

Avoid `PermissionDenied` when `projects` is an empty list `[]`.

Related JIRA tickets : [IA-3609](https://bluesquare.atlassian.net/browse/IA-3609)

2024-10-31 15:08 UTC, beygorghor approved these changes

2024-10-31 22:38 UTC, quang-le requested changes
This doesn't solve the problem if the edited user already has projects in their profile, because then a non-empty list is sent in the PATCH request

![Screenshot 2024-10-31 at 23 36 43](https://github.com/user-attachments/assets/a1884eb8-0bc0-4085-9745-d310cd7deaff)

2024-11-01 09:28 UTC, kemar commented
> This doesn't solve the problem if the edited user already has projects in their profile, because then a non-empty list is sent in the PATCH request

@quang-le It seems to work for me.

Do you have a precise use case to reproduce this issue or the full backend error trace?

https://github.com/user-attachments/assets/65227061-9680-4462-a3a4-d6ceda64ca34

2024-11-04 15:35 UTC, quang-le approved these changes

2024-11-04 15:35 UTC, quang-le commented on iaso/api/profiles/profiles.py
> +            if not request.user.has_perm(permission.USERS_ADMIN):
```suggestion
       projects = request.data.get("projects", [])
        profile_project_ids = set(profile.projects.values_list("id", flat=True))
        project_ids_from_request = set(map(int, projects))
        if projects:
            if not request.user.has_perm(permission.USERS_ADMIN) and profile_project_ids != project_ids_from_request:
```

2024-11-04 15:36 UTC, merged