WC2-592: Integrate Nigeria data to beneficiary table
BLSQ/iaso pull request #1778
Opened 2024-11-06 13:48 UTC by butofleury

Explain what problem this PR is resolving

Related JIRA tickets : [WC2-592](https://bluesquare.atlassian.net/browse/WC2-592)

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Splitted `**wfp**` plugin into 2 sub plugins `**south_sudan**` and `**nigeria**`, integrated the Nigeria beneficiary data and refactored the code by making the code more generic.

## How to test

From the local instance with wfp coda database, run ETL script to generate data for: 
- South Sudan : `docker compose run iaso manage etl_ssd`
- Nigeria :  `docker compose run iaso manage etl_ng`

## Print screen / video

[Administration-de-Wfp-Iaso.webm](https://github.com/user-attachments/assets/2da1e443-913c-4ab3-a506-bf3e6ef8657c)

2024-11-06 13:55 UTC, butofleury commented
This PR depends to https://github.com/BLSQ/iaso/pull/1765.

2024-11-07 13:03 UTC, bramj requested changes
I don't know the exact details of the data generated, but the scripts run well and appear correctly linked to the correct account :+1: 

General code structure question: is there a reason why you decided to add a new Django app for each country? I think adding the `etl_ssd.py` and `etl_ng.py` scripts directly into `wfp/management/commands` and adding folders there with the classes and helper functions per country would be easier. Then we would also not need anything in `settings.py`. What do you think?

2024-11-07 13:03 UTC, bramj commented on hat/settings.py
> +    "plugins.wfp.nigeria",
We should not load these plugin apps for every Iaso installation. If we really need multiple apps for WFP, we can do it with the `INSTALLED_APPS` ENV as here for Trypelim: https://github.com/BLSQ/trypelim/blob/main/plugin_settings.py

2024-11-07 13:03 UTC, bramj commented on plugins/wfp/common.py
> +        entity_type = EntityType.objects.filter(code__in=self.type)
`self.type` has become a list. I think the naming is confusing like this, we should change it to `types`.

2024-11-07 13:03 UTC, bramj commented on plugins/wfp/common.py
> +        entity_type = EntityType.objects.filter(code__in=self.type)
Actually, why exactly did this change? I see it's being called as:

```python
ETL(["pbwg_1"])
# and
ETL(["child_under_5_1"])
```

2024-11-07 13:03 UTC, bramj commented on plugins/wfp/common.py
>              # .filter(entity__id__in=[230, 359, 254])
Maybe we should clean up these comments?

2024-11-07 13:03 UTC, bramj commented on plugins/wfp/common.py
> +        if step.get("vitamins_given", None) is not None and step.get("vitamins_given", None) == "1":
Just for easier reading, I think this can be simplified into
```python
if step.get("vitamins_given") == "1":
```
Since `get` returns `None` by default when nothing's found (https://docs.python.org/3/library/stdtypes.html#dict.get)
Same for the other conditions.

2024-11-07 13:03 UTC, bramj commented on plugins/wfp/common.py
> +        elif step.get("ration_type") is not None:
Maybe irrelevant, but might be safer to do
```python
elif step.get("ration_type"):
```
which will give `False` if ration_type is an empty string?

2024-11-07 13:03 UTC, bramj commented on plugins/wfp/migrations/0013_beneficiary_account.py
> +    ]
I see no handling of existing beneficiary data (that have account `NULL`), I guess we'll do a delete all beneficiary data and re-run the scripts?

2024-11-08 06:34 UTC, butofleury commented on plugins/wfp/common.py
> +        entity_type = EntityType.objects.filter(code__in=self.type)
I did that change to align South Sudan to Nigeria. As discussed yesterday during the **WFP touchbase** , the entity type for child has been splitted to 2 entity types. 

But as we will merge the 2 types into 1 like South Sudan structure, I will fix it according to the changes will be made once the merge done.

2024-11-08 07:13 UTC, butofleury commented on plugins/wfp/migrations/0013_beneficiary_account.py
> +    ]
yes, we will do a delete all beneficiary data and re-run the scripts!

2024-11-08 14:20 UTC, bramj approved these changes
Looking good! :+1:

2024-11-08 14:22 UTC, merged