IA-3625 Mobile setup zip: Add missing API calls
BLSQ/iaso pull request #1779
Opened 2024-11-06 14:46 UTC by bramj

Added files for the groupsets and deleted entities API calls.
And a (very) small improvement to the task's progress message.

Related JIRA tickets : https://bluesquare.atlassian.net/browse/IA-3625

2024-11-07 09:05 UTC, bmonjoie requested changes

2024-11-07 09:05 UTC, bmonjoie commented on iaso/tasks/utils/mobile_app_setup_api_calls.py
> +        "path": "/api/mobile/group_sets/",
It's missing: `?showDeleted=true`

2024-11-07 09:05 UTC, bmonjoie commented on iaso/tasks/utils/mobile_app_setup_api_calls.py
>          "path": "/api/mobile/groups/",
It's missing: `?showDeleted=true`

2024-11-07 09:49 UTC, kemar approved these changes
LGTM but no clue about `?showDeleted=true`?

2024-11-07 11:34 UTC, bmonjoie commented
@kemar  The mobile must be aware of the deleted groups and groupSets because otherwise, it could receive old change requests with unknown groups/groupSets.

2024-11-08 08:48 UTC, bmonjoie approved these changes

2024-11-08 09:06 UTC, bramj commented
Just became a hotfix because urgently needed for a demo

2024-11-08 09:07 UTC, merged