Ia 1639 fix cypress ci
BLSQ/iaso pull request #180
Opened 2022-11-17 10:54 UTC by quang-le

Cypress binary was missing when running cypress manually in the CI

## Self proof reading checklist

- [NA] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [NA] Are my typescript files well typed
- [NA] Did I add translations
- [NA] My migrations file are included
- [NA] Are there enough tests
## Changes

- Replaced the caching of node_modules as per [guidelines](https://docs.cypress.io/guides/continuous-integration/introduction#Caching)
- Cached cypress binary and `.npm` folder as in [recommended example](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml)

## How to test
Run Iaso manual cypress testing in Github actions

## Print screen / video

NA

## Notes

I just fixed the missing binary issue. the tests still take a long time (20min+), but this can probably be optimized further

2022-11-17 12:13 UTC, qgerome requested changes

2022-11-17 12:13 UTC, qgerome commented on .github/workflows/cypress.yml
> -      - name: Cache dependencies
You need to keep this as by default the node_modules are not cached. You also need to keep the `id: cache` to be able to check it in the `npm ci` step.

2022-11-17 12:13 UTC, qgerome commented on .github/workflows/cypress.yml
> +      # source: https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml
This source is quite old, a lot has changed since then :p 
using `cache: npm` on the `setup/node` step will already cache the `npm cache`.

2022-11-21 10:26 UTC, codeKameleon commented
@cypress

2022-11-21 12:02 UTC, qgerome commented
@quang-le I've pushed the correct fix. It worked here: https://github.com/qgerome/iaso/actions/runs/3513836648

2022-11-21 12:06 UTC, quang-le commented
> @quang-le I've pushed the correct fix. It worked here: https://github.com/qgerome/iaso/actions/runs/3513836648

I'm curious as to why it didn't work. It worked when I tested it on Friday

2022-11-21 12:16 UTC, beygorghor commented
@cypress

2022-11-21 12:26 UTC, qgerome commented
It has to be merged to work.Quentin Gérôme Let’s Build It SRLLe 21 nov. 2022 à 13:23, github-actions[bot] ***@***.***> a écrit :﻿
Test failed: https://github.com/BLSQ/iaso/actions/runs/3514318230

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2022-11-21 12:43 UTC, quang-le commented
It works when you trigger the workflow manually (as did the config I pushed on Friday), so I'm merging this

2022-11-21 12:43 UTC, merged