IA-3540 restrict payments list by user location
BLSQ/iaso pull request #1812
Opened 2024-11-20 14:54 UTC by quang-le

geo-limited users trying to see change request related to a payment could land on an empty page if they didn't have the permission to see the org unit of the change request

Related JIRA tickets : IA-3540

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc

NA

Explain the changes that were made.

- Add `can_see_change_requests` field to `PotentialPyament` and `PaymentLot` API responses
- In the same APIs add a `can_see_change_request` for each change request
- `can_see_change_request(s)` are computed by comparing the change request org unit with the user's location
- Use these booleans in the front end to remove the link to change request(s):
   - For potential payments
   - For payment lots
   - For individual payments in payment lots 

## How to test

Explain how to test your PR.

DB setup:
- Have approved change requests, with a non-null `created_by` field (may require change to django admin in local)
- Have payment lots with change requests from several org units
- Have a geo-limited user with a location that is not a parent of at least one org unit of the approved change requests and of the payment's change requests, and the payments read-write perm
- Have a super user
- Have a geo-limited user with a location that includes all the org units in all change requests (directly or as parent), and the payments read-write perm

Test:
- Go to Potential payments page:
    -  super user and user with authorized org units should see the action icon button. It should lead them to the change requests' page, where all change requests should be visible
    - geo-limited user should not see the icon button
- Go to payment lots:
    -  super user and user with authorized org units should see the "eye" icon button. Same expected behaviour as potential payments
    - Same expected behaviour as potential payments
- Open/edit a payment lot:
    - super user and authorized user should see the action button ("eye") for all payments
    - limited user should only see it for payments for which all change requests's org units are covered by his location

## Print screen / video

Upload here print screens or videos showing the changes.

## Notes

Things that the reviewers should know:

- known bugs that are out of the scope of the PR
- other trade-offs that were made
- does the PR depends on a PR in [bluesquare-components](https://github.com/BLSQ/bluesquare-components)?
- should the PR be merged into another PR?

## Follow the Conventional Commits specification

The **merge message** of a pull request must follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

This convention helps to automatically generate release notes.

Use lowercase for consistency.

[Example](https://github.com/BLSQ/iaso/commit/8b8d7d3064138c1e57878f17b4eb922516ab0112):

```
fix: empty instance pop up

Refs: IA-3665
```

Note that the Jira reference is preceded by a _line break_.

Both the line break and the Jira reference are entered in the _Add an optional extended description…_ field.

2024-11-22 07:59 UTC, hakifran commented
@quang-le I have tested but there are some behaviors which are not clear to me.

1.  The user without a specific location can not see the view action of the potential payment
[Screencast from 2024-11-22 09-52-41.webm](https://github.com/user-attachments/assets/29b53fd8-3b13-4a22-8481-06d3517fed09)

2. The user with a specific location can not see the view action of the potential payment related to its location
[Screencast from 2024-11-22 09-54-10.webm](https://github.com/user-attachments/assets/96855246-7d6b-4300-a1db-404e823a18e9)

 Maybe I don't understand well the feature,if so share some videos on how to test it. thank you

2024-11-22 09:35 UTC, quang-le commented
> @quang-le I have tested but there are some behaviors which are not clear to me.
> 
>     1. The user without a specific location can not see the view action of the potential payment
>        [Screencast from 2024-11-22 09-52-41.webm](https://github.com/user-attachments/assets/29b53fd8-3b13-4a22-8481-06d3517fed09)
> 
>     2. The user with a specific location can not see the view action of the potential payment related to its location
>        [Screencast from 2024-11-22 09-54-10.webm](https://github.com/user-attachments/assets/96855246-7d6b-4300-a1db-404e823a18e9)
>        But for the paymentlots it works as specified in the PR.
>        Maybe I don't understand well the feature,if so share some videos on how to test it. thank you

That looks like a bug, well spotted

2024-11-28 12:24 UTC, hakifran requested changes

2024-11-28 12:24 UTC, hakifran commented on iaso/api/payments/serializers.py
> +        user_org_units = sorted(list(user.iaso_profile.org_units.all().values_list("id")))
I think that instead of accessing org units linked directly to the user, it should be the hierarchy of the org units

2024-11-29 09:09 UTC, quang-le commented on iaso/api/payments/serializers.py
> +        user_org_units = sorted(list(user.iaso_profile.get_hierarchy_for_user().values_list("id"), flat=True))
```suggestion
        user_org_units = sorted(list(user.iaso_profile.get_hierarchy_for_user().values_list("id", flat=True)))
```

2024-11-29 09:48 UTC, hakifran requested changes

2024-11-29 09:48 UTC, hakifran commented on iaso/api/payments/serializers.py
> +        return user_org_units == change_requests_org_units_for_lot
user_org_units is a list while the change_requests_org_units_for_lot is a list of tuples. Which I think can not be compared directly without to flatten the list of tuples.
`return set([item[0] for item in change_requests_org_units_for_lot]).issubset(user_org_units)`

2024-11-29 09:48 UTC, hakifran commented on iaso/api/payments/serializers.py
> +        user_org_units = sorted(list(user.iaso_profile.get_hierarchy_for_user().values_list("id"), flat=True))
@quang-le there is an error on this : `File "/opt/app/iaso/api/payments/serializers.py", line 111, in get_can_see_change_requests
user_org_units = sorted(list(user.iaso_profile.get_hierarchy_for_user().values_list("id"), flat=True))
TypeError: list() takes no keyword arguments`

2024-11-29 09:48 UTC, hakifran commented on iaso/api/payments/serializers.py
> +        return user_org_units == change_requests_org_units_for_lot
user_org_units = set(user.iaso_profile.get_hierarchy_for_user().values_list("id", flat=True))
        change_requests_org_units_for_lot = (
            OrgUnitChangeRequest.objects.filter(payment__in=obj.payments.all())
            .values_list("org_unit__id", flat=True)
            .distinct()
        )
        return set(change_requests_org_units_for_lot).issubset(user_org_units)
```suggestion
        user_org_units = sorted(list(user.iaso_profile.get_hierarchy_for_user().values_list("id", flat=True)))
        change_requests_org_units_for_lot = sorted(
            list(OrgUnitChangeRequest.objects.filter(payment__in=obj.payments.all()).values_list("org_unit__id"))
        )
        return user_org_units == change_requests_org_units_for_lot
```

2024-11-29 09:52 UTC, hakifran requested changes

2024-11-29 09:52 UTC, hakifran commented on iaso/api/payments/serializers.py
> +        return user_org_units == change_requests_org_units_for_lot
```suggestion
        user_org_units = set(user.iaso_profile.get_hierarchy_for_user().values_list("id", flat=True))
        change_requests_org_units_for_lot = (
            OrgUnitChangeRequest.objects.filter(payment__in=obj.payments.all())
            .values_list("org_unit__id", flat=True)
            .distinct()
        )
        return set(change_requests_org_units_for_lot).issubset(user_org_units)
```

2024-11-30 11:09 UTC, hakifran approved these changes

2024-12-02 09:08 UTC, merged