WC2-431: Decipher how to aggregate ETL based on current tableau
BLSQ/iaso pull request #1833
Opened 2024-11-27 12:51 UTC by butofleury

What problem is this PR solving? Explain here in one sentence.

Related JIRA tickets : [WC2-431](https://bluesquare.atlassian.net/browse/WC2-431)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Aggregated data by period(month and year) and org unit.

## How to test

From the local instance with wfp coda database, run ETL script to generate data for:
- South Sudan: `docker compose run iaso manage etl_ssd `
- Nigeria: `docker compose run iaso manage etl_ng`

Then login on django admin and check on [Monthly statistics table](http://localhost:8081/admin/wfp/monthlystatistics/). You should see data aggregated by period and org unit. You can also filter the data per account(country).

## Print screen / video

[Administration-de-Wfp-Iaso.webm](https://github.com/user-attachments/assets/cd50e1a7-867b-481e-9464-c40e447cfcbe)

## Follow the Conventional Commits specification

The **merge message** of a pull request must follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

This convention helps to automatically generate release notes.

Use lowercase for consistency.

[Example](https://github.com/BLSQ/iaso/commit/8b8d7d3064138c1e57878f17b4eb922516ab0112):

```
fix: empty instance pop up

Refs: IA-3665
```

Note that the Jira reference is preceded by a _line break_.

Both the line break and the Jira reference are entered in the _Add an optional extended description…_ field.

2024-12-03 15:02 UTC, bramj requested changes
Tested locally and working. However, I think variable naming could be better to improve the overall code readability. As well as (but more difficult) avoiding function side-effects.

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/aggregate_journeys.py
> +class AGGREGATE_JOURNEY:
Is there a reason why this is not CamelCase?

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/common.py
> +    def journey_with_visit_and_steps_per_visit(self, account, program):
`programme`?

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/common.py
> +        aggregated_journey = []
Some variable names are pretty confusing. I think this would be better called `aggregated_journeys` to better reflect it's a list, what do you think?

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/common.py
> +        for org_unit, journey in data_by_journey:
`journeys`

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/common.py
> +            visit_by_period = groupby(journey, key=itemgetter("period"))
`visits_by_period`

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/common.py
> +            aggregated_journey = AGGREGATE_JOURNEY().group_by_period(
`aggregated_journeys`

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/models.py
> +    given_quantity_csb = models.FloatField(null=True, blank=True)
Is there a reason these 3 quantity fields are floats? Intuitively I would think an integer makes more sense?

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/aggregate_journeys.py
> +    def group_by_period(self, visit_by_period, org_unit, all_journey, assistance):
`visits_by_period`, `all_journeys`

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/common.py
> +    def save_monthly_journey(self, journey, account):
This feels like `journey` is an instance of `Journey`, but in reality it is a dict representing 1 monthly statistic. Maybe the naming can be improved?

2024-12-03 15:02 UTC, bramj commented on plugins/wfp/aggregate_journeys.py
> +        return all_journey
The code seems is working, but I find it pretty hard to follow to be honest. I think the main reason is that there are certain variables like `assistance` and `row` that are changed in place, and other methods that depend on these changes. I'm not sure if that's fixable, but I think we should avoid manipulating objects in place, and instead have functions return copies. We should strive for functions without side-effects, which makes the code easier to understand.

2024-12-04 07:45 UTC, butofleury commented on plugins/wfp/models.py
> +    given_quantity_csb = models.FloatField(null=True, blank=True)
> Is there a reason these 3 quantity fields are floats? Intuitively I would think an integer makes more sense?

 @bramj  there is some given assistance with float values in given quantity. 

![image](https://github.com/user-attachments/assets/a22a9b74-b500-49be-ac4e-3031c930916a)

2024-12-05 12:33 UTC, bramj approved these changes
LGTM :+1:

2024-12-06 07:56 UTC, merged