[IA-3782] Bulk push of GPS from submissions to OUs - backend
BLSQ/iaso pull request #1871
Opened 2024-12-13 18:07 UTC by tdethier

Bulk push of GPS from submissions to OUs - backend

Related JIRA tickets : IA-3782

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc

Tell us where the doc can be found (docs folder, wiki, in the code...).

## Changes

Explain the changes that were made.

The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:

- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.

If a specific config is required explain it here: dataset, account, profile, etc.

## Print screen / video

Upload here print screens or videos showing the changes.

## Notes

Things that the reviewers should know:

- known bugs that are out of the scope of the PR
- other trade-offs that were made
- does the PR depends on a PR in [bluesquare-components](https://github.com/BLSQ/bluesquare-components)?
- should the PR be merged into another PR?

## Follow the Conventional Commits specification

The **merge message** of a pull request must follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

This convention helps to automatically generate release notes.

Use lowercase for consistency.

[Example](https://github.com/BLSQ/iaso/commit/8b8d7d3064138c1e57878f17b4eb922516ab0112):

```
fix: empty instance pop up

Refs: IA-3665
```

Note that the Jira reference is preceded by a _line break_.

Both the line break and the Jira reference are entered in the _Add an optional extended description…_ field.

2025-01-07 10:19 UTC, kemar requested changes
Do you think that you could use a serializer instead of parsing the querystring?

2025-01-07 10:19 UTC, kemar commented on iaso/api/org_units.py
> +class HasCreateOrgUnitPermission(permissions.BasePermission):
Nice catch 😉

2025-01-07 10:19 UTC, kemar commented on iaso/utils/models/common.py
> +        org_unit = instance.org_unit
Since `instance.org_unit` is a nullable field, should we check that it really exists to avoid a potential error when accessing `org_unit.id` below?

2025-01-07 10:19 UTC, kemar commented on iaso/utils/models/common.py
> +            set_org_units_ids.add(org_unit.id)
This looks superfluous to me?

```suggestion
```

2025-01-07 10:19 UTC, kemar commented on iaso/api/instances.py
> +        select_all, selected_ids, unselected_ids = self._parse_check_bulk_gps_push_parameters(request.GET)
You should probably use a serializer instead of manually parsing the querystring?

2025-01-07 10:19 UTC, kemar commented on iaso/api/instances.py
> +            get_object_or_404(instances_query, pk=unselected_id)
This will trigger one SQL query per iteration of each loop. And this can increase rapidly depending on the number of `selected_id` and `unselected_id`.

I think we can do something more performant with only two queries:

```python
if instances_query.filter(pk__in= selected_ids).count() != len(selected_id):
    raise Http404
if instances_query.filter(pk__in=unselected_id).count() != len(unselected_id):
    raise Http404
```

2025-01-07 10:19 UTC, kemar commented on iaso/api/tasks/create/instance_bulk_gps_push.py
> +        raw_select_all = request.data.get("select_all", True)
I must insist that a serializer would make the API contract clearer and easier to understand.

2025-01-07 10:19 UTC, kemar commented on iaso/tasks/instance_bulk_gps_push.py
> +    with transaction.atomic():
Nice!
Note to myself: don't forget `atomic`.

2025-01-07 10:19 UTC, kemar commented on iaso/utils/models/common.py
> +def check_instance_bulk_gps_push(queryset: QuerySet) -> (bool, Dict[str, List[int]], Dict[str, List[int]]):
I think I'd have put that in the `validate()` method of a serializer.
It's kinda strange to find a sole validation function in a `models` file.

2025-01-07 11:02 UTC, tdethier commented on iaso/utils/models/common.py
> +        org_unit = instance.org_unit
Good question. I considered that it shouldn't be an issue, but I'll relay your question

2025-01-09 09:53 UTC, tdethier commented on iaso/utils/models/common.py
> +        org_unit = instance.org_unit
So, it seems that we'll cover this potential issue in a v2

2025-01-09 09:57 UTC, kemar approved these changes

2025-01-09 10:04 UTC, merged