IA-3685_IA-811: Allow filtering groups by project and by source and version
BLSQ/iaso pull request #1884
Opened 2024-12-19 10:16 UTC by butofleury

Related JIRA tickets : [IA-3685](https://bluesquare.atlassian.net/browse/IA-3685), [IA-811](https://bluesquare.atlassian.net/browse/IA-811)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Doc

N/A

## Changes

Added filters for project, data source and source version on groups page.

## How to test

From setuper folder, launch `python3 setuper.py --additional_projects` to create data and login with the created account.
Then check the groups page: http://localhost:8081/dashboard/orgunits/configuration/groups/.
Try to apply filters(Projects, Data Sources and Source version).

## Print screen / video

[Filter_by_Project_source_version.webm](https://github.com/user-attachments/assets/e37a7d84-d9e5-4331-ad4a-de2d4d4e1fdc)

## Notes

Things that the reviewers should know:

- known bugs that are out of the scope of the PR
- other trade-offs that were made
- does the PR depends on a PR in [bluesquare-components](https://github.com/BLSQ/bluesquare-components)?
- should the PR be merged into another PR?

## Follow the Conventional Commits specification

The **merge message** of a pull request must follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

This convention helps to automatically generate release notes.

Use lowercase for consistency.

[Example](https://github.com/BLSQ/iaso/commit/8b8d7d3064138c1e57878f17b4eb922516ab0112):

```
fix: empty instance pop up

Refs: IA-3665
```

Note that the Jira reference is preceded by a _line break_.

Both the line break and the Jira reference are entered in the _Add an optional extended description…_ field.

2025-01-10 12:24 UTC, hakifran requested changes
@butofleury could you check you eslint configuration

2025-01-20 12:47 UTC, hakifran requested changes
@butofleury the filters not working properly as expected.

2025-01-23 12:58 UTC, hakifran requested changes
Still not working as expected
[Screencast from 2025-01-23 14-48-25.webm](https://github.com/user-attachments/assets/ec6873d8-bc77-4afa-b973-f50d7d8fd455)

2025-02-07 08:38 UTC, hakifran requested changes

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +const dataSourceByProjectId = (dataSources: any[], projectId: string) => {
I think dataSource has already a defined type here: https://github.com/BLSQ/iaso/blob/495985c6337b15f11e63ee1645ccdef1b97806eb/hat/assets/js/apps/Iaso/domains/orgUnits/types/dataSources.ts#L40

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +    const allDataSource: any[] = dataSources?.map(
Same here you can define the type based on the returned object in the map, instead of any type.

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +        (source: { projects: any[][]; name: any; id: any }) => {
Avoid defining the type inside the code, it make the code hard to read.

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +                (project: { id: string }) => project?.id.toString(),
Same here `Avoid defining the type inside the code`

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +            const projectIds = source?.projects[0].map(
I think you can use flat() to flatten the projects array as it can contain multiple arrays.

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +const dataSourceByProjectId = (dataSources: any[], projectId: string) => {
The name of the method should be changed for example: filterDataSourcesByProjectId. And I think it can be simplified like this proposition: 
`const dataSourceByProjectId = (dataSources: any[], projectId: string) => {
    const allDataSource = dataSources?.map(({ projects, name, id }) => {
        return {
            label: name,
            value: `${id}`,
            projectIds: projects?.flat().map(project => project.id.toString()),
        };
    });
    return projectId
        ? allDataSource?.filter(({ projectIds }) =>
              projectIds?.includes(projectId),
          )
        : allDataSource;
};`

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +const versionsBySource = (sourceVersions: any[], source: string) => {
The sourcVersion has also predefined type.

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +const versionsBySource = (sourceVersions: any[], source: string) => {
This method can also be simplified.`const versionsBySource = (sourceVersions: any[], source: string) =>
    sourceVersions
        ?.filter(version => version?.data_source.toString() === source)
        ?.map(version => ({
            label: `${version?.data_source_name}-${version?.number}`,
            value: `${version?.id}`,
        }));`

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +                    value={projectIds}
I think this projectIds should be renamed into projectId because the select component isn't multi-select.

2025-02-07 08:38 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/hooks/requests.js
> +        if (params.version) {
On my humble opinion there is not need of nesting the if(params.version) inside params.dataSource check

2025-02-10 15:30 UTC, butofleury commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +const dataSourceByProjectId = (dataSources: any[], projectId: string) => {
To keep the code more readable, I wanted to avoid ternary condition which make the code difficult to read on this case!

2025-02-11 07:27 UTC, butofleury commented on hat/assets/js/apps/Iaso/domains/orgUnits/groups/components/Filters.tsx
> +const versionsBySource = (sourceVersions: any[], source: string) => {
IMO, chaining filter and map functions would make code hard to read.

2025-02-11 11:48 UTC, hakifran approved these changes
LGTM

2025-02-11 11:53 UTC, merged