IA-3433 Tasks view: Add extra filters on type, status and username (launcher)
BLSQ/iaso pull request #1889
Opened 2024-12-20 13:12 UTC by bramj

This PR improves the tasks. Specifically, it:
- Adds a new column `created_by` on the Task model to differentiate between who did the initial launch, and who did a potential re-launch. 
- Adds the following filters to the tasks page:
  - type (the task's "name")
  - status
  - user (both creator as well as last launcher are take into consideration)
  - start and end date (of any of the timestamps `created_at`, `started_at` and `ended_at`
- General refactoring:
  - File structure of Tasks api endpoint, extracted `filters.py` and`serializers.py`
  - DRY up some Django API filtering code
  - Typescriptify some JS
- Add test for Tasks API filtering

### Screenshot

![image](https://github.com/user-attachments/assets/fb8b3e40-2aab-4acb-a119-681623d88ce6)

2025-01-08 14:28 UTC, kemar requested changes
Good job.

I'd say that you can safely remove 2 redundant indexes and add a relation in the `select_related` method.

The rest is optional.

2025-01-08 14:28 UTC, kemar commented on iaso/api/deduplication/filters.py
> +                queryset = queryset.filter(analyze__created_at__gte=date_string_to_start_of_day(start_date))
We may be able to use a string and only filter on the `date` part of the `datetime` field.

E.g. (assuming the date format is correct):

```python
queryset.filter(analyze__created_at__date__gte="2021-05-23")

queryset.filter(analyze__created_at__date__lte="2021-05-23")
```

This may be easier to read and may save some code.

2025-01-08 14:28 UTC, kemar commented on iaso/models/base.py
> +            models.Index(fields=["account"]),
```suggestion
```

This is not necessary because a database index is [automatically created](https://docs.djangoproject.com/en/5.1/ref/models/fields/#foreignkey) on the `ForeignKey` (unless `db_index=False` is set).

2025-01-08 14:28 UTC, kemar commented on iaso/models/base.py
> +            models.Index(fields=["created_by"]),
```suggestion
```

Same thing as above.

2025-01-08 14:28 UTC, kemar commented on beanstalk_worker/__init__.py
>                  task.launcher = user
What I understand is that we assume that the creator and the launcher are always the same person. Is this correct?

2025-01-08 14:28 UTC, kemar commented on iaso/tests/api/test_tasks.py
> +    maxDiff = None
TBH I'm always tempted to put that in the base class…

2025-01-08 14:28 UTC, kemar commented on iaso/api/tasks/views.py
> +        return Task.objects.select_related("created_by", "launcher").filter(account=profile.account)
We could add `user__iaso_profile` because it's used in `ordering_fields`.

```suggestion
        return Task.objects.select_related("created_by", "launcher", "user__iaso_profile").filter(account=profile.account)
```

2025-01-08 14:28 UTC, kemar commented on iaso/api/tasks/views.py
> +    ]
Just for you information (no need to rewrite that) I like to do that via [django-filter](https://django-filter.readthedocs.io/en/latest/guide/rest_framework.html).

It has built-in validation and you don't need a bunch of different classes.

You have [various examples](https://github.com/BLSQ/iaso/blob/5c7e90d95dd93f6cfc1b0f8e4414a3916a552800/plugins/polio/api/chronogram/filters.py#L47) in the code base.

2025-01-08 14:28 UTC, kemar commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.tasks.last_launch_by": "Dernière execution :",
Excuse my French 😄 

```suggestion
    "iaso.tasks.last_launch_by": "Dernière exécution :",
```

2025-01-13 09:43 UTC, bramj commented on iaso/api/deduplication/filters.py
> +                queryset = queryset.filter(analyze__created_at__gte=date_string_to_start_of_day(start_date))
I like the simplicity, but would that take correctly into account the timezone? :thinking:

2025-01-13 09:44 UTC, bramj commented on iaso/models/base.py
> +            models.Index(fields=["account"]),
Good point, thanks!

2025-01-13 09:47 UTC, bramj commented on beanstalk_worker/__init__.py
>                  task.launcher = user
This is when the task is being created, so here indeed the creator and launcher will be the same person.

It's because of the "relaunch" functionality that I added the creator. When relaunching, only the launcher is updated (see https://github.com/BLSQ/iaso/blob/main/iaso/api/tasks/__init__.py#L135)

2025-01-13 09:48 UTC, bramj commented on iaso/tests/api/test_tasks.py
> +    maxDiff = None
Agreed, I'll do it

2025-01-13 10:00 UTC, bramj commented on iaso/api/tasks/views.py
> +    ]
Oh I like that, thanks! TIL

2025-01-13 13:48 UTC, kemar commented on iaso/api/deduplication/filters.py
> +                queryset = queryset.filter(analyze__created_at__gte=date_string_to_start_of_day(start_date))
Correct me if I'm wrong but it seems that the incoming format of `request.query_params.get("start_date")` is a date string (i.e. `"%d-%m-%Y"`) without a clearly defined TZ nor any time information.

If that's the case, you'll never be able to get an accurate "TZ aware" date or datetime.

You may as well rely on `__date__`.

2025-01-14 09:13 UTC, kemar approved these changes
LGTM

2025-01-14 10:56 UTC, bramj commented on iaso/api/deduplication/filters.py
> +                queryset = queryset.filter(analyze__created_at__gte=date_string_to_start_of_day(start_date))
@kemar You're right, actually ideally the user should have a timezone on their profile, and then we could use that one to generate the "start of day". If we do it correctly, the current code would be easier to refactor I think. Since it's working as is, okay for you to merge like this?

2025-01-14 11:00 UTC, kemar commented on iaso/api/deduplication/filters.py
> +                queryset = queryset.filter(analyze__created_at__gte=date_string_to_start_of_day(start_date))
@bramj yup OK

2025-01-14 11:02 UTC, merged