IA-610 edit shapes
BLSQ/iaso pull request #225
Opened 2021-06-22 12:20 UTC by beygorghor

- restore old code
- refactor totally the shape edition
- support multi polygons
- remove unused code
- plug edit catchment and location to features flags

=> no frontend test for now

<img width="1678" alt="Screenshot 2021-06-22 at 13 53 00" src="https://user-images.githubusercontent.com/12494624/122923270-d2195d00-d364-11eb-9488-81f17473d151.png">
![Uploading Screenshot 2021-06-22 at 13.55.14.png…]()

2021-06-22 14:12 UTC, quang-le commented
I would hide the "Catchment" title, or mention that it is also disabled:

![Screenshot 2021-06-22 at 16 10 58](https://user-images.githubusercontent.com/38907762/122940111-7951c080-d374-11eb-999d-5b65c66ecbe5.png)

2021-06-22 14:32 UTC, quang-le commented
The text on hover says "click cancel" but the cancel button only becomes active after the user clicks "STOP EDIT"

![Screenshot 2021-06-22 at 16 30 52](https://user-images.githubusercontent.com/38907762/122943379-42c97500-d377-11eb-9403-7a579c2a58ed.png)

2021-06-22 14:36 UTC, quang-le commented
"Click to keep drawing" confused me at first: I tried to draw a shape with the mouse button down. Maybe "click to add a point" or something in that vein would be clearer

![Screenshot 2021-06-22 at 16 30 52](https://user-images.githubusercontent.com/38907762/122943764-950a9600-d377-11eb-88c7-f4456fbcdae4.png)

2021-06-23 10:54 UTC, quang-le reviewed
Mostly nitpicking

2021-06-23 10:54 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/EditableGoup.js
> +
I would move the value assignments in `initialize`. I think it would make `initialize` more readable, and most values are not used by `createPane` anyway

2021-06-23 10:54 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/EditableGoup.js
> +
The logic of `toggleEditShape` and `toggleDeleteShape` could be abstracted although it might be overkill for such little methods. If not abstracting, I would suggest moving the `pane.style.zIndex` values (500 and 400) into (static) properties

2021-06-23 10:54 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/fitToBounds.js
> +        ot.orgUnits.shapes.forEach(o => {
Nitpick: I prefer expressive names like "orgUnit" over "ot"

2021-06-23 10:54 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/EditOrgUnitOptionComponent.js
>          const {
Why not a functional component since we don't use any life-cycle method?

2021-06-23 13:40 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.map.shape.editCathcmentDisabled": "Catchment edition is disabled on this account",
editCathcmentDisabled

2021-06-23 13:44 UTC, olethanh commented
Can we just remove or disable the table if both feature are disabled?

2021-06-23 13:48 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/EditOrgUnitOptionComponent.js
> +// we invest the time required to implement multi-polygon editing.
is that comment still true?

2021-06-23 14:28 UTC, olethanh requested changes
* The buttons don't get disabled when creating a new shape. And when you click on them you are now in a weird state
* There is no way to cancel adding a shape when you are in the middle of it
* In edition: we can remove a  node by double clicking on it but I haven't found how to add a new one
* we should probably add a warning that the change are not saved if we leave the page in the middle of an edition
* Minor but we can have children which have the same color as the catchment and it's kind of confusing
* Button for catchment are not in the same order
![image](https://user-images.githubusercontent.com/82500/123111465-3a3b7200-d43d-11eb-87c1-4d9db895c4fe.png)

* A migration is missing to add the catchment editing permission
* Not sure if there is any reason to have the altitude edition field disabled since the backend support it? would allow us to clean the code

2021-06-23 14:28 UTC, olethanh commented on hat/assets/js/apps/Iaso/utils/mapUtils.js
> +            // TODO replace unary with  j = i, i += 1
pas compris

2021-06-24 07:58 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/EditOrgUnitOptionComponent.js
> +// we invest the time required to implement multi-polygon editing.
removed

2021-06-24 07:58 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.map.shape.editCathcmentDisabled": "Catchment edition is disabled on this account",
thx

2021-06-24 09:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/utils/mapUtils.js
> +            // TODO replace unary with  j = i, i += 1
c'est une ancienne fonction que je voulais garder... j'ai enlevé plein de code legacy entretemps

2021-06-24 10:20 UTC, beygorghor commented
UPDATES:

- a single component for edit, delete, add shapes + refactor state
- "add enabled" state (possibility to cancel while adding)
- altitude can now be edited and saved

2021-06-24 12:57 UTC, olethanh approved these changes

2021-06-24 14:17 UTC, quang-le approved these changes

2021-06-24 14:22 UTC, merged