IA-1669: Edit org unit: filter groups for ou source
BLSQ/iaso pull request #229
Opened 2022-12-05 11:49 UTC by beygorghor

In org unit details: When showing an org unit from a given source, proposed groups should be from the same source

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes
Use current org unit source id to filter groups while editing an org unit.

## How to test

Edit an org unit and check that the list of groups are exclusively from the same source as the org unit.

2022-12-06 14:34 UTC, codeKameleon approved these changes

2022-12-07 11:44 UTC, quang-le requested changes
just a small edge case

2022-12-07 11:44 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/hooks.js
> +                            : `?&dataSource=${originalOrgUnit?.source_id}`
if source_id is null or undefined you might send an incorrect query

2022-12-07 12:57 UTC, quang-le approved these changes

2022-12-07 12:57 UTC, merged