IA-1678: submissions - org units filter state
BLSQ/iaso pull request #232
Opened 2022-12-06 11:01 UTC by beygorghor

Repro

Go to forms list

click “view submissions” for a form

Open the side menu

Click “Submissions”

Expected:

Either: Both the filter selection and the table results are preserved

Or: Both the filter selection and the table results are cleared/ reset

Actual

The filter selection is preserved but the table results are updated (diplaying results of an empty search)

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

- `useSkipEffectOnMount` to watch params and sync filter states with it
- ensure fetching data is not done on org units id isSearchActive not set in the params
- fix a a small issue with forms without possible fields, cols were empty

## How to test

Go to submissions and org units pages, perform seraches and click back the same page in the sidebar

## Print screen / video

https://user-images.githubusercontent.com/12494624/205893782-17ff0559-ddc0-4ecb-92f0-76214050fa6d.mov

https://user-images.githubusercontent.com/12494624/205893883-388e1a1a-4397-4499-b3a6-e3212308d884.mov

2022-12-06 15:22 UTC, codeKameleon approved these changes

2022-12-12 11:50 UTC, quang-le requested changes
The org unit filter doesn't reset in submissions though the results do):

https://user-images.githubusercontent.com/38907762/207038078-7a385f66-10fa-425d-9b88-1a4079d01a29.mov

2022-12-12 11:50 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +    }, [defaultFilters]);
formState is missing from the deps

2022-12-12 11:50 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitFiltersContainer.tsx
> +    }, [params.searches]);
searches is missing from the deps

2022-12-12 12:30 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitFiltersContainer.tsx
> +    }, [params.searches]);
this will lead to an infinite loop

2022-12-12 12:31 UTC, beygorghor commented
> The org unit filter doesn't reset in submissions though the results do):
> 
>  Screen.Recording.2022-12-12.at.12.49.01.mov

We had the same issue on org unit selection in org unit lists, this is fixed now

2022-12-12 13:56 UTC, quang-le approved these changes

2022-12-12 13:57 UTC, merged