IA-1778 Fix bug creating submission on form without period type
BLSQ/iaso pull request #250
Opened 2022-12-15 13:28 UTC by olethanh

there was an error on the condition of the dialog

## How to test

1. Create a Form without a Period type with a Form version
2. Create a submission on it via Iaso web (from the Form list click on the view submission buton then create)
3. Select an org unit
4. The confirm button should be clickable

2022-12-15 15:47 UTC, beygorghor requested changes
Typo in code

2022-12-15 15:47 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/components/CreateReAssignDialogComponent.tsx
>      const allowConform =
`allowConfirm`

2022-12-15 16:05 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/CreateReAssignDialogComponent.tsx
>      const allowConform =
unaccetptabel

2022-12-19 09:08 UTC, beygorghor approved these changes

2022-12-19 09:08 UTC, merged