[IA-456] org units tree view
BLSQ/iaso pull request #256
Opened 2021-07-02 11:39 UTC by geoffreydhuyvetters

## Added

- Tree view component for org units

2021-07-23 15:39 UTC, olethanh commented
converting it back to draft, as I have fix to do in the API before merging and don't want it merged by mistake

2021-08-02 10:43 UTC, olethanh requested changes

2021-08-09 06:22 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +    tooltip(orgUnit, icon) {
we don't seem to be using it?

2021-08-09 15:19 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/requests.js
> +    const useableData = response.orgunits.map(orgUnit => {
That was the data I actually used. Granted, the name was made moot when I put the whole orgUnit in `data`

2021-08-10 11:36 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +    tooltip(orgUnit, icon) {
indeed, it seems to be a leftover

2021-08-10 14:22 UTC, quang-le commented
## Updates 10/08/2021

- removed `OrgUnitLevelFilterComponent`and `OrgUnitsLevelsFiltersComponent`
- replaced them with `OrgUnitTreeViewModal` in `OrgUnitFiltersComponent` and `OrgUnitInfosComponent`
- updated `requests.js` and `OrgUnitTreeViewModal` to enable changing the source

2021-08-11 14:03 UTC, quang-le commented
## Updates 11/08/2021

- Add styling: resize Input box to match other fields in OrgUnits list, correctly align `TruncatedTreeview`, change box color on hover, align box with siblings
- Change "clear" Icon
- Clear OrgUnit selection when changing source
- Restore deep linking in OrgUnit List
- Update deps to bluesquare-components and node-sass



https://user-images.githubusercontent.com/38907762/129043156-23cee63c-3b36-4bc5-945a-e2b81d96387a.mov

2021-08-12 12:51 UTC, beygorghor commented
We need to add `ignoreEmptyNames` tu api calls to avoid weird results
<img width="1255" alt="Screenshot 2021-08-12 at 14 43 29" src="https://user-images.githubusercontent.com/12494624/129199696-971bfa74-7174-42eb-bed5-14bc69192aaf.png">
Selected org unit is not visible in the tree.
Also maybe put a max height to the dialog in order to avoid this double scroll

2021-08-13 09:04 UTC, beygorghor requested changes
Ok just change source while editing an org unit like we said

2021-08-13 09:04 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewPicker.js
> +        fontSize: '16px',
fyi you can only use fontSize: 16

2021-08-13 10:04 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +    // FIXME: Olivier check after merge
yep

2021-08-13 13:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewPicker.js
> +        fontSize: '16px',
Old habits die hard 🙂

2021-08-13 13:08 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/TreeView/OrgUnitTreeviewModal.js
> +const tooltip = (orgUnit, icon) => (
Done already

2021-08-16 10:34 UTC, quang-le commented
## Update 16/08/2021
- Added Treeview in `OrgUnitInfosComponent`
- Updated messages and added translations
- Made placeholder configurable for `TreeviewPicker`


https://user-images.githubusercontent.com/38907762/129550621-145c3622-23c4-47a9-9d1c-62d721a75529.mov

2021-08-17 10:16 UTC, beygorghor approved these changes

2021-08-17 10:34 UTC, merged