IA-1645 Add checkbox to filter users by ou children or parent
BLSQ/iaso pull request #258
Opened 2022-12-20 12:25 UTC by SimonDus

On the profile API add of 2 checkboxes to filter users by Ou parent or children

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are there enough tests

## How to test

Create users with OU set on their profiles. 
Set OU Parent/Children on users and play with the filters. 
Selection an ou to do the search is required...

## Print screen / video

![image](https://user-images.githubusercontent.com/45785235/208666679-35a1462b-58ec-4c0a-886d-a61d5fed8353.png)

2022-12-22 15:40 UTC, quang-le requested changes
- `ouChildren` is missing from the filter state, so it won't work when deep linking
- The checkboxes shouldn't be mutually exclusive

2022-12-22 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/Filters.js
> +        ouParent: params.ouParent,
shouldn't there be ouChildren here as well?

2022-12-22 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/messages.js
> +        defaultMessage: 'Show OU Children',
Show org unit children

2022-12-22 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/messages.js
> +        defaultMessage: 'Show OU parent',
Show org unit parent

2022-12-22 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/Filters.js
> +                        // onEnterPressed={handleSearchPerms}
can be deleted

2022-12-22 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/Filters.js
> +                        // onEnterPressed={handleSearchPerms}
can be deleted

2022-12-22 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/Filters.js
> +
Can you move this to /iaso/hat/assets/apps/Iaso/utils/dataManipulation.ts?

2022-12-23 08:26 UTC, quang-le requested changes
Thanks for the changes.

Is this the expected behaviour?

https://user-images.githubusercontent.com/38907762/209299964-f4689359-9ff8-44c7-a086-e8af23eee5f9.mov

Also:
-  The localisation (org unit) filter shouldn't push the checkboxes down when we select an org unit far down the tree
- We have (new) layout guidelines about filters. They shouldn't take the whole width of the screen. See for example Completeness stats:
![Screenshot 2022-12-23 at 09 24 42](https://user-images.githubusercontent.com/38907762/209300407-6203438d-0641-438c-999c-049f22c2082f.png)
My take in this case is that we should have 3 filters in one row, and org units with the 2 checkboxes on another. @beygorghor  can you weight on this please?

2022-12-23 11:53 UTC, quang-le approved these changes
Nice job!

2022-12-27 18:30 UTC, codeKameleon approved these changes

2023-01-02 15:33 UTC, beygorghor approved these changes

2023-01-04 09:41 UTC, beygorghor commented
I agree with @olethanh, for me it's not clear what those checkboxes are doing, maybe adding a info icon with a tooltip giving more infos can be a good idea

2023-01-09 13:58 UTC, merged