IA-671: ignore source if empty, add api params to ignore empty names
BLSQ/iaso pull request #265
Opened 2021-07-06 10:59 UTC by beygorghor

2021-07-06 12:34 UTC, quang-le approved these changes
Front-end looks fine to me

2021-07-07 13:24 UTC, olethanh requested changes
We should probably forbid empty name in the futur but that's probably a good fix in the mean time

2021-07-07 13:24 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/orgUnits/utils.js
> +                    : ''
it's like an  escape in an escape in a escape. I've got a feeling there is probably a more readable way to write this?

2021-07-07 13:24 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/orgUnits/utils.js
> +                    : ''
maybe something like
```
orgUnit.name \
   + orgunit.source ? ` - source: ${orgUnit.source}` : '' \
   + orgUnit.org_unit_type_name && withType?  ` (${orgUnit.org_unit_type_name})` : ''
```

2021-07-12 09:38 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/utils.js
>      let message = textPlaceholder;
name should be orgunitMessage, since it's not a class

2021-07-12 13:08 UTC, merged