IA-611 Correctly zoom on all the shape
BLSQ/iaso pull request #282
Opened 2021-07-22 15:46 UTC by olethanh

not the most efficient because we re convert the geojson in shape but should do for now

2021-07-22 19:01 UTC, quang-le requested changes
replace import of leaflet in `MapComponent.jsx` to import only the needed method, `geoJSON`

2021-07-23 07:27 UTC, olethanh commented on plugins/polio/js/src/components/MapComponent/MapComponent.jsx
> +import * as L from "leaflet";
I'm just in the habit of using L for leaflet and letting my IDE handle the importing. Corrected

2021-07-23 07:35 UTC, quang-le approved these changes

2021-07-23 07:35 UTC, olethanh commented
re corrected forgot to commit the second place :D

2021-07-23 07:42 UTC, merged