Remove preparedness or surge data if the user removes the url
BLSQ/iaso pull request #290
Opened 2021-07-26 17:10 UTC by xavierbarbosa

### Fix
- Not being able to remove cached data, after removing the preparedness URL or surge data

2021-07-26 19:56 UTC, kaiobrito commented on plugins/polio/serializers.py
> +                instance.last_preparedness().delete()
This will delete only the last entry, not the history, is that correct?

2021-07-28 09:29 UTC, xavierbarbosa commented on plugins/polio/serializers.py
> +                instance.last_preparedness().delete()
Good question, but do we want to delete the entire history? Do we care about it? Maybe @olethanh you know?

2021-07-28 09:40 UTC, olethanh requested changes

2021-07-28 09:40 UTC, olethanh commented on plugins/polio/serializers.py
> +                instance.last_preparedness().delete()
From what I understand last_preparedness just return the last one, so if you delete it, next time it's called it will just return the previous one, which is probably not what the user would expect.

Not sure why we keep the history of preparedness but let's not allow it's deletion by error.

So all considered I would propose that we don't actually delete any data but modify last_preparedness and last_surge to only return something if the url is the same as the currently configured one on the Campaign

2021-07-30 18:00 UTC, xavierbarbosa commented on plugins/polio/serializers.py
> +                instance.last_preparedness().delete()
Changed it to work like @olethanh suggestion: https://github.com/BLSQ/iaso/pull/290/commits/3731a3f23b61e63408749786063b41fc2e9adeb2

2021-07-30 18:59 UTC, olethanh commented
thanks but it's not needed anymore to remove it from the DB then

2021-08-03 12:46 UTC, olethanh commented
closing replaced by #299

2021-08-03 12:46 UTC, closed without merging