Add support to create, update and delete pages
BLSQ/iaso pull request #296
Opened 2021-07-29 18:22 UTC by xavierbarbosa

### Added
- Support to create, update and delete pages

2021-07-30 15:29 UTC, xavierbarbosa commented on hat/assets/js/apps/Iaso/domains/pages/index.js
> +                            <Link to={`/pages/${settings.original.slug}`}>
@madewulf I added a view inside the react app which renders the dashboard inside an iframe, so we only need to add the link when creating the page. This way we keep the navigation consistent, see:

![image](https://user-images.githubusercontent.com/3688705/127675974-d70a4ad1-92f9-4642-a88b-03ea687587b2.png)

If you prefer the old approach we can change it back, but I do think this is nicer.

2021-08-05 21:50 UTC, beygorghor commented
Added:
- use feature flag for page activation
- change icon menu
- adapt modale size, padding and scroll
- page type : iframe / html /raw
- use a wysiwyg tool to allow editing html
- change link to django template 
-  adding needs_auth, users to CRUD
- change view.py to use different types
- remove view page
-  split codeinto components
<img width="1657" alt="Screenshot 2021-08-05 at 23 39 48" src="https://user-images.githubusercontent.com/12494624/128425759-e2985e89-c073-406a-ac02-7cf92a6e615b.png">
<img width="1032" alt="Screenshot 2021-08-05 at 23 38 09" src="https://user-images.githubusercontent.com/12494624/128425781-789290d5-6d99-4e30-b4fc-86a6745aecd0.png">
<img width="1033" alt="Screenshot 2021-08-05 at 23 40 03" src="https://user-images.githubusercontent.com/12494624/128425790-76de9155-f00e-4fe3-a61c-f7e5a0f12e75.png">
<img width="992" alt="Screenshot 2021-08-05 at 23 39 55" src="https://user-images.githubusercontent.com/12494624/128425792-5336be83-48c5-4b9e-9735-b204d0d75521.png">

2021-08-09 08:23 UTC, olethanh commented on hat/templates/iaso/pages/iframe.html
> +
maybe a title?

2021-08-09 14:56 UTC, quang-le requested changes
-  remove potential mutation in `CreateEditDialog` line 60.
-  remove potential null error in `index.js`  line 94
- other comments are more stylistic suggestions

Nice work, great feature!

2021-08-09 14:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/pages/components/CreateEditDialog.js
> +        savePage(tempValues, {
Line 61: there's a potential mutation of `values`. 
Suggested change: `tempValues.users = [...(values.users??[]), currentUser.user_id]`, in place of lines 61-63

2021-08-09 14:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/pages/components/CreateEditDialog.js
> +            selectedPage && selectedPage.needs_authentication === false
cf line 72

2021-08-09 14:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/pages/index.js
> +        removePage(selectedPage.slug, {
this will throw an error if selectedPage is undefined -> `selectedPage?.slug`

2021-08-09 15:43 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/pages/components/CreateEditDialog.js
> +        savePage(tempValues, {
not really important but shouldn't we check the currentUser is not already included before adding it?

2021-08-10 11:21 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/pages/components/CreateEditDialog.js
> +        savePage(tempValues, {
Without a currentUser, the page is not loaded

2021-08-11 07:27 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/dialogs/ConfirmDialogComponent.js
> +            >
otherwhise the dialog will close on any click... lika a focus on a input

2021-08-11 08:14 UTC, merged