IA-1812: parent disapear when an alias is added in orgunit creation
BLSQ/iaso pull request #305
Opened 2023-01-13 15:09 UTC by codeKameleon

adding an alias cleared the org unit treeview input 

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

- fixed handleChangeAlias function

## How to test

Go to Orgunits > Create 
Then  select a parent orgunit and try adding an alias
Adding an alias should not empty the parent orgunit treeview

## Print screen / video

[recording-2023-01-13-16-07-51.webm](https://user-images.githubusercontent.com/25134301/212352559-52635d01-4ab8-4e75-84ec-dfbadd0e9519.webm)

2023-01-16 09:47 UTC, beygorghor requested changes

2023-01-16 09:47 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitForm.js
> -                setOrgUnitModified(false);
This is not fixing the issue in fact, this is avoiding it. Can you have a look into `OrgUnitInfosComponent` please. The `reformatOrgUnit` method looks weird. It's using `orgunit.parent` but we only have a `orgunit.parent_id`

2023-02-13 09:17 UTC, beygorghor approved these changes

2023-02-13 09:17 UTC, beygorghor commented
Added cypress test on creation.
@cypress

2023-02-14 15:40 UTC, quang-le approved these changes
much cleaner that way. works on my machine

2023-02-14 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitInfos.tsx
> +};
Is it not a sub type of org unit?

2023-02-14 15:40 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitForm.tsx
> +const initialFormState = orgUnit => ({
no typing?

2023-02-15 11:40 UTC, merged