IA-1782: account id warning
BLSQ/iaso pull request #307
Opened 2023-01-16 12:35 UTC by beygorghor

Use account id that is now in the url to warn user logged into one account that he’s trying to access another account. 

Example: if you are logged into account with id 1 and that you access this url: http://localhost:8081/dashboard/settings/tasks/accountId/2 , you should see a popup telling you:

You are connected to the wrong account, would you like to log out and connect in the correct account to see this link?

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## Changes

Create a dialog allowing to logout if account id in the url is not the same as current user account id.

## How to test

Open the dashboard, change accountId in the url to something else, a dialog should appear

## Print screen / video

https://user-images.githubusercontent.com/12494624/212679529-1c1cd330-3659-4413-a576-1fd9ea123474.mov

2023-01-19 11:24 UTC, quang-le requested changes
it works when I mnually change the account, but when I paste a link with a different account id, the app makes the correction the account id of the current user:

https://user-images.githubusercontent.com/38907762/213430091-a74a5a58-4242-426a-acc6-25d698fe5685.mov

Changing this behaviour might increase the scope of the PR more than previously thought

2023-01-19 11:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.label.wrongAccount": "You are connected to the wrong account, would you like to log out and connect in the correct account to see this link?",
You are connected to the wrong account, would you like to log out and connect TO the correct account to see this link?

I wonder if "with" wouldn't be even better

2023-01-19 11:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.label.wrongAccount": "Vous êtes connecté au mauvais compte, voulez-vous vous déconnecter pour vous connecter avec le bon compte?",
Here as well do we connect to an account or with an account?

2023-01-19 11:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/ProtectedRoute.js
> +
I don't think you need to memoize booleans

2023-01-19 11:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/WrongAccountModal.tsx
> +const WrongAccountModal: FunctionComponent<Props> = ({ isOpen }) => {
Why not use/edit the modal from bluesquare-components?

2023-01-23 11:13 UTC, codeKameleon commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.label.wrongAccount": "Vous êtes connecté au mauvais compte, voulez-vous vous déconnecter pour vous connecter avec le bon compte?",
i would say "with" too

2023-01-23 11:38 UTC, codeKameleon requested changes
Mainly agree with Son for the changes. 
Just concerning this comment :https://github.com/BLSQ/iaso/pull/307#pullrequestreview-1261391099

I don't have the issue personnaly : 

[recording-2023-01-23-12-35-44.webm](https://user-images.githubusercontent.com/25134301/214030548-d7807e0f-220a-432c-919a-688b04ef9700.webm)

2023-01-23 14:41 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/WrongAccountModal.tsx
> +const WrongAccountModal: FunctionComponent<Props> = ({ isOpen }) => {
because it's impossible to hide the button

2023-01-23 14:43 UTC, beygorghor commented
@quang-le indeed i cannot reproduce it:

https://user-images.githubusercontent.com/12494624/214067897-06ee986e-4e18-4d6e-a25d-08485723d486.mov

on left = chrome with user account 1
on right = firefox with user account 3

2023-01-23 15:44 UTC, codeKameleon approved these changes

2023-01-23 15:51 UTC, quang-le approved these changes
I can't repro anymore either. Mystery bug...

2023-01-24 12:26 UTC, merged