Replace superagent by fetch in front
BLSQ/iaso pull request #328
Opened 2021-08-27 08:44 UTC by olethanh

don't remove superagent dependency yet because there are unused code that use it... And I removed that code in PR #326 

Added node-fetch as a dependency for testing.
Note that we had a bunch of code using Fetch already in Stephan's PBF code, and since it  was not present when testing it was either silently failing or not tested.

2021-08-30 08:29 UTC, beygorghor requested changes
You can now remove superagent.
Stephan's code is indeed not tested.
Did you test the upload of file and the multipart post ?

2021-08-30 10:22 UTC, olethanh commented
> You can now remove superagent.

done

> Stephan's code is indeed not tested.
> Did you test the upload of file and the multipart post ?

yes, I tested for the GPKG import, not sure where else it is used.

2021-08-30 17:00 UTC, olethanh commented
force pushed so I could beneficiate from my hot fix on  master. Checked and the file upload working correctly for FormVersion too

2021-09-01 09:06 UTC, beygorghor approved these changes

2021-09-01 09:06 UTC, merged