IA 768 label keys visual bugs
BLSQ/iaso pull request #362
Opened 2021-09-13 07:29 UTC by quang-le

## Changes
- use JSON.parse for labels that are valid jsons. If parsing fails, use the name as label instead
- Truncate long labels to avoid text overlap
- use Tooltip to display full label name on hover
- use `secondary` prop to display key underneath label in order to avoid ambiguity between labels with the same name

https://user-images.githubusercontent.com/38907762/133041873-0d16bf0e-3c72-45e2-a813-b9cece0a47ed.mov

2021-09-13 08:12 UTC, beygorghor requested changes

2021-09-13 08:12 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/tables/ColumnSelectDrawer/index.js
> +                                                        <Switch
- Maybe split this item into separate component
- also you can apply some offset top on the tooltip to pop just under the name and not under the key

2021-09-13 08:12 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/utils.js
> +        if (locale === 'fr') {
I think use a constant can be a good approach here:

`const locales = { fr: 'French', en: 'English`};`

Then in the future if we want to add a locale it's more easy...

2021-09-13 15:04 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/tables/ColumnSelectDrawer/index.js
> +                                                        <Switch
I moved the tooltip message to the left instead as it seemed more legible

2021-09-14 10:26 UTC, beygorghor approved these changes

2021-09-14 10:26 UTC, merged