IA-1916 entity mandatory field
BLSQ/iaso pull request #385
Opened 2023-02-16 11:30 UTC by quang-le

In entity types create/edit modal, the `List fields` and `Details info fields` need to be made mandatory to prevent bugs with the mobile app

Related JIRA tickets : IA-1916

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [X] Is my code clear enough and well documented
- [X] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## Changes

- Added validator for both fields
- Marked them as required
- Changed the default value in `intialState` fromm `[]` to `undefined` to enable the validation check
- Filtered out forms without XLS version to avoid users having no fields to choose from after having selected a reference form when creating an entity type
- Fixed `usePossibleFields` so it fetches the fields when user changes selection in UI
- Fixed Dialog so it would reset `onClose` to avoid keeping the values after a `Create`

## How to test

Go to Beneficiary Types
Create a Beneficiary: you shouldn't be able to save unless all fields have a value

## Print screen / video

https://user-images.githubusercontent.com/38907762/219353290-04a94906-bd96-4984-ba74-029d2fec036f.mov

2023-02-16 11:30 UTC, quang-le commented
cypress

2023-02-16 12:41 UTC, codeKameleon approved these changes

2023-02-17 08:10 UTC, beygorghor requested changes
While clicking on cancel, the fields are displaying an error state, not very sure how to handle this
https://user-images.githubusercontent.com/12494624/219588271-ac39fd02-c6fa-42ea-a7b9-894bd4f2727a.mov

2023-02-17 11:09 UTC, quang-le commented
> While clicking on cancel, the fields are displaying an error state, not very sure how to handle this https://user-images.githubusercontent.com/12494624/219588271-ac39fd02-c6fa-42ea-a7b9-894bd4f2727a.mov

That's probably because we reset the state values but the formik context hasn't reset

2023-02-17 11:47 UTC, quang-le commented
cypress

2023-02-20 08:21 UTC, merged