IA-775? Mod network
BLSQ/iaso pull request #391
Opened 2021-09-28 18:06 UTC by olethanh

Remove the custom network code for Polio (and Pages) and replace it with react-query.

This also ensure that we have Snackbars in case of failure for everything. Replace the network code in a few other places too.

Completely remove sendRequest (we had two copy)

2021-09-28 19:07 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/pages/hooks/useGetProfiles.js
> +            structuralSharing: false,
not sure why it was there before so I left it as is

2021-10-05 12:43 UTC, quang-le requested changes
Pages crashes in local at the moment.

Otherwise, just add the translations please. The rest is questions for my education

2021-10-05 12:43 UTC, quang-le commented on plugins/polio/js/src/hooks/useGetOrgUnits.js
> +        () => getRequest(`/api/orgunits/${OrgUnitId}/`),
shouldn't it be `async`?

2021-10-05 14:12 UTC, olethanh commented on plugins/polio/js/src/components/CountryNotificationsConfig/CountryNotificationsConfigModal.js
> +    };
you only need to set setCallback if you use it as a dep of something else. Also in this case I'm not to sure we really need to use the setConfig since we close the dialog afterward ?

2021-10-05 14:13 UTC, olethanh commented on plugins/polio/js/src/components/CountryNotificationsConfig/Table/CountryNotificationsConfigTable.js
> -            },
No, but it will display nothing. We removed the textPlaceholder pretty much everywhere else in the table and normally there shouldn't be a row without country

2021-10-05 14:14 UTC, olethanh commented on plugins/polio/js/src/components/CountryNotificationsConfig/requests.js
> +        ['countryusersgroup'],
Yes

2021-10-05 14:16 UTC, olethanh commented on plugins/polio/js/src/hooks/useGetOrgUnits.js
> +        () => getRequest(`/api/orgunits/${OrgUnitId}/`),
it doesn't need to be since it return a Promise. But I haven't been the most consistant in the code base.

2021-10-06 07:29 UTC, beygorghor approved these changes
This is working for me, just add translations to json file.

2021-10-06 07:29 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/pages/hooks/useGetProfiles.js
> +            structuralSharing: false,
This is a copy paste from polio dashboard original code... i did the same

2021-10-06 07:29 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/pages/hooks/useSavePage.js
> +        undefined,
if you use an object for all the props you can avoid to pass undefined variables, anyway don't change it !!!

2021-10-06 08:48 UTC, quang-le approved these changes

2021-10-06 08:54 UTC, merged