Ia 754 org units
BLSQ/iaso pull request #392
Opened 2021-09-29 11:59 UTC by beygorghor

- reordering and rename org units filters
- put location limit inside filters
-  new color picker 
- change of color if adding one new search
<img width="1658" alt="Screenshot 2021-09-29 at 13 54 34" src="https://user-images.githubusercontent.com/12494624/135264170-3c41abde-57ce-46ed-bb80-dbc6cbce90d7.png">
<img width="1648" alt="Screenshot 2021-09-29 at 13 52 03" src="https://user-images.githubusercontent.com/12494624/135264178-b966cf9e-2f35-4882-a34f-369b6d8b2c43.png">

2021-09-30 06:49 UTC, olethanh commented on iaso/api/serializers.py
> +            "altitude",
you have added these field but I don't see where they are used?

2021-10-01 10:22 UTC, quang-le requested changes
Maybe update bluesquare-components to the latest version to see if the treeview is still aligned.

Otherwise mostly nitpicking with translations

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/forms/ColorPicker.js
> +        height: theme.spacing(4),
I find the button a bit too big, maybe `theme.spacing(2)` is enough?

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.forms.hasInstances": "Forms submissions",
I think it's "Form submissions"

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.instance.undelete": "Mark isntance(s) as not deleted",
"isntance(s)" 😂

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.exportRequest.Status": "Status",
"Statut"

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.instance.undelete": "Marquer une(des) soumission(s) comme non effacée(s)",
"non-effacée(s)"

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.orgUnits.selectionAction": "Avec la sélection d'unité d'organisation",
"unités d'organisation"

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/messages.js
> +        defaultMessage: 'Forms submissions',
"Form submissions"

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +                            <Box mt={1}>
This might break alignment at the next update of blsq-comp

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +                            <Box mt={1}>
It's my fault, I made then reverted a stupid change

2021-10-01 10:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgunitsMapComponent.js
> +            )
😃👍

2021-10-01 10:30 UTC, quang-le approved these changes
I made the small changes from my comments.
Very nice changes.
I still think the color picker should not be on top, but I can live with it

2021-10-06 07:45 UTC, merged