Polio 849 update workflow fields
BLSQ/iaso pull request #397
Opened 2023-02-20 16:03 UTC by quang-le

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-03-06 12:21 UTC, beygorghor approved these changes

2023-03-16 13:58 UTC, olethanh requested changes

2023-03-16 13:58 UTC, olethanh commented on plugins/polio/models.py
> +    re_submitted_to_orpg_at_WFEDITABLE_old = models.DateField(null=True, blank=True)
I still see the old field in BudgetForm.js and useFormValidator.js is that normal?

![image](https://user-images.githubusercontent.com/82500/225640044-fca15671-c7d5-4659-a71e-2aad34692a67.png)

2023-03-16 14:17 UTC, olethanh approved these changes

2023-03-16 14:18 UTC, merged