IA-1670 ou appear as their own children
BLSQ/iaso pull request #410
Opened 2023-02-27 21:03 UTC by SimonDus

If you don't hit the checkbox Only Direct children in org unit search tab children, atm the org unit you are looking the children for will be in the result. 

There is some strange things with this checkbox. If the checkbox is check the paremeter for the parent org unit is "parent_id" if not the parameter  is "orgUnitParentId", I'm not sure why. The parameter "onlyDirectChildren" is sent in both case respectively true or false.

Nevertheless, the parameter "onlyDirectChildren" was appearing in org_unit.py but unused and was missing in org_unit_search.py so I added it. I also added some tests.  

Related JIRA tickets : IA-1670

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## How to test

With the actualy version : 
Go to org unit, search for a org unit with children. 
Go to the children tab and search with the "only direct children" box unchecked
You will find the org unit as its own children in the list. 

With my PR: 
Do the same but you won't find the org unit as its own children.

Do the same and the org unit

2023-03-02 14:47 UTC, mathvdh reviewed
A part mon petit commentaire le reste me semble bien  ...

2023-03-02 14:47 UTC, mathvdh commented on iaso/api/org_unit_search.py
> +    direct_children = params.get("onlyDirectChildren", False)
Je suis pas trop sûr de comprendre ces 2 lines 

```python
direct_children = params.get("onlyDirectChildren", False)
direct_children = False if direct_children == "false" else True
```

En gros la deuxième ligne va toujours écraser la première ... ? Donc je pige pas .. (Si direct_children == "false" alors ca devient faux, dans tous les autres cas ça devient true du coup il s'en fout de `params.get("onlyDirectChildren", False)` Ou c'est moi qui bug ?

2023-03-03 10:16 UTC, SimonDus commented on iaso/api/org_unit_search.py
> +    direct_children = params.get("onlyDirectChildren", False)
Il est vrai que je pourrais mettre None à la place de False. C'est juste que ce param doit toujours être un booléen et non None sinon ça bug beaucoup plus bas. Y'a plusieurs trucs confus dans ce code je trouve. Il y a un petit boulot de refactoring du côté back et front à faire pour rentre consistant l'api et le front.  Cette PR est plus un " quickfix "

2023-03-03 10:28 UTC, mathvdh commented on iaso/api/org_unit_search.py
> +    direct_children = params.get("onlyDirectChildren", False)
@SimonDus je veux dire que tu peux juste effacer la première ligne dans l'état actuel elle sera TOUJOURS effacée par la deuxième ligne non ?

2023-03-03 10:28 UTC, mathvdh commented on iaso/api/org_unit_search.py
> +    direct_children = params.get("onlyDirectChildren", False)
Enfin pas "effacée" mais quoi qu'il y ait dans `direct_children` sera changé par la deuxième ligne

2023-03-03 10:29 UTC, mathvdh commented on iaso/api/org_unit_search.py
> +    direct_children = params.get("onlyDirectChildren", False)
Mais en effet ça semble un peu le bordel entre  "onlyDirectChildren" et "direct_children=false"

2023-03-03 10:32 UTC, mathvdh commented on iaso/api/org_unit_search.py
> +    direct_children = params.get("onlyDirectChildren", False)
Donc c'est pas une question de mettre "None" ou pas à la première ligne parce que cette ligne ne sert à rien dans l'état actuel, ce sera toujours remplacé par True ou False par la deuxième ligne

2023-03-03 10:55 UTC, mathvdh approved these changes

2023-03-07 08:00 UTC, hakifran approved these changes
This is okay for me.

2023-03-07 10:47 UTC, olethanh requested changes
> There is some strange things with this checkbox. If the checkbox is check the paremeter for the parent org unit is "parent_id" if not the parameter is "orgUnitParentId", I'm not sure why. The parameter "onlyDirectChildren" is sent in both case respectively true or false.

> Nevertheless, the parameter "onlyDirectChildren" was appearing in org_unit.py but unused and was missing in org_unit_search.py so I added it. I also added some tests.

The parameters were badly named, but the current behaviour is
`parent_id` -> only direct children
`orgUnitParentId` > The whole hierarchy

it's probably adding to the confusion if we do special casing if we add handling for onlyDirectChildren on top in the API so not sure if that's what we actually want

2023-03-07 10:47 UTC, olethanh commented on iaso/api/org_unit_search.py
> +
shouldn't we add this only if org_unit_parent id is set?

2023-05-11 12:04 UTC, olethanh commented
rebased the change on top of main after consideration I think we can merged it as is.

2023-05-11 13:24 UTC, olethanh approved these changes

2023-05-11 13:24 UTC, merged