IA-1897:  replace SearchFilter component
BLSQ/iaso pull request #414
Opened 2023-03-02 13:08 UTC by codeKameleon

`SearchFilter`  was only used in OrgUnits, i removed the component and refactored `SearchInput` in bluesquare-components to handle text search errors and use `InputComponent` in `OrgunitsFilters` 

Related JIRA tickets : [IA-1897](https://bluesquare.atlassian.net/browse/IA-1897?atlOrigin=eyJpIjoiYzllMWYyZDI4NWFmNDBhNzkyM2ZkODU5YTU2YWQ0OWQiLCJwIjoiaiJ9)
## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## Changes

- use logic in `SearchFilter` to check for forbiddenCharacters and migrate to `SearchInput` in bluesquare-components 
see [here](https://github.com/BLSQ/bluesquare-components/pull/104)
- pass `blockForbiddenChars` and `onErrorChange` props to `InputComponent` and `OrgunitsFilter` to handle error state and disable/enable `SearchButton`

## How to test

- Go to OrgUnits list
-  type something in `Search` filter and try to add forbidden characters (`['"', '?', '/', '%', '&']`) => the error message appears below the input + the search button should be disabled and the press key on this input should be disabled too

## Print screen / video

https://user-images.githubusercontent.com/25134301/222440672-86360fa2-3855-412b-8dfe-7a1b12301a01.mov

[IA-1897]: https://bluesquare.atlassian.net/browse/IA-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Notes

This [PR](https://github.com/BLSQ/bluesquare-components/pull/104) in bluesquare-components needs to be merged before merging this one

2023-03-06 08:21 UTC, beygorghor requested changes
Thanks for this, still some work to make it perfect:

- We have lost error message on form search input while using a special char
<img width="505" alt="Screenshot 2023-03-06 at 09 13 49" src="https://user-images.githubusercontent.com/12494624/223054802-6f61c52c-7b7f-487b-a910-981b1f826426.png">
<img width="439" alt="Screenshot 2023-03-06 at 09 13 28" src="https://user-images.githubusercontent.com/12494624/223054804-247ea8bd-8f37-41bb-96b4-5f28b12ebea6.png">

- We have lost red border while having an error on org unit search:
<img width="572" alt="Screenshot 2023-03-06 at 09 14 38" src="https://user-images.githubusercontent.com/12494624/223054912-d1c7fa6d-89fd-4bdc-9877-26e04d3817ea.png">
<img width="579" alt="Screenshot 2023-03-06 at 09 14 30" src="https://user-images.githubusercontent.com/12494624/223054915-e3f9bc6d-51f2-47dd-82d7-2ae7d5c22438.png">
- You should probably go trough all implementation of this search and check if the check on forbidden chars is required ( if the search is deep linked or not, cf groups, instances, ...)
- Also having Cypress tests on this behaviour can be very cool.

2023-03-08 10:36 UTC, quang-le commented
Please update the PR description (changes,  how to test) since the scope of the PR has changed

2023-03-08 13:18 UTC, beygorghor approved these changes
Ok for me, if you have the time to centralise the search tests into one place, this is a must

2023-03-08 13:18 UTC, beygorghor commented on hat/assets/js/cypress/integration/11 - submissions/list.spec.js
> +        });
These whole describe can go to a method we can call on each page, instead of copy paste it no ?

2023-03-08 13:18 UTC, beygorghor commented on hat/assets/js/cypress/integration/13 - workflows/list.spec.js
> +    // });
Yo can remove this

2023-03-09 07:59 UTC, beygorghor approved these changes
Thanks for the tests. Last step is to wait the merge of the other PR and updates the lock file here.

2023-03-09 09:37 UTC, quang-le requested changes
Works fine, but it should also be replaced in polio campaigns, grouped campaigns and calendar

2023-03-09 10:26 UTC, quang-le approved these changes

2023-03-09 10:27 UTC, merged