POLIO-858: Polio / Budget: migrate repeat button to steps
BLSQ/iaso pull request #430
Opened 2023-03-08 12:46 UTC by beygorghor

Whimsical [link](https://whimsical.com/move-repeat-step-button-8JFFU8XomPLPhKfoxp9fUu)

Moving repeat step button form the top of the page to the correct row of step in step table

Related JIRA tickets : POLIO-858

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new string have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- removed the option to display a repeat action from `AddStepButton` and add `RepeatStepIconProps`
- pre-filter repeat steps in `BudgetDetailsInfos` and pass it to steps table
- Create an action cell for steps
- display repeat button on steps with a repeat action possible

## How to test

Open an existing budget for a specific campaign and country.
Proceed to steps.
You should see the loop icon (mainly on the last step)
Click on it and re submit the step

## Print screen / video

https://user-images.githubusercontent.com/12494624/223716910-5118356e-7ade-4721-97ce-4bfd901fe4d8.mov

2023-03-08 14:57 UTC, quang-le requested changes
We get a strange UX when hiding steps: if we hide the last step, we can't repeat it anymore unless we show hidden steps. I think this will confuse the users. We should probably sit down and spec this:
https://user-images.githubusercontent.com/38907762/223746288-48434216-584f-49a8-a4cc-22b2ba690e67.mov

2023-03-08 14:57 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/AddStepButton.tsx
> +// import { IconButton } from 'bluesquare-components';
you can delete this

2023-03-08 14:57 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/hooks/config.tsx
> +type TablePorps = {
TablePorps 😂

2023-03-09 08:09 UTC, beygorghor commented
> We get a strange UX when hiding steps: if we hide the last step, we can't repeat it anymore unless we show hidden steps. I think this will confuse the users. We should probably sit down and spec this: https://user-images.githubusercontent.com/38907762/223746288-48434216-584f-49a8-a4cc-22b2ba690e67.mov

@quang-le maybe a warning saying you have hidden steps that can be repeated ??

2023-03-16 09:34 UTC, quang-le approved these changes

2023-03-16 13:51 UTC, merged