IA-1947 handle bulk import with task worker
BLSQ/iaso pull request #437
Opened 2023-03-10 12:08 UTC by SimonDus

The bulk create user has been moved as a task. To do it I moved the code that actually create the users out of the view and made it a task. Tests are covering the user creation part. 

Related JIRA tickets : IA-1873

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new string have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## How to test

make a csv file to create users. Check the files from the tests to find how to do it. 
go to /api/bulkcreateuser/ and upload your file. 
Go to task and check if the task is created. 

For the user creation itself,  you must run it from iaso bash using :

` bulk_create_users_task.__wrapped__(uploaded_file, user, False)`

uploaded_file is your csv file mock as an upload.
user is your logged in user
False is to prevent triggering task log when not performing it as a task.

Dont forget to wrap it to dont trigger the task. 

The file must be a mock of an uploade file so you must do it this way : 

```
file = open("path_to_your_test_file")

request = RequestFactory().post("/upload", {"file": file})

        uploaded_file = request.FILES["file"]
```

2023-03-10 12:37 UTC, mathvdh requested changes

2023-03-10 12:37 UTC, mathvdh commented on hat/common/utils.py
> +def is_json_serializable(x):
Ce check additionnel sur les paramètres via `is_json_serializable` est intéressant.

Néanmoins dans l'état il me semble que ça peut péter, en effet dans la doc du module json ils parent d'autres erreurs, telles que `RecursionError` ou `ValueError`

Du coup est-ce que tu ne ferais pas un except vide pour être sur que ça throw pas s'il se passe quoi que ce soit d'autre dans le json.dumps ?

2023-03-10 12:37 UTC, mathvdh commented on iaso/api/bulk_create_users.py
> +@task_decorator(task_name="bulk_create_users")
Il me semble que le code des tasks est un fichier spécifique dans le repertoire `/iaso/tasks` ? Et pas directement dans l'API ... Mais je peux me tromper .. ?

2023-03-13 08:21 UTC, SimonDus commented on hat/common/utils.py
> +def is_json_serializable(x):
Pas faux

2023-03-13 08:28 UTC, SimonDus commented on iaso/api/bulk_create_users.py
> +@task_decorator(task_name="bulk_create_users")
Je bouge ça

2023-03-13 08:34 UTC, mathvdh approved these changes
👍🏼

2023-03-13 09:48 UTC, SimonDus commented
I found a bug. Don't merge it for now

2023-09-27 16:16 UTC, SimonDus commented
I close this PR and will start again from main as it's too outdated and a mess to merge

2023-09-27 16:16 UTC, closed without merging