Add button to check connectivity
BLSQ/iaso pull request #455
Opened 2021-10-26 10:30 UTC by olethanh

https://user-images.githubusercontent.com/82500/138860599-6d8c39d4-f4fb-42b0-976b-0661192f1075.mp4

2021-11-02 18:06 UTC, madewulf commented on iaso/tasks/dhis2_ou_importer.py
> +    print(options_or_url, login, password)
Oh, a forgotten print

2021-11-02 18:06 UTC, madewulf commented on iaso/tasks/dhis2_ou_importer.py
> +    print(options_or_url, login, password)
This will put the password in the logs of the server, I'd rather avoid that, in fact.

2021-11-02 18:41 UTC, olethanh commented on iaso/tasks/dhis2_ou_importer.py
> +    print(options_or_url, login, password)
oups you are right, removed

2021-11-03 17:09 UTC, quang-le requested changes
The test button works fine, but when I try to save (in create and update dialogs), I get a 400:

https://user-images.githubusercontent.com/38907762/140130069-e50ff0d3-c2cf-4d58-b2b1-3f9b49426774.mov


Also, the save button is enabled when we open the modal and haven't made any changes yet

2021-11-04 08:23 UTC, quang-le commented
Error message from the 400: 
```json
{
 "name": "ApiError",
 "status": 400,
 "details": {
  "name": [
   "Ce champ est obligatoire."
  ]
 },
 "message": "Error on GET /api/datasources/ "
}
```

2021-11-04 14:03 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
> +    const projectsIsEmpty = form.project_ids?.value.length === 0;
I left as was the previous check. The idea is that at least a  project is required, so if it's undefined or null it should also be an error.

2021-11-04 14:03 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
> +                                defaultMessage="✅ Connection to server ok"
The magic of unicode ! it's nice and terrifying at the same time.

2021-11-04 14:04 UTC, olethanh commented
rebase on top of main and fixed the problem

2021-11-04 14:53 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
> +    const projectsIsEmpty = form.project_ids?.value.length === 0;
Yeah, but as it is the check on `!projectsIsEmpty` on line 98 will return true when `form.project_ids` is null or undefined, which doesn't seem correct. Or do we catch the error somewhere else?

2021-11-04 21:33 UTC, olethanh commented
> Also, the save button is enabled when we open the modal and haven't made any changes yet
Forgot to address this,  this is one was done on purpose to now match the behavior of the other dialogs in the app to modify object: Project, Group, Type, User, etc..

2021-11-04 21:38 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceDialogComponent.js
> +    const projectsIsEmpty = form.project_ids?.value.length === 0;
Le franc est tombé, I finally get what you mean, I will correct it. Normally it shouldn't be null since we provide a default value but let's make certain.

2021-11-05 08:43 UTC, quang-le approved these changes

2021-11-05 08:44 UTC, merged