POLIO 661: campaign history UI improvements
BLSQ/iaso pull request #458
Opened 2023-03-20 13:32 UTC by codeKameleon

Poor readibility of the the data coming from logs especially for nested values (rounds, scopes,...)
This PR was made in pair coding with @beygorghor to improve the UI

Related JIRA tickets : [POLIO-661](https://bluesquare.atlassian.net/browse/POLIO-661?atlOrigin=eyJpIjoiOTYwMzJlY2M2YmZlNDUxNjkwMzYyZDIyMGM4ZjQwOTciLCJwIjoiaiJ9)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] New translations have been added or updated if new string have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- add `ExpandableItem` component for complex values with nested objects and arrays (rounds, scopes, vaccines, shipments, destructions)
- create a `config.tsx `file to get the key and convert it if necessary with a `getLogValue` function
- centralize logic to render rows with array/objects in `mapLogStructure` function

## How to test

- Go to Campaign
- Choose a campaign
- Edit some fields
- Click on history icon in the edit dialog
- Check through all the log if values are well displayed (ExpandableItem for nested values, links should work, date in the right format)

## Print screen / video

https://user-images.githubusercontent.com/25134301/226388947-b91e23e0-c662-4bbd-8402-c3c8c6ed2259.mov

[POLIO-661]: https://bluesquare.atlassian.net/browse/POLIO-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-22 09:30 UTC, beygorghor requested changes
Coool , thanks for this ! but:
- you have dead code to remove
- This one is a bit alone, we can add the OBR name at least
<img width="624" alt="Screenshot 2023-03-22 at 10 28 05" src="https://user-images.githubusercontent.com/12494624/226859680-6353bfce-b007-44ca-b3ac-602a4917b300.png">
- I still have translatio
![Screenshot 2023-03-22 at 10 28 30](https://user-images.githubusercontent.com/12494624/226859924-b694d04d-79f8-4af8-b04c-d7ff238c7671.png)
ns warning in the console
-

2023-03-22 09:30 UTC, beygorghor commented on plugins/polio/js/src/components/campaignHistory/CampaignLogDetail.tsx
>  const objectLoop = (obj, getValue, getLabel) => {
This part of the code is not used anymore i guess

2023-03-22 09:30 UTC, beygorghor commented on plugins/polio/js/src/components/campaignHistory/CampaignLogDetail.tsx
>  const objectLoop = (obj, getValue, getLabel) => {
objectLoop, ArrayLoop getComplexValue ...

2023-03-24 16:02 UTC, quang-le requested changes
Looks very nice, quite a neat solution overall. Still some small improvements that can be done to code (see comments).

Still some issues in the interface:

- Boolean fields should display more useful information, like yes or no. 

![Screenshot 2023-03-24 at 16 50 29](https://user-images.githubusercontent.com/38907762/227576066-1689419a-1bdd-488f-bbfa-f6ba5fb62450.png)

- I think we should show the name of the org unit instead of the id, or show both

![Screenshot 2023-03-24 at 16 46 12](https://user-images.githubusercontent.com/38907762/227577221-f09fa6fc-e0e7-4588-9188-234637d19559.png)

- There is a field translated as "Approuvé", I think there's something wrong with the json key:
![Screenshot 2023-03-24 at 16 48 20](https://user-images.githubusercontent.com/38907762/227577636-02817d4e-1220-4c48-bb0e-6217e506e4e4.png)

- There are some translations missing: 

![Screenshot 2023-03-24 at 16 43 27](https://user-images.githubusercontent.com/38907762/227577873-44c159d1-61dd-43f2-b73b-84d74aac3d1f.png)
![Screenshot 2023-03-24 at 16 47 09](https://user-images.githubusercontent.com/38907762/227577910-3c696974-41e2-4698-94db-b891e683bacf.png)
![Screenshot 2023-03-24 at 16 44 59](https://user-images.githubusercontent.com/38907762/227577936-f791288d-4c7c-41f8-9909-5676b5bf167c.png)
![Screenshot 2023-03-24 at 16 44 14](https://user-images.githubusercontent.com/38907762/227577958-bcb0399f-b3a5-454f-9ed1-acbeb51f5b12.png)
![Screenshot 2023-03-24 at 16 47 54](https://user-images.githubusercontent.com/38907762/227577978-3b1f42a0-5228-45af-9c32-7f6ff3f39a67.png)
![Screenshot 2023-03-24 at 16 47 41](https://user-images.githubusercontent.com/38907762/227577995-06bd09dd-7ff5-4b2f-9628-49494686b894.png)

- "Fioles" should be replaced with "Flacons". There was a PR for this a while ago, but we may have missed some

![Screenshot 2023-03-24 at 16 43 50](https://user-images.githubusercontent.com/38907762/227578270-4f9ab6eb-8c83-4d61-a3f2-3faaadd6e185.png)

- "Scopes" should be translated here:
![Screenshot 2023-03-24 at 16 45 45](https://user-images.githubusercontent.com/38907762/227578469-51e854b7-7de3-4fac-8700-adeb33f00d07.png)

- We have the same translation for 2 keys:
![Screenshot 2023-03-24 at 16 46 56](https://user-images.githubusercontent.com/38907762/227578624-43493d21-11e6-45ea-9da8-da7b7b117ebc.png)
This one is tricky, because we switched one key for the other at some point in the project

Lots of nitpicking but it's mostly minor stuff. Nice job!

2023-03-24 16:02 UTC, quang-le commented on plugins/polio/js/src/components/campaignHistory/CampaignHistory.tsx
>          }
This should go in the `select` of `useGetCampaignLogDetail`. It's part of the same logic. Also you wouldn't have to repeat your code in `CampaignLogDetail`, lines 39-45

2023-03-24 16:02 UTC, quang-le commented on plugins/polio/js/src/components/campaignHistory/Head.tsx
> +    ...commonStyles(theme),
why the import ? You don't seem to use any className from `commonStyles`

2023-03-24 16:02 UTC, quang-le commented on plugins/polio/js/src/hooks/useGetCampaignFieldLabel.ts
> +};
The function you return is equivalent to `formatMessage`, without adding any functionality as `useGetCampaignFieldLabel` above does, so you don't need it

2023-03-24 16:02 UTC, quang-le commented on plugins/polio/js/src/components/campaignHistory/Row.tsx
> +                <TableCell className={classes.tableCellLabel} width={300}>
Line 67: classes.round does not exist

2023-03-27 07:09 UTC, beygorghor commented
Still missing 3 translations in french please:

![Screenshot 2023-03-27 at 09 06 31](https://user-images.githubusercontent.com/12494624/227866534-b9131418-978a-46bd-b0ac-5a2f0e2cc223.png)

2023-03-28 11:17 UTC, quang-le approved these changes
Nothing blocking.

2023-03-28 11:17 UTC, quang-le commented on plugins/polio/js/src/components/campaignHistory/CampaignLogDetail.tsx
> +        data: { logDetail: campaignLogDetail } = initialLogDetail,
I think if we do this we don't need the `initialData` in the `useSnackQuery`

2023-03-28 11:17 UTC, quang-le commented on plugins/polio/js/src/components/campaignHistory/CampaignHistory.tsx
> +        } = initialLogDetail,
see comment below

2023-03-28 11:17 UTC, quang-le commented on plugins/polio/js/src/hooks/useGetCampaignHistory.ts
> +            initialData,
see comment obove

2023-03-28 11:48 UTC, beygorghor approved these changes

2023-03-28 11:59 UTC, merged