IA-866 multiple forms submissions
BLSQ/iaso pull request #467
Opened 2021-11-04 11:40 UTC by beygorghor

- submissions index to arrow component 
- create topbar component dedicated to submissions
- refactor submissions filters to use local state and redirect only when search pressed
- add forms filter + adapt index page
- adapt routes and menu with new submissions permission and entry
<img width="176" alt="Screenshot 2021-11-04 at 12 34 46" src="https://user-images.githubusercontent.com/12494624/140307398-6400d2ab-c5c7-4966-a526-ea248e00e06b.png">

<img width="1656" alt="Screenshot 2021-11-04 at 12 34 52" src="https://user-images.githubusercontent.com/12494624/140307420-9951df5d-3502-457c-ad39-20bec8d8286a.png">
<img width="1677" alt="Screenshot 2021-11-04 at 12 35 08" src="https://user-images.githubusercontent.com/12494624/140307431-b84c0668-2550-48c4-8d85-0ccc562f4ebb.png">

2021-11-04 14:33 UTC, olethanh commented on iaso/api/instances.py
> +            form = Form.objects.filter(pk__in=form_ids.split(","))
not sure why it's here or if it would work since filter return a list

2021-11-04 14:38 UTC, quang-le requested changes
That's a lot work, but I used to hate this part of the code, and now it's much easier to understand, not to mention another piece of redux is gone 😁
All kidding apart, most of my remarks in the code is non-blocking stuff that we might want to consider next time we have to touch this code.

When testing the feature, I did find some blocking stuff:

- The menu entry is not translated when switching to French
![Screenshot 2021-11-04 at 15 31 52](https://user-images.githubusercontent.com/38907762/140332698-7a7f9af7-9b5a-4162-8b71-b1f95ee1b3bd.png)

- There are 2 text search filters, that interfere with each other:
![Screenshot 2021-11-04 at 15 31 52](https://user-images.githubusercontent.com/38907762/140332949-b4f3a467-b80f-4184-9a90-e8cdf330378c.png)

Not blocking, but worth considering:
- I think the first letter of the status filter options should be Uppercase, to be consistent with other such filters

![Screenshot 2021-11-04 at 15 34 44](https://user-images.githubusercontent.com/38907762/140333306-c37f2d32-b50c-49bc-8d39-25ba37dde25f.png)

- The "error" option in the status filter is shown as "duplicate" in the table, which I find confusing
- It's not clear fro the UI how the date filter work: is "Start date" the exact date, or does it filter "as from" the chosen date?

This doesn't take away the quality and amount of work. Very nice PR

2021-11-04 14:38 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/utils.js
> +    });
We are effectively filtering the `null` | `undefined` values from `allFilters`. It might be worth making a `filter` function for objects. Found some neat ideas on  [SO](https://stackoverflow.com/questions/5072136/javascript-filter-for-objects)

Not blocking.

2021-11-04 14:38 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/index.js
> +    ]);
In a V2, `fetchInstances` and `fetchSmallInstances`can probably be moved to react-query and this `useEffect` removed.

Not blocking

2021-11-04 14:38 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/index.js
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
This can be deleted

2021-11-04 20:22 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/app/components/MenuItemComponent.js
> +    }
or `${path}${menuItem.extraPath|| }` ? tbh all the diferent way are getting confusing.

2021-11-05 08:45 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/hooks.js
> +            cacheTime: 1000 * 60 * 5,
lol copy paste will kill me one day

2021-11-05 08:46 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/utils.js
> +    );
then we need to refactor this in blsq-component too

2021-11-05 08:46 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/index.js
> +    ]);
that was the idea

2021-11-05 09:07 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/hooks.js
> +            cacheTime: 1000 * 60 * 5,
😂

2021-11-05 09:12 UTC, quang-le approved these changes

2021-11-05 10:48 UTC, merged