Multi form react query
BLSQ/iaso pull request #474
Opened 2021-11-05 15:25 UTC by olethanh

2021-11-08 13:35 UTC, beygorghor requested changes

2021-11-08 13:35 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/instances/index.js
> -    createInstance,
You can remove `resetInstances` and `setInstancesFetching` from actions, reducer and test i think

2021-11-09 15:50 UTC, olethanh commented
I removed `resetInstances`  but not `setInstancesFetching` as it is still used

2021-11-10 08:52 UTC, beygorghor approved these changes

2021-11-10 08:52 UTC, merged