IA-877 use snack query in treeview
BLSQ/iaso pull request #483
Opened 2021-11-10 15:33 UTC by quang-le

## Changes

- removed uses of `iasoGetRequest`
- updated network code to use `react-query`& `useSnackQuery`
- refactored `DynamicSelect` to use same component as `Table` to select amount of results to display
- updated dep to blsq-comp

2021-11-18 15:27 UTC, olethanh requested changes
it crash when i do a search  term and press enter. It didn't do so before. Doesn't crash if I click the icon

2021-11-19 09:49 UTC, quang-le commented
> it crash when i do a search term and press enter. It didn't do so before. Doesn't crash if I click the icon

I can't reproduce it locally

2021-11-19 10:06 UTC, olethanh approved these changes

2021-11-19 10:07 UTC, olethanh commented
sorry the error was caused by my installed version of bluesquare component

2021-11-19 10:37 UTC, merged