POLIO-912: make initial_org_unit required and refactor dialog tab to allow an icon
BLSQ/iaso pull request #483
Opened 2023-03-29 14:58 UTC by codeKameleon

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new string have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-03-30 10:25 UTC, quang-le requested changes
When I change tabs without filling out OBR and initial region, the tab errors, and the errored fields should be in error state, but only OBR name is in error:


https://user-images.githubusercontent.com/38907762/228807614-3314b579-8b9d-4366-829b-498a9f995653.mov

2023-03-30 10:25 UTC, quang-le commented on plugins/polio/js/src/components/MainDialog/PolioDialogTab.tsx
> +                )) || <></>
works with `|| undefined` as well

2023-03-30 10:25 UTC, quang-le commented on plugins/polio/js/src/styles/theme.js
> +    },
:+1:

2023-03-30 12:44 UTC, quang-le approved these changes
I fixed the error state of initial org unit so it behaves like the rest of the form

2023-03-31 08:35 UTC, hakifran approved these changes
Seems good to me.

2023-03-31 09:48 UTC, merged