POLIO-920 auto fill statuses
BLSQ/iaso pull request #485
Opened 2023-03-30 07:58 UTC by quang-le

Compute the detection and risk assessment status from the date input in the respective forms

Related JIRA tickets :  POLIO-920

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new string have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Detection: Filling out a date in one of the 3 fields updates the status. Emptying a date updates as well
- Risk Assessment: same as detection, except only 1s draft submission, RRT/OPRTT Approval and DG approval are taken into account to determine the status (cf Jira ticket)
- For both: replaced the status input with text
- Fixed a spacing bug in the budget tab
- Set a default value for both detection status and risk assessment status in the front-end
- Removed unused intl message

## How to test

- Go to polio, open a campaign
- In detection and risk assessment, fill in dates. The statuses should update accordingly

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

merges into POLIO-898

I didn't convert to typescript due to the time constraint on this and other features

2023-03-30 11:42 UTC, codeKameleon approved these changes
Well done !

2023-03-31 09:47 UTC, beygorghor requested changes
Is this normal ?
![Screenshot 2023-03-31 at 11 47 08](https://user-images.githubusercontent.com/12494624/229086896-18e198cc-b1e8-4548-8ab3-bcf8fde51a7c.png)

2023-03-31 09:47 UTC, beygorghor commented on plugins/polio/js/src/forms/DetectionForm.js
> +                                        values.detection_status.toLowerCase()
be careful with this if MESSAGES doesn't contain the status, it will fail. Maybe double check this before and display the key if missing

2023-03-31 12:40 UTC, quang-le commented on plugins/polio/js/src/forms/DetectionForm.js
> +                                        values.detection_status.toLowerCase()
I added it.

2023-03-31 12:47 UTC, beygorghor approved these changes

2023-03-31 12:47 UTC, merged