IA-892 instance period filter
BLSQ/iaso pull request #492
Opened 2021-11-15 12:33 UTC by beygorghor

- refactor instance filters with local state and avoid FilterComponent
- add period type, start and end period filter
- remove period reducer

<img width="1632" alt="Screenshot 2021-11-15 at 11 50 24" src="https://user-images.githubusercontent.com/12494624/141782668-26ba5ef6-487b-44e1-a9ca-ebfb9a69c584.png">
<img width="564" alt="Screenshot 2021-11-15 at 12 38 35" src="https://user-images.githubusercontent.com/12494624/141782690-c3aae2ae-f954-4ffe-b57f-d6563ec588eb.png">

<img width="758" alt="Screenshot 2021-11-15 at 11 53 19" src="https://user-images.githubusercontent.com/12494624/141782710-5cf9e47c-52e0-45e9-8716-9c36c7310b00.png">

2021-11-19 10:34 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +    const endPeriodError = useMemo(() => {
wouldn't it make more sense to use setFieldErrors and to set it in the handleFormChange?

2021-11-19 10:36 UTC, olethanh commented on hat/assets/js/apps/Iaso/domains/instances/constants.js
> +    const user =
seems like a merge error, this broke the feature

2021-11-25 11:28 UTC, quang-le commented
QA test in Jira: https://bluesquare.atlassian.net/browse/IA-936?atlOrigin=eyJpIjoiZWY4ODM2YjVlNmNjNDZkMmJmODVmYzcwYTY3ZTZlNTEiLCJwIjoiaiJ9

2021-11-25 11:35 UTC, quang-le requested changes
See [Jira ticket](https://bluesquare.atlassian.net/browse/IA-936?atlOrigin=eyJpIjoiZWY4ODM2YjVlNmNjNDZkMmJmODVmYzcwYTY3ZTZlNTEiLCJwIjoiaiJ9)

Blocking and in scope (number refers to ticket description): 6
In scope but not critical: 5
Not in scope of this PR, but related to submissions: 1,2,3,4

2021-11-25 15:41 UTC, quang-le approved these changes

2021-11-25 15:41 UTC, merged