POLIO-926: campaign history logs some fields are not displayed
BLSQ/iaso pull request #493
Opened 2023-03-31 13:40 UTC by codeKameleon

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new string have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-04-03 07:12 UTC, hakifran commented
@codeKameleon while testing I noticed that two fields still missing in the history: Disbursed to MOH (WHO) and Disbursed to MOH (unicef)
![Annotate-a-local-image(48)](https://user-images.githubusercontent.com/19631540/229436845-8321a584-6f87-40c8-a59c-53422221fb1e.png)

2023-04-04 08:12 UTC, beygorghor requested changes

2023-04-04 08:12 UTC, beygorghor commented on plugins/polio/js/src/components/campaignHistory/config.tsx
> -        key: 'budget_status',
I guess those field needs to stay has previous campaigns can still use it no ? @olethanh  ?

2023-04-06 13:25 UTC, olethanh commented on plugins/polio/js/src/components/campaignHistory/config.tsx
> -        key: 'budget_status',
altough we could still check in db if it was actually ever used

2023-04-13 09:37 UTC, codeKameleon commented on plugins/polio/js/src/components/campaignHistory/config.tsx
> -        key: 'budget_status',
@beygorghor @olethanh I created an other ticket to add those fields : [POLIO-939](https://bluesquare.atlassian.net/browse/POLIO-939?atlOrigin=eyJpIjoiNWQ4OGU3ZDMyMzdhNGNlZWJiZWIxYWEzZmQxZjBiN2UiLCJwIjoiaiJ9)

2023-04-13 10:22 UTC, codeKameleon commented
@cypress

2023-04-13 16:11 UTC, beygorghor approved these changes

2023-04-13 16:11 UTC, merged