Wc2 196 current date
BLSQ/iaso pull request #513
Opened 2023-04-13 07:37 UTC by beygorghor

The follow-up feature should allow to pick a date field and to compare it to the “now” variable that represents the current moment. 
On top of “enter date”, it should be possible to pick as option “current time” for date fields, so that on mobile, we can compare the current time with. This would result in using the “currentTime” string in the formula at the place where the date was entered.

Related JIRA tickets : [WC2-196](https://bluesquare.atlassian.net/browse/WC2-196)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- adding custom fields for query builder (currentDateTime, currentDate), make it optional 

## How to test

- Go to beneficiary types
- Select a type with a reference form using date and date time 
[registration_sudan_2023030845465465.xlsx](https://github.com/BLSQ/bluesquare-components/files/11219129/registration_sudan_2023030845465465.xlsx)
- select / create a version and add a follow-up
- you should be able to select current date or date time for date time and date fields
- those custom fields should not be available while performing a search in the 

## Print screen / video

https://user-images.githubusercontent.com/12494624/231686623-d79538be-6bb2-4e88-9d34-03a738f64192.mov

[WC2-196]: https://bluesquare.atlassian.net/browse/WC2-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Notes

⚠️ Please use/merge [this](https://github.com/BLSQ/bluesquare-components/pull/113) before ⚠️

2023-04-17 13:28 UTC, codeKameleon approved these changes

2023-04-17 14:24 UTC, quang-le requested changes

2023-04-17 14:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/utils/jsonLogicParse.ts
> +            }
This change should be mirrored for date time

2023-04-18 09:08 UTC, quang-le approved these changes

2023-04-18 09:32 UTC, merged