IA-2053 : workflow version changes/follow-up order
BLSQ/iaso pull request #523
Opened 2023-04-17 12:45 UTC by beygorghor

On a workflow details page, follow-ups are not sorted by order and changes are nor not sortable.

Related JIRA tickets : IA-2053

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- change workflow detail api to order follow-ups by order field
- moved changes result from detail cal to a dedicated one, allowing ordering of results
- plug new api features to front-end

## How to test

- Edit a existing non draft workflow version with multiple changes and follow-ups 
- follow-ups should be displayed ordered on order field
- you should be able to change order of changes by clicking in a head cell

## Print screen / video

https://user-images.githubusercontent.com/12494624/232487806-c0baefe8-f81a-4607-8482-96c4e2cb03d2.mov

2023-04-17 14:34 UTC, quang-le approved these changes

2023-04-17 14:34 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/workflows/details.tsx
> +    }: // isLoading: isLoadingChanges,
comment

2023-04-17 14:34 UTC, quang-le commented on iaso/api/workflows/changes.py
> +        queryset = WorkflowChange.objects
shouldn't that be `objects.all()`?

2023-04-18 07:16 UTC, beygorghor commented on iaso/api/workflows/changes.py
> +        queryset = WorkflowChange.objects
i think the all is required if you want to parse it, not to build a `queryset`

2023-04-18 09:01 UTC, beygorghor commented
This is breaking cypress tests

2023-04-19 09:29 UTC, mathvdh requested changes
I have put a comment with 3 lines to be removed otherwise it seems good to me

2023-04-19 09:29 UTC, mathvdh commented on iaso/api/workflows/serializers.py
> +    def get_queryset(self):
I think we can remove this as it was not working ..

2023-04-24 08:28 UTC, merged