IA-1483 query builder
BLSQ/iaso pull request #55
Opened 2022-10-04 13:48 UTC by beygorghor

No problem here, only a new feature: allow to search in submission fields using json logic

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests

## Changes

- using brand new components from bluesquare-components [PR](https://github.com/BLSQ/bluesquare-components/pull/80)
- use possible fields and form descriptor to get fields label and value for select and multiselect

## How to test

Open submissions page and select a unique form.
A new field appear beneath.
Click on it and ply with the query builder to search into fields value
Check that the results are corrects

## Print screen / video

![Screenshot 2022-10-04 at 15 19 39](https://user-images.githubusercontent.com/12494624/193836208-844c57df-56c3-499f-9dd2-887e28b6b906.png)
![Screenshot 2022-10-04 at 15 19 30](https://user-images.githubusercontent.com/12494624/193836216-70586a7b-63c8-4dc8-b556-b90bb0defcd7.png)
![Screenshot 2022-10-04 at 15 19 21](https://user-images.githubusercontent.com/12494624/193836224-82f5c5ea-2b5e-44ca-8d5d-68096f8ab502.png)
![Screenshot 2022-10-04 at 15 19 09](https://user-images.githubusercontent.com/12494624/193836226-0ddb2cbf-8952-4a91-8126-e1a102f706fc.png)

## Notes

I'm using by default last_version on the form selected.
Other operators such as proximity, contains, ... are disabled for now because backend is not supporting it

2022-10-17 09:55 UTC, olethanh commented
Pushed a fix for a crash when it was trying to translate a select.

Played with it a bit, it works well overall, the big issue I see, and that's probably a problem in the backend (cc @niconoe ), is that the filter for number don't work. 
The root is probably that we store everything as string in the backend and that we would need to cast them.  Found a lead here, https://code.djangoproject.com/ticket/29769#comment:5 don't know how far that will take us

Small bug in the frontend:
- Add a filter for a single select.
- Go to the json
- Set  a value that's not part of the listed choice
- Click apply
- Go back to the query tab. It show nothing

in video: https://user-images.githubusercontent.com/82500/196147843-604674b5-d190-4272-8a3d-bdf63e0485c4.mp4


Didn't take a look at the code, it was quite big in blsq-components

2022-10-17 10:22 UTC, beygorghor commented
> 

@olethanh Are you sure that the name of the field is correct ? it's working on my side 

https://user-images.githubusercontent.com/12494624/196153911-c4a5940b-3b07-4b7c-a98d-176ee9e7952e.mov

2022-10-17 13:23 UTC, olethanh commented
@beygorghor it's if you put a value that's not part of the listed choice

2022-10-17 14:49 UTC, codeKameleon approved these changes

2022-10-18 07:52 UTC, beygorghor commented
> @beygorghor it's if you put a value that's not part of the listed choice

then it's normal

2022-10-18 09:24 UTC, quang-le requested changes
Code is very clean and readable, it was very easy to review.
About the feature:
- The field doesn't stand out very much, if you don't know that it will show up when you select a form, it's easy to miss that there's an additional field/filter that popped up. 
- For later version, we may want to show something more readable than the json in the `FakeInput`, as it's not super readable even for technical users
- There seems to be no validation of the json, are there backend checks to ensure it's safe. Users can send pretty much anything to the backend:

https://user-images.githubusercontent.com/38907762/196391323-afa36d78-e0fc-40a5-b971-a0da1b4cc343.mov

- Activating the `NOT`operator crashes the UI:

https://user-images.githubusercontent.com/38907762/196391453-28e46388-832b-4635-9b71-226fd54cbef4.mov

2022-10-18 09:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/types/forms.ts
> +export type Children = {
That's not a great type name I think , as it can lead to confusion the `children` prop from react

2022-10-18 09:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/types/forms.ts
> +    children: Children[];
see above

2022-10-18 09:24 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesFiltersComponent.js
> +    const formsList = useMemo(() => (data && data.forms) || [], [data]);
data?.forms??[] (or data?.forms || [])

2022-10-18 13:34 UTC, beygorghor commented
TO be fixed by @niconoe => Activating the NOT operator crashes the back-end

2022-10-20 09:33 UTC, beygorghor commented
@quang-le main has been merged into this branch and the "!" operator is working now

2022-10-20 12:29 UTC, quang-le approved these changes
Awesome work!

2022-10-20 12:30 UTC, merged