IA-796 + IA-783
BLSQ/iaso pull request #552
Opened 2022-01-04 14:48 UTC by beygorghor

2022-01-05 14:33 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/orgUnits/index.js
> +                                                orgUnits
yes thanks

2022-01-07 13:52 UTC, quang-le requested changes
Very nice to see all this redux gone 😁

Also farewell `UNSAFE_ComponentWillMount`!

please just check the redirection. Otherwise the code is much cleaner and legible, and the component seems to work fine 👍

2022-01-07 13:52 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/index.js
> +    ];
I'll change and push

2022-01-07 13:52 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/index.js
> +    );
I'll change and push

2022-01-07 13:52 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/index.js
> +        [params.pageSize, params.order, params.page, searches],
Adding getEndpointUrl would require to put it in its own callback, which might might have unintended side effects because of the deps array. I'll open a ticket to review all callbacks in this component

2022-01-07 13:52 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/index.js
> +    }, [params.validation_status, params.validation_status]);
I'll remove the duplicated param, but adding the whole of params to the effect might mess things up. I'll deactivate the rule and add a comment for the time being

2022-01-07 13:52 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/index.js
> +    }, [warningDisplayed, params.locationLimit, tab]);
will add it

2022-01-10 09:55 UTC, merged