IA-2078: from completeness stats table link back to ou linked submissions
BLSQ/iaso pull request #580
Opened 2023-05-05 16:00 UTC by codeKameleon

Add a link in actions column to access the organization unit linked submissions

Related JIRA tickets : [IA-2078](https://bluesquare.atlassian.net/browse/IA-2078?atlOrigin=eyJpIjoiZjAzYjcxZWMwZThlNDk1YjkzMzU2ODI4Y2M3NTI4NmMiLCJwIjoiaiJ9)

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- add a link in actions column
- add message
- 

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-05-08 12:19 UTC, quang-le requested changes

2023-05-08 12:19 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/completenessStats/hooks/useCompletenessStatsColumns.tsx
> +                        )}
Please use the Org unit id, as the name is not unique (see other buttons in the action column)

2023-05-09 08:47 UTC, hakifran approved these changes
@codeKameleon , a part the comment made by Son, which seems crutial to me too on the remplacement of the orgunitName by the orgunit_id, the rest looks good to me

2023-05-09 08:47 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/completenessStats/hooks/useCompletenessStatsColumns.tsx
> +                        )}
Same comment

2023-05-09 10:10 UTC, beygorghor requested changes

2023-05-09 10:10 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/completenessStats/hooks/useCompletenessStatsColumns.tsx
> +                        )}
also i would check if the user has `iaso_submissions` permission

2023-05-10 07:54 UTC, beygorghor approved these changes

2023-05-10 07:54 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/completenessStats/hooks/useCompletenessStatsColumns.tsx
> +                );
using valuesIn from lodash you can make something like that:
`const hasFormSubmissions = valuesIn(formStats).some(stat => stat.itself_has_instances > 0 );`

2023-05-10 08:48 UTC, beygorghor approved these changes

2023-05-15 16:30 UTC, quang-le approved these changes

2023-05-16 07:06 UTC, hakifran approved these changes

2023-05-16 07:10 UTC, merged