POLIO-1011 fix group dropdown in campaigns page
BLSQ/iaso pull request #589
Opened 2023-05-12 09:43 UTC by olethanh

Now we don't need the group permission to have the Group dropdown.
And it works in the anonymous calendar

Related JIRA tickets : POLIO-2011

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [x] Are there enough tests
- [x] Documentation has been included (for new feature)

## Changes

Added a new API for group that we can use later in dropdowns: `/api/groups/dropdown/`

## How to test

- Test the polio interface with an user without the group permission
- Test the embeddedCalendar in an private page.

2023-05-15 08:24 UTC, hakifran requested changes
And also there should be this `{
        isRequired: false,
        key: "orgUnitGroups"
    }` to be added in the /polio/js/config.js on campaignsFilters so that it can be taken in account while filtering on orgUnitGroups.

2023-05-15 08:24 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/orgUnits/hooks/requests/useGetGroups.ts
> +                return data.groups.map(group => {
There is no groups in data, you should map directly data `TypeError: data.groups is undefined.`
![Screenshot from 2023-05-15 10-04-54](https://github.com/BLSQ/iaso/assets/19631540/be432554-5a5c-4d85-9548-f4eca55b347f)

2023-05-15 16:29 UTC, quang-le requested changes
I get the response from the API, but I don't see anything in the dropdown list:
![Screenshot 2023-05-15 at 18 27 40](https://github.com/BLSQ/iaso/assets/38907762/9676a4ad-e9be-4140-8cee-4906c5bd7200)

2023-05-16 08:52 UTC, quang-le requested changes
In the embedded calendar, the dropdown shows, but the filter is not applied in the video, applying the filter should only keep the Benin campaign. It works in the normal calendar though)


https://github.com/BLSQ/iaso/assets/38907762/b4acc7b8-a5dd-4d87-9144-590bfa93502a

2023-05-16 09:28 UTC, quang-le approved these changes

2023-05-16 09:28 UTC, merged