IA-632 leaflet
BLSQ/iaso pull request #591
Opened 2023-05-12 14:39 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-05-31 13:56 UTC, quang-le requested changes
THE FIT TO BOUNDS NIGHTMARE IS FINALLY OVER!

Nothing really deep to say about the code.

- There's a z-index bug with the tooltips:

![Screenshot 2023-05-31 at 14 46 39](https://github.com/BLSQ/iaso/assets/38907762/6ef79003-3668-4515-9b15-9e2d5d5211b3)

- In registry: it's impossible to close the pop-up

https://github.com/BLSQ/iaso/assets/38907762/9027332a-c4e0-4451-bf54-8e241ec0a176

- In org units details map, the fit to bounds seems a bit off:


https://github.com/BLSQ/iaso/assets/38907762/ddcb608e-3744-4e4f-96b9-68f03f454886

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/GeoJsonMapComponent.tsx
> +    }, [currentTile]);
I don't understand this part. It seems to me this effect will never run, as `ref.current` is initialized with `null` and is not set anywhere else in the component

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/GeoJsonMapComponent.tsx
> +    const boundsOptions: Record<string, any> = {
memo

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/tools/CustomTileLayer.tsx
> +    const ref: any = useRef(null);
`RefObject<any>`

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/tools/CustomZoomControl.tsx
> +            fitToBoundsTitle: formatMessage(MESSAGES['fit-to-bounds']),
Why not `MESSAGES.boxZoomTitle` etc? I see no apparent reason not to use camelCase for the message keys

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/tools/CustomZoomControl.tsx
> +    L.control.zoom = opts => {
`opts` could be typed

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/tools/MapToggleCluster.tsx
> +    setIsClusterActive: Dispatch<SetStateAction<boolean>>;
it just occurred to me that when we want to pass state+setState as props, we could just do 
```javascript
const activeClusterState = useState<boolean>()
// some code
<MapToggleCluster clusterState = {activeClusterState}/>
```

Then in `MapToggleCluster`:
```javascript
const [isClusterActive, setIsClusterActive] = clusterState
```

Not sure we gain much by doing that though, and the linter may complain that the setter should be wrapped in useEffect. 

I just don't like passing these values separately, but passing them together and pattern matching them in the child is not really better ☹️

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/tools/TileSwitchComponent.js
As far as I can see, this component is only used by `TileSwitchDialog`, so we could remove `injectIntl` and `withStyles` even if we don't convert it to arrow function without too much risk. Bonus points for TS conversion

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/instances/components/InstancesMap/useResetMapReducerOnUnmount.ts
🍾

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/OrgUnitMap/useRedux.ts
Only one left...

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/maps/MarkerMapComponent.tsx
> +    const boundsOptions: Record<string, any> = {
`type BoundOptions = Record<string, [number,number] | number>`

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/ListMap.tsx
> +    const bounds = useMemo(
const bounds : Bounds | undefined ?

2023-05-31 13:56 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/OrgUnitsMap.tsx
> +    let bounds: Bounds | undefined;
nitpick, but style wise,  I'd prefer:
```javascript
if (locationsBounds && shapeBounds) {
    return locationsBounds.extend(shapeBounds);
    } else if (locationsBounds) {
       return locationsBounds;
    } else if (shapeBounds) {
       return shapeBounds;
    }
return undefined
```

2023-06-01 07:32 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/maps/GeoJsonMapComponent.tsx
> +    const boundsOptions: Record<string, any> = {
in fact this is useless, props passed to the map are immutable, to update a value you need to use a hook or leaflet...

2023-06-01 09:07 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/maps/tools/MapToggleCluster.tsx
> +    setIsClusterActive: Dispatch<SetStateAction<boolean>>;
the isClusterActive is used in the parent component too sometimes ... i'll leave it like that for now

2023-06-01 09:43 UTC, beygorghor commented
@Son, regarding the last video, can you check that the parent has a shape and is very small ? i have the same problem on my side with this org unit

2023-06-01 11:44 UTC, quang-le commented
> @son, regarding the last video, can you check that the parent has a shape and is very small ? i have the same problem on my side with this org unit

Yes, indeed. I tried an org unit with no parent and the fit to bounds was ok

2023-06-01 11:46 UTC, quang-le approved these changes
LET'S MERGE!!

2023-06-01 11:46 UTC, merged