IA-2166 Org unit types: refactor
BLSQ/iaso pull request #593
Opened 2023-05-15 12:10 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-05-16 10:38 UTC, beygorghor commented on iaso/api/org_unit_types/serializers.py
> +    return parents_ids
@olethanh this can probably be improved, also we should write test for this .. it could be a good pair programing topic ?

2023-05-17 10:12 UTC, quang-le requested changes
REMOVE ALL THE REDUX!!!!
Front-end looks OK to me apart from the sort. Nice cleaning up!

2023-05-17 10:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useSaveOrgUnitType.ts
> +    const ignoreErrorCodes = [400];
Why do we ignore the 400?

2023-05-17 10:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/index.tsx
> +                </Grid>
This should go above the table to align with the rest of Iaso

2023-05-17 10:12 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useGetOrgUnitTypesDropdownOptions.ts
> +        },
The sort is not working well: it seems to order correctly between the `null` depths. Maybe assign a value like `0` or `100` when `depth` is `null`, depending on where they should appear in the order:

```javascript
 .sort((orgunitType1, orgunitType2) => {
                    const depth1 = orgunitType1.depth ?? 0;
                    const depth2 = orgunitType2.depth ?? 0;
                    return depth1 < depth2 ? -1 : 1;
                })
```

2023-05-17 10:13 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/orgUnitTypes/hooks/useSaveOrgUnitType.ts
> +    const ignoreErrorCodes = [400];
I got it  we catch it in the component

2023-05-17 13:15 UTC, quang-le approved these changes

2023-05-17 13:53 UTC, merged