IA-1013 and IA-1012 Deeplink of Campaign and Page Table, fix rest page issue.
BLSQ/iaso pull request #594
Opened 2022-01-19 12:11 UTC by olethanh

2022-01-21 10:58 UTC, beygorghor requested changes
<img width="1684" alt="Screenshot 2022-01-21 at 11 54 55" src="https://user-images.githubusercontent.com/12494624/150515260-ccbd1b29-8363-489c-a756-672415ce4646.png">

IA-1012 is stil displaying page 3 in pagination.
Each time the filters change the page page should be set to 0.
Search for `resetPageToOne` in the code base.

2022-02-02 12:34 UTC, beygorghor approved these changes

2022-02-07 09:27 UTC, quang-le requested changes
I've this weird bug when I filter for a date then change the page row number:

Then, when I reload (ctrl+r) the same page, the date is changed: 


https://user-images.githubusercontent.com/38907762/152761086-13b6464c-74a5-4223-a02a-9250dbc14e6b.mov

2022-02-07 14:20 UTC, quang-le approved these changes

2022-02-07 14:31 UTC, merged