Wfp plugin
BLSQ/iaso pull request #614
Opened 2022-01-25 15:52 UTC by SimonDus

@madewulf for the duplicate check, even with the OneToOne field I have to add a try/catch or check if an entity with the same attributes already exists.  Or maybe I'm missing something :). I don't know which one is best to use between the try/catch or if.

2022-01-26 08:22 UTC, SimonDus commented
I mixed the creation of wfp plugin and the Entity API in this pullrequest. I'm fixing it right now

2022-01-26 08:26 UTC, olethanh commented
Yes it's probably better to split the two for now. As Martin you can just  reuse our generic ModelViewset no need to reimplement everything

2022-01-26 12:59 UTC, SimonDus commented on iaso/api/entity.py
> +        return JsonResponse(created_entities, safe=False)
I decided to overwrite create as it basically create an Entity but allows to create multiple entities in 1 request as Martin asked. I tried with bulk_create but it was ending in making it more complicated than necessary in my opinion as anyway I couldn't make it in one line because of the assignment of entity_type and attributes so I opted for the " KISS " practice.

2022-01-28 09:19 UTC, olethanh requested changes

2022-01-28 09:19 UTC, olethanh commented on iaso/api/entity.py
> +            return True
please comment  the perm logic like it was done for other API endpoint

2022-01-28 09:19 UTC, olethanh commented on iaso/api/entity.py
> +        query_param = request.query_params.get("entity")
rename to deletion_status like for campaign.  We can probably reuse the same filter

2022-01-28 09:19 UTC, olethanh commented on iaso/api/entity.py
> +                )
Use a serializers.ValidationError instead. Instead of "result" use the proper field name
is there an associated unique constraint on the model?

2022-01-28 09:19 UTC, olethanh commented on iaso/api/entity.py
> +        return JsonResponse(created_entities, safe=False)
sorry we had a misunderstanding what I was suggesting was to have a separate endpoint called `/bulk_create/` not to use the  bulk_create function.

2022-02-02 10:59 UTC, olethanh commented on iaso/models/entity.py
> +        )
this should not be needed since you have  have serializers

2022-02-02 11:22 UTC, beygorghor commented on iaso/models/entity.py
> +        )
it's removed

2022-02-03 08:45 UTC, closed without merging