IA-2156 form attachments front
BLSQ/iaso pull request #616
Opened 2023-05-24 14:17 UTC by beygorghor

Allow to upload, delete, create attachment linked to a form

Related JIRA tickets : IA-2156

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Split form version detail with two tabs, versions and attachments
- Attachments table with sort and pagination
- delete an attachment
- upload/update attachment

## How to test

Go to a detail form page and click on the attachments tab.
Try to upload several times different files.
Upload a same file a again an check that it has updated the previous one
Try yo delete and download a file.

## Print screen / video

https://github.com/BLSQ/iaso/assets/12494624/a1afa16d-b524-43a6-965c-b8969b2511cb

2023-05-26 13:46 UTC, codeKameleon approved these changes

2023-05-30 09:29 UTC, quang-le requested changes
only minor changes. very readable once again

2023-05-30 09:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/AttachmentModal.tsx
> +    const handleConfirm = () => {
useCallback

2023-05-30 09:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/AttachmentModal.tsx
> +            <FilesUpload
Nice to see it re-used 😀

2023-05-30 09:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormAttachments.tsx
> +};
This can be moved to a config.ts I think

2023-05-30 09:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormAttachments.tsx
> +    return [
Shouldn't that be in a memo?

2023-05-30 09:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormAttachments.tsx
> +                    iconProps={{}}
Is that TS complaining if you leave it undefined? If so we should make the change in blsq-comp, no? (It's not exactly pressing though)

2023-05-30 09:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/detail.js
> +                    <FormAttachments formId={params.formId} params={params} />
Is there a reason to pass the id separately (like reusing the component elsewhere)? We pass it twice since it's part of the params anyway

2023-05-30 09:51 UTC, quang-le approved these changes

2023-05-30 09:54 UTC, merged