IA-1497: provide planning filter forms list frontend
BLSQ/iaso pull request #627
Opened 2023-05-31 12:49 UTC by codeKameleon

We couldn't filter forms list result by related planning

Related JIRA tickets : IA-1497

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- add planning to params
- split the results of planning filter to sort on multiple plannings

## How to test

- Go to forms
- Play with the Planning filter, see if the results are correct

## Print screen / video

https://github.com/BLSQ/iaso/assets/25134301/e1d76f45-3684-4f04-8d77-e8fb6c6bc0e3

2023-06-01 09:55 UTC, beygorghor requested changes
i have an issue with the search button:
![Screenshot 2023-06-01 at 11 54 25](https://github.com/BLSQ/iaso/assets/12494624/74f7722c-13d3-44d1-98b4-a352a4ebb795)

2023-06-01 09:55 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/forms/components/Filters.tsx
> +    const { data: planningsDropdown } = useGetPlanningsOptions();
`planningsDropdownOptions` ?

2023-06-01 09:55 UTC, beygorghor commented on iaso/api/forms.py
>          planning_id = self.request.query_params.get("planning", None)
i would call it `planning_ids` then

2023-06-01 09:56 UTC, beygorghor commented
Also you have a conflict and js test are failing

2023-06-01 14:13 UTC, codeKameleon commented
@cypress

2023-06-05 10:34 UTC, beygorghor approved these changes
just a .only to remove, i'll do it

2023-06-05 10:34 UTC, beygorghor commented on hat/assets/js/cypress/integration/02 - forms/list.spec.js
> +    describe.only('api', () => {
I'll fix that

2023-06-05 15:59 UTC, merged