IA-1039: Entities + entity types front
BLSQ/iaso pull request #628
Opened 2022-02-01 15:08 UTC by beygorghor

⚠️ This sis a merge into wfp-plugin branch
⚠️ Python test are failing, as well as the base branc
<img width="839" alt="Screenshot 2022-02-01 at 16 04 48" src="https://user-images.githubusercontent.com/12494624/151994266-644ebe5f-122d-43e2-bce1-3c2cead9be86.png">
<img width="694" alt="Screenshot 2022-02-01 at 16 04 55" src="https://user-images.githubusercontent.com/12494624/151994275-1710f3c6-c5ac-4369-aab3-08e23d63eba7.png">
<img width="350" alt="Screenshot 2022-02-01 at 16 05 02" src="https://user-images.githubusercontent.com/12494624/151994277-29e0f1ab-1782-4293-8178-63f4fe8ed265.png">
<img width="836" alt="Screenshot 2022-02-01 at 16 05 10" src="https://user-images.githubusercontent.com/12494624/151994279-4bd11d0c-3d3c-4dfa-ae07-d1c823086788.png">
h

2022-02-03 14:49 UTC, quang-le requested changes
Just reviewing the front-end: very clean

There's a few things we need to agree about, like the file format for hooks and when/where to put types that should be used throughout Iaso (like `Messages`), but otherwise the code is very neat and easy to read, and the test on my local machine seems to work like a charm.

Just please wrap these callbacks in `useCallback` 🤓

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
> +
I don't really understand the use of this type? I guess it has to do with the form values

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
> +    const classes: any = useStyles();
Booooooh `any` 😋

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
> +    const getErrors = k => (errors[k] ? [errors[k]] : []);
`errors[k]??[]`

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
> +                    formik.resetForm();
This is cool, we need that elsewhere in Iaso as forms don't reset on cancel or even on save

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
> +                            url={`/${baseUrls.instanceDetail}/instanceId/${values.attributes}`}
This is a bit of a strange feature, since you kind of expect to be able to go back from the submission to the modal you had opened

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/Filters.tsx
> +export default Filters;
Why not a named export? They get better support from IDEs

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/Filters.tsx
> +    const handleSearch = () => {
This should be wrapped in a useCallback since it depends on a state value and is not passed as prop through a lambda

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/components/Filters.tsx
> +    const handleChange = (key, value) => {
same as handleSearch

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/config.tsx
> +type Column = {
Like Message we can probably also make this type available through the whole app

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/components/EntityTypesDialog.tsx
> +type EmptyEntityType = {
Same as EmptyEntity, I don't really get this type

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/components/EntityTypesDialog.tsx
> +    const { values, setFieldValue, errors, isValid, initialValues } = formik;
you could add handleSubmit in there, no?

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/components/Filters.tsx
> +    const handleSearch = () => {
Same as other Filters with useCallback

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/components/Filters.tsx
> +    const handleChange = (key, value) => {
useCallback, yadda yadda

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/useGetTypes.ts
> +};
I don't get why make one file per hook, but group them here.

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/hooks/useGetTypes.ts
> +            staleTime: 300000,
5 mins is a bit long though  😅

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/index.tsx
> +    // AddButton as AddButtonComponent,
You can remove this

2022-02-03 14:49 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/types/paginatedEntityTypes.ts
> +export type PaginatedEntityTypes = {
This as well: we could make a base type with `count`, `has_next`,  etc,  and extend it when we need to create a new paginated type

2022-02-07 07:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/nav/TopBarComponent.js
> +            title && title !== '' ? `| ${title}` : ''
`title ? `| ${title}` : ''` is doing the thing in fact

2022-02-07 08:19 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/entities/components/EntityDialog.tsx
> +                    formik.resetForm();
yes i was thinking about it ...

2022-02-07 13:08 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/components/EntityTypesDialog.tsx
> +    const { values, setFieldValue, errors, isValid, initialValues } = formik;
resetForm too !

2022-02-07 13:26 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/entities/entityTypes/index.tsx
> +    // AddButton as AddButtonComponent,
required for add dialog

2022-02-08 09:56 UTC, quang-le approved these changes

2022-02-08 09:56 UTC, merged