IA-1944: Frontend - user roles management and changes to users page
BLSQ/iaso pull request #632
Opened 2023-06-05 11:58 UTC by hakifran

Explain what problem this PR is resolving
Add front for user roles creation
Related JIRA tickets : [IA-1944](https://bluesquare.atlassian.net/browse/IA-1944)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Display user roles list

## How to test

- Go to the admin menu
- Go to the user roles submenu

## Print screen / video

2023-06-26 08:02 UTC, beygorghor approved these changes
Only small improvements, very nice job!

2023-06-26 08:02 UTC, beygorghor commented on hat/assets/js/apps/Iaso/constants/routes.js
> +        })),
`...paginationPathParams` is enough 😉

2023-06-26 08:02 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +                )
You can create a `useMemo` with sorted permissions

2023-06-26 08:02 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/userRoles/components/UserRolesFilters.tsx
> +        <>
useless fragment

2023-06-26 08:09 UTC, beygorghor commented
Also we can provide a filter on users page to filter users by user roles, but maybe on another ticket

2023-06-26 09:18 UTC, hakifran commented
> 

Working on this

2023-06-28 10:07 UTC, beygorghor approved these changes

2023-06-29 12:02 UTC, quang-le requested changes
Excellent work on a very rich feature!

Code-wise, there's only one blocking comment, the rest is mostly style-stuff

There are a few minor bugs that still required fixing:

- In the users role page, when changing the `PageSize`, we get a 404. I suspect it will be the same changing pages. Check the `paginationPArams` in routes.js


https://github.com/BLSQ/iaso/assets/38907762/fb698ab5-2155-46e0-b6dd-68a1ebbb0eee

- Some permissions are not translated for user roles (but they are in the users modal):
![Screenshot 2023-06-29 at 12 01 26](https://github.com/BLSQ/iaso/assets/38907762/e84ebe94-cc53-47a9-9454-918f82c2aa09)

- you need to filter out the `iaso_beneficiaries` permission. It's a legacy that we can't remove because it breaks some stuff, but it's not supposed to be used anymore. It's `iaso_entities` that has "taken over"
![Screenshot 2023-06-29 at 11 48 45](https://github.com/BLSQ/iaso/assets/38907762/245b09a4-4e97-46ec-9ccd-2847bf8a1515)

- You need to reset the state of the Create/Edit modal for user roles when closing it:


https://github.com/BLSQ/iaso/assets/38907762/8d593bd1-073b-4ab0-aea1-577a0a39c61c

Overall it's all relatively minor stuff. Great work!

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/constants/menu.js
> +/* eslint-disable react/jsx-props-no-spreading */
we should remove this rule from the es-lint config

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.teams.delete": "Are you sure you want to delete this team?",
❤️

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.users.userPermissions": "User permissions",
This one doesn't seem sorted correctly by alphanum

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
> +            <ConfirmCancelDialogComponent
You should use the `ConfirmCancelModal` from bluesquare-components. It's not blocking but it's worth spinning a ticket out of this and do it in the next sprint or something

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
> +    const titleMessage = formatTitle(dialogType, formatMessage);
I think you could spare the function by just declaring:
```javascript
const titleMessage = dialogType === "create" ? formatMessage(MESSAGES.createUserRole) : formatMessage(MESSAGES.editUserRole)
```

and passing a default value of `"create"` to the `dialogType` prop (line 59)

Again, not blocking, just style stuff

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
> +    const titleMessage = formatTitle(dialogType, formatMessage);
Also, you haven't made `dialogType` optional, so according to the TS typing, you don't need to care about the case where `dialogType` is undefined 😉

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
> +    } = formik;
you can group that in a single statement

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +};
You have 4 occurences of the type `Permission` in the codebase. They should be grouped in a single type and imported. If you need to differentiate between `Permission`with or without `codename`you can either make it optional:

```javascript
type Permission = {
    id: number;
    name: string;
    codename?: string;
};
```

or make a separate sub type:

```javascript
type PermissionShort = Omit<Permission, "codename">
```

In general reused types should be saved in a file at app or domain level

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +};
cf Permission type

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +    );
please pass the arguments using object notation, it makes it easier to read for others

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +        handleChange(newUserPerms);
this should be in a useCallback

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +    const permissions = data?.permissions ?? [];
like @beygorghor  said: this and lines 62-70 should be in a useMemo

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +    };
I prefer functions to have verb names like `getPermissionLabel`or `makePermissionLabel`

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/PermissionsSwitches.tsx
> +export default PermissionsSwitches;
please use `export const PermissionSwitches` instead

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/config.tsx
> +    ];
Try wrapping this in `useMemo` since it depends on `formatMessage` and `deleteUserRole`

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/config.tsx
Way to go! 👍

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useDeleteUserRole.ts
> +        ['userRolesList'],
please use object notation for the arguments of `useSnackMutation`

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/hooks/requests/useGetUserRoles.ts
> +    });
again: object notation. It's more legible and saves you the trouble of passing `undefined`

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/validation.ts
> +    );
Using backend errors, very nice !

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/PermissionsSwitches.tsx
> +};
cf comment about duplicate types

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/config.js
> +export const userPermissionColumns = ({ formatMessage, currentUser }) => {
rename as `useUserPermissionColumns` and wrap `columns` in a `useMemo`

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserPermissions.tsx
> +};
duplicate type

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserPermissions.tsx
> +    const permissionLabel = useCallback(
please use verb in function name

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserRolesDropDown.ts
> +    );
pls use object notation

2023-06-29 12:02 UTC, quang-le commented on iaso/api/profiles.py
> +        profile.user.groups.clear()
I'm not sure this is necessary since you're in the `create `method

2023-06-29 12:02 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/hooks/useGetUserPermissions.tsx
> +            data.push(row);
I'm sorry but I'm going to block on this: this type of calculation should happen in the `userPermissionsColumns`hook (which should be renamed, see other comment), using the `Cell` property:
```javascript
  {
            Header: formatMessage(MESSAGES.userPermissions),
            id: 'userPermission',
            accessor: 'userPermission',
            sortable: false,
            Cell: settings => // your logic here
        },
```

Your method works, but since we do it using `Cell`everywhere else in the codebase, it makes your code harder to debug. Also, I think we shouldn't mix render logic with the data

2023-06-30 09:46 UTC, hakifran commented
@quang-le when you have time take a look. I've apply or the changes requests

2023-06-30 13:49 UTC, quang-le approved these changes
Great job!

2023-06-30 13:56 UTC, merged