IA-2169: org unit groups permissions
BLSQ/iaso pull request #633
Opened 2023-06-05 12:23 UTC by beygorghor

Allow access to group page only to admin or those with correct permission

Related JIRA tickets : IA-2169

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- added new permission + migration
- change menu permission of groups to `iaso_org_unit_groups`
- translate permission

## How to test

Use a test user that doesn't have the permission `iaso_org_unit_groups`
Check that he does't have access to groups page
check that he can see groups in dropdown on ohter pages

## Print screen / video

<img width="337" alt="Screenshot 2023-06-05 at 14 20 13" src="https://github.com/BLSQ/iaso/assets/12494624/11608d0e-d001-455c-a73e-45b20e4f1d74">

2023-06-08 10:17 UTC, codeKameleon approved these changes

2023-06-09 09:03 UTC, olethanh commented
The users are going to lose access to the page, should we have some kind of migration or communication with the implementations  team on how to handle the transition?

2023-06-09 10:04 UTC, quang-le requested changes
Same comment as @olethanh 

I foresee this might be problem with polio, where they use the group feature to create country blocs

We should have a definitive answer to what to do about making a migration to add the permission to some users before merging

2023-06-14 11:18 UTC, beygorghor commented
@quang-le 
![Screenshot 2023-06-14 at 13 17 48](https://github.com/BLSQ/iaso/assets/12494624/74499060-609c-47ad-80d3-b1ae00a8ec0a)

2023-06-14 11:56 UTC, merged