IA-1053: remove useless delete warning
BLSQ/iaso pull request #641
Opened 2022-02-10 11:46 UTC by quang-le

- make message optional in DeleteDialogComponent
- remove warning message from table config
- remove unused warning message in polio

2022-02-10 12:46 UTC, beygorghor requested changes

2022-02-10 12:46 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/dialogs/DeleteDialogComponent.js
> +                    {message && <FormattedMessage {...message} />}
i prefer to remove completely the dialog cotent or even the parent div

2022-02-10 15:22 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/dialogs/DeleteDialogComponent.js
> +                    {message && <FormattedMessage {...message} />}
Removing the parent div creates an error

2022-02-11 09:22 UTC, beygorghor approved these changes

2022-02-11 09:22 UTC, merged