Ia 1027 lqas/im list and form skipped because of wrong keys
BLSQ/iaso pull request #644
Opened 2022-02-11 16:33 UTC by SimonDus

I added a "skipped_forms": skipped_forms to the response which contains a count and the skipped forms. 

![image](https://user-images.githubusercontent.com/45785235/153630451-282781c2-9e65-48b4-a1c2-694f99b4349f.png)

2022-02-15 13:42 UTC, quang-le requested changes
We need it for IM as well...

2022-02-15 13:42 UTC, quang-le commented on plugins/polio/api.py
> +        skipped_forms = {"count": 0, "forms_id": skipped_forms_list}
I don't know if it would make sense to have a dictionary with the country name as key, like we did with `day_country_not_found`, since we already pass the country in the request. @madewulf, what are your thoughts on this?

2022-02-16 08:42 UTC, SimonDus commented on plugins/polio/api.py
> +        skipped_forms = {"count": 0, "forms_id": skipped_forms_list}
I added it to IM

2022-02-18 11:34 UTC, quang-le approved these changes
Very nice. This will help clean the data. Also, now we get the round data, regardless of how the various forms decide to spell "round 1" or "round 2", which means there's less empty graphs (e.g Chad).

2022-02-18 11:34 UTC, quang-le commented on plugins/polio/api.py
> +                if round_number.endswith("1") or round_number.endswith("2"):
😀

2022-02-18 11:42 UTC, merged