IA-2213 add warning for user with no perm
BLSQ/iaso pull request #647
Opened 2023-06-09 16:40 UTC by quang-le

Add a warning when creating a user ith no permissions  through the web interface that the created user will have access to the mobile app but not to the features of the web app

Related JIRA tickets : IA-2213

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [X] Is my code clear enough and well documented
- [X] Are my typescript files well typed
- [X] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Switch UsersDialog to TS
- Move logic related to the conversion of `initialData`to the format needed by the component to `useInitialData` hook
- Pass `isLoading`to Table to force refresh when updating a user
- use `isLoading` to force refresh `UsersDialog` when creating a user

The main problem was that The modal uses the old `ConfirmCancelModal` component and that converting it to the new component would have entailed rewriting the cypress tests, which would have inflated the scope of the ticket and delayed it. The current solution is a bit hacky but should make the feature available while doing a proper rewrite

## How to test

- Go to users 
- try to create a user with no permissions
- try to add permissions to that user
- try to remove all permissions from a user

## Print screen / video

https://github.com/BLSQ/iaso/assets/38907762/66e51845-05cb-4e7e-901a-ea2f36a13752

## Notes
Ticket for full modal upgrade https://bluesquare.atlassian.net/browse/IA-2238

2023-06-09 16:48 UTC, quang-le commented
@cypress

2023-06-14 10:57 UTC, beygorghor requested changes
Small remarks + see screen shot 
![Screenshot 2023-06-14 at 12 53 21](https://github.com/BLSQ/iaso/assets/12494624/3d860ba5-d443-4bb2-abbc-7522a0a8bb54)

2023-06-14 10:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.users.warningModalMessage": "You are about to save a user with no permissions. This user will have access to the mobile application but not to the features of the web interface.",
without permissions ?

2023-06-14 10:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +    renderTrigger: any;
ReactElement ?

2023-06-14 10:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +    saveProfile: any;
Promise<any>  ?

2023-06-14 10:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +                // closeDialog();
you can remove this ?

2023-06-14 10:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/WarningModal/WarningModal.tsx
> +            onClose={() => {}}
`onClose={() => undefined}` ?

2023-06-14 10:57 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/WarningModal/WarningModal.tsx
> +            onCancel={() => {}}
same

2023-06-14 12:21 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.users.warningModalMessage": "You are about to save a user with no permissions. This user will have access to the mobile application but not to the features of the web interface.",
Yeah, I wasn't sure about that one

2023-06-14 12:26 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +    saveProfile: any;
MutateFunction<Profile, any>

2023-06-14 12:29 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.users.warningModalMessage": "You are about to save a user with no permissions. This user will have access to the mobile application but not to the features of the web interface.",
I think it's OK as is

2023-06-14 13:30 UTC, beygorghor approved these changes

2023-06-14 13:33 UTC, merged