Polio 619 refactor budget front end
BLSQ/iaso pull request #65
Opened 2022-10-07 11:49 UTC by quang-le

Explain what problem this PR is resolving

## Self proof reading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] Did I add translations
- [ ] My migrations file are included
- [ ] Are there enough tests
## Changes

###  Features
- Add step button + modal has been replaced by buttons generated dynamically according to the workflow state
- The Map in Budget details has been removed to give more space to the Table, which allowed to remove the `BudgetFiles`modal in the desktop version: the files and links are shown directly in the table
- Budget Steps are not editable anymore
- The notion of deletion/restoration of events has been replaced by show/hide, which don't open a modal anymore.
- Filters by team and recipient have been removed as they don't make sense anymore in the context of the steps being constrained by the workflow.
- When adding links, users can now choose an alias, that will be displayed in the table
- Step creation  buttons can have 3 colors: "primary", "red" or "green". These are determined in the workflow

### In the code

- Data for the Budget Table is received from a single endpoint from the backend. No values are computed in the front-end (as opposed to previously where e.g. status was computed from all events for the campaign)
- All calls to `/api/polio/campaign` have been removed
- `CreateEditBudgetEvent`has been replaced with `CreateBudgetStep` and `CreateOverrideStep`
- Table and Card layouts for BudgetDetails have been split and moved to their own component
- Budget status and step names come directly from the backend and are not translated in the front-end
- Added `AddMultipleLinks` and `NamedLink`components for managing links' aliases
- Most calls to `api/profiles` have been removed since the backend handles  the necessary checks
- links are now treated as a list of objects with an `alias` and a `url`
- likewise have a `filename` that we can display in the table. 
- Step creation button colors are handled with classNames, which explains why the are constrained to predetermined values

## How to test

- Go to Polio -> Budget and play around

## Print screen / video

https://user-images.githubusercontent.com/38907762/194546197-392f87e7-2423-41b3-987d-374ca4a7fc6f.mov

## Notes

⚠️ Includes [POLIO-617](https://github.com/BLSQ/iaso/tree/POLIO-617_BWE_backend) changes (backend)
Known issues:

- Files don't seem to be saved, though POSTing returns a 200
- The show/hide step feature is not yet implemented
- Form validation is deactivated as it needs to be rewritten
- Modal fields for each step are not yet dynamic
- Required fields are not yet enforced ( cf form validation)
- Backend for override feature is not ready

2022-10-17 10:14 UTC, niconoe commented on hat/api/token_authentication.py
> +    print(final_link)
Forgotten from debugging?

2022-10-17 10:16 UTC, niconoe commented on plugins/polio/admin.py
> +            print(e)
Maybe we can catch a less broad exception, and use the logging module rather than print().

2022-10-18 09:28 UTC, beygorghor requested changes
Huuuuge job  !! :bravo:
- I have an issue while requesting a budget and leaving a second link empty 
![Screenshot 2022-10-18 at 11 22 01](https://user-images.githubusercontent.com/12494624/196391301-0410c94a-6d4f-481e-a070-58b557841c36.png)
- i'm not a huge fan of the error set by default if you touch another field, also files should be required here:

![Screenshot 2022-10-18 at 11 21 53](https://user-images.githubusercontent.com/12494624/196391305-6afe
![Screenshot 2022-10-18 at 11 23 26](https://user-images.githubusercontent.com/12494624/196391680-1ffcebca-6d4e-490a-984d-e1beb34b9383.png)
90c8-87f5-471f-85ba-19f3c04021cc.png)

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetailsFilters.tsx
> +    // const { data: teams, isFetching } = useGetTeamsDropDown();
this can be removed

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetailsTableLayout.tsx
> +    resetPageToOne,
this is not required anymore since the last changes i did on the table (normally)

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/mobile/BudgetDetailsFiltersMobile.tsx
> +    // expand,
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetFilters.tsx
> +    // const isSmLayout = useMediaQuery(theme.breakpoints.down('sm'));
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetFilters.tsx
> +                {/* <Grid item xs={12} sm={12} md={6}>
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetStatus.tsx
> +                    className={`${classes.title}`}
`className={classes.title}`

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +    //@ts-ignore
this is not necessary no ?

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +        const trimmedParams = {...params}
you have some eslint issues here

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +                        {/* @ts-ignore */}
weird

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +                        <>
you can remove this fragment

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +                        {/* @ts-ignore */}
useless

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateOverrideStep.tsx
> +                                label={MESSAGES.eventType}
this translation is missing

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateOverrideStep.tsx
> +    // const titleMessage = MESSAGES.newBudgetStep;
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateOverrideStep.tsx
> +                        <>
useless fragment

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/MultipleLinks/AddMultipleLinks.tsx
> +        // @ts-ignore
useless

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/MultipleLinks/AddMultipleLinks.tsx
> +    const links = useMemo(() => values?.links ?? [], [values?.links]);
if you type values you can remove the ignore

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/NextBudgetStep.tsx
> +const useStyles = makeStyles(styles);
`
const useStyles = makeStyles(theme => ({
    title: {
        fontWeight: 'bold',
        [theme.breakpoints.down('md')]: {
            fontSize: 18,
        },
    },
    spacer: { marginRight: '5px' },
}));
`
is fixing the error, don't ask me why

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/hooks/api/useGetBudgetDetails.ts
> +export const useGetBudgetDetails = params => {
no typing here ?

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/hooks/api/useGetStatusDropDown.ts
> +    await waitFor(1000);
Why ?

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/utils.tsx
> +    // const linksArray = links.split(',');
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/utils.tsx
> +        // const fileName = extractFileName(file) || file;
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +    // @ts-ignore
you can type a state

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +    }, [campaignId, rest, showHidden]);
transition_key is not in the deps

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +        const toDisplay = new Set(regular?.filter(transition=>transition.key!==budgetInfos?.current_state?.key).map(transition=>transition.label));
eslint where are you ?

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +    }, [budgetInfos?.next_transitions]);
budgetInfos?.current_state?.key ?

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +            {/* @ts-ignore */}
useless

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +                className={`${classes.containerFullHeightNoTabPadded}`}
`className={classes.containerFullHeightNoTabPadded}`

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +                                                                // displayedFields={step.displayed_fields}
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +                                                                        !step.allowed,
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +                                                    // displayedFields={step.displayed_fields}
to remove

2022-10-18 09:28 UTC, beygorghor commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +                                                        // tooltipText={step.reason_not_allowed}
to remove

2022-10-18 09:44 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/hooks/api/useGetStatusDropDown.ts
> +    await waitFor(1000);
Actually, it's not used anymore, I'll delete it. Leftover from when the api wasn't ready

2022-10-18 09:50 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +    //@ts-ignore
it seems my ts-linter is on drugs or something,

2022-10-18 09:51 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/CreateBudgetStep/CreateBudgetStep.tsx
> +                        {/* @ts-ignore */}
Object is possibly undefined, says tslint. I don't see how though

2022-10-18 09:59 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +    }, [budgetInfos?.next_transitions]);
my linter is letting me down these days

2022-10-18 10:01 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/BudgetDetails/BudgetDetails.tsx
> +    }, [campaignId, rest, showHidden]);
well spotted. My linter was on strike yesterday apparently

2022-10-18 10:02 UTC, quang-le commented on plugins/polio/js/src/pages/Budget/MultipleLinks/AddMultipleLinks.tsx
> +    const links = useMemo(() => values?.links ?? [], [values?.links]);
Yep, I was lazy...

2022-10-18 11:16 UTC, quang-le commented
> Huuuuge job !! 👏
> 
>     * I have an issue while requesting a budget and leaving a second link empty
>       ![Screenshot 2022-10-18 at 11 22 01](https://user-images.githubusercontent.com/12494624/196391301-0410c94a-6d4f-481e-a070-58b557841c36.png)
> 
>     * i'm not a huge fan of the error set by default if you touch another field, also files should be required here:
> 
> 
> ![Screenshot 2022-10-18 at 11 21 53](https://user-images.githubusercontent.com/12494624/196391305-6afe ![Screenshot 2022-10-18 at 11 23 26](https://user-images.githubusercontent.com/12494624/196391680-1ffcebca-6d4e-490a-984d-e1beb34b9383.png) 90c8-87f5-471f-85ba-19f3c04021cc.png)

The error I spun in another ticket, since we're deploying for demo, and not for client use. The thing with the error and required fields we can discuss, as it's one of links or files that is required, not both, so it's a bit trickier to signal to the user with our usual conventions

2022-10-18 11:25 UTC, quang-le commented
The package-lock conflict seems to be with bluesquare-components. The safest bet is probaby to update bluesquare-components on main, since resolving package-lock conflicts by hand is both tedious and error prone

2022-10-19 08:04 UTC, beygorghor approved these changes

2022-10-19 08:06 UTC, merged