IA-2245: add filename format for gpckg export
BLSQ/iaso pull request #663
Opened 2023-06-21 08:32 UTC by quang-le

when exporting org units as gpckg, the name wasn't formatted correctly

Related JIRA tickets : IA-2245

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Added the filename for gpckg export in api/org_units.py

## How to test

- Go to Org units in web UI, perform a search
- click the gpckg button
- The filename should include the environment and the account name

## Print screen / video

![Screenshot 2023-06-21 at 10 30 45](https://github.com/BLSQ/iaso/assets/38907762/13348c9c-06c8-451c-98c7-0366b1aa841a)

2023-07-03 11:07 UTC, olethanh approved these changes

2023-07-03 11:08 UTC, olethanh requested changes
It add two time the date. e.g:
`development-polio-org_units-2023-07-03-11-04-2023-07-03-11-05.gpkg`

2023-07-03 15:11 UTC, quang-le commented
> It add two time the date. e.g: `development-polio-org_units-2023-07-03-11-04-2023-07-03-11-05.gpkg`

Ugh, shame on me. Should be fixed

2023-07-04 06:59 UTC, olethanh approved these changes

2023-07-07 14:12 UTC, merged