IA-2188: users  /  projects & bulk update
BLSQ/iaso pull request #666
Opened 2023-06-21 12:00 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-2188

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-06-30 10:28 UTC, quang-le requested changes
There's a problem with the checkbox placement, as both depend on the localisation filter to be enabled:
![Screenshot 2023-06-30 at 12 26 51](https://github.com/BLSQ/iaso/assets/38907762/6cd4758c-9afe-474f-a998-a77fab1eb8c1)

Other wise works great, nothing else blocking to point out

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/messages.js
> +        defaultMessage: 'Confirm mass changes ?',
We usually use "bulk"

2023-06-30 10:28 UTC, quang-le commented on iaso/api/profiles.py
> +def get_filtered_profiles(
Shouldn't method go in the model?

2023-06-30 10:28 UTC, quang-le commented on iaso/api/profiles.py
> +    original_queryset = queryset
Isn't it like in JS? Changes to `queryset` will be reflected in `original_queryset`?

2023-06-30 10:28 UTC, quang-le commented on iaso/api/profiles.py
> +    if parent_ou and location or children_ou and location:
is it `(parent_ou) and (location) or (children) and (location)` or `(parent_ou and location) or (children_ou and location)`?

2023-06-30 10:28 UTC, quang-le commented on package.json
> +        "test": "NODE_PATH=hat/assets/js/apps mocha --exit --require ./babel-register.js --require ./hat/assets/js/test/helpers.js --require ./hat/assets/js/test/dom.js './hat/assets/js/apps/**/*.spe
what does that do?

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> -
❤️

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +            <ConfirmCancelModal
❤️

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
> +    it('triggerd callback when changing language', () => {
triggers

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/UsersInfos.spec.js
Why add an enzyme test i.o cypress test?

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/useInitialUser.ts
> -    const resetUser = useCallback(() => setUser(initialUser), [initialUser]);
Is it not necessary anymore because the new Modal resets itself onClose?

2023-06-30 10:28 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/index.tsx
> +                {multiActionPopupOpen && 'SHOW MODALE'}
What does this do?

2023-06-30 13:38 UTC, quang-le approved these changes

2023-06-30 13:57 UTC, merged

2023-07-10 08:37 UTC, mathvdh commented on iaso/api/profiles.py
> +    if parent_ou and location or children_ou and location:
If I'm correct, `and` has a higher precedence than `or` in python so it's like `(parent_ou and location) or (children_ou and location)`

2023-07-10 08:43 UTC, mathvdh commented on iaso/api/profiles.py
> +    original_queryset = queryset
@quang-le yes it is. BUT then when you use functions like `filter` or whatever on the queryset it doens't modify the original one but return the resulting queryset (if I'm not mistaken) so in this case this works.

2023-07-13 15:25 UTC, madewulf commented on iaso/api/profiles.py
> +    if parent_ou and location or children_ou and location:
This should be rewritten (parent_ou or children_ou) and location to my taste, but ok ;-)