IA-2208: [API] Create migration for feature flags
BLSQ/iaso pull request #669
Opened 2023-06-22 16:32 UTC by hakifran

Explain what problem this PR is resolving
- Create migration for feature flags
Related JIRA tickets : [IA-2208](https://bluesquare.atlassian.net/browse/IA-2208)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Add migration for creating new feature flags

## How to test

## Print screen / video

## Notes

2023-06-23 07:39 UTC, bmonjoie requested changes

2023-06-23 07:39 UTC, bmonjoie commented on iaso/migrations/0217_add_feature_flag_MOBILE_CHECK_FORMS_UPDATE.py
> +        name="Mobile: Check if the user can update a form.",
The description should be: 
> Mobile: Warn the user when forms have been updated

2023-06-23 07:39 UTC, bmonjoie commented on iaso/migrations/0218_add_feature_flag_MOBILE_CHECK_OU_UPDATE.py
> +        name="Mobile: Check if the user can update an orgUnit.",
The description should be: 
> Mobile: Warn the user when the Org Units have been updated

2023-06-23 07:39 UTC, bmonjoie commented on iaso/migrations/0219_add_feature_flag_MOBILE_FORCE_FORMS_UPDATE.py
> +        name="Mobile: Check if the user can force update a form.",
The description should be: 
> Mobile: Warn the user when forms have been updated and force them to update

2023-06-23 07:39 UTC, bmonjoie commented on iaso/migrations/0220_add_feature_flag_MOBILE_FORCE_OU_UPDATE.py
> +        name="Mobile: Check if the user can force update an orgUnit.",
The description should be: 
> Mobile: Warn the user when the Org Units have been updated and force them to update

2023-06-23 11:58 UTC, bmonjoie approved these changes

2023-06-30 08:10 UTC, olethanh commented
that look ok to me. I merged with main and pushed a merge migration to resolve conflicts.

But I'm wondering if we should not handle the case for when the feature flag already exists if they were already created manually on some of the environments

2023-07-18 12:46 UTC, merged