IA-2047 IA-2282 IA-2252 Completeness stats improvement
BLSQ/iaso pull request #684
Opened 2023-06-29 15:17 UTC by olethanh

Make planning filter work properly in the Completeness stats page, it now filter on the assigned Form and OrgUnit

Related JIRA tickets : IA-2047 IA-2282 IA-2252

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Make planning filter work properly in the Completeness stats page, it now filter on the assigned Form and OrgUnit
- fix crash when navigating hierarchy
- Seed better data for planning and completeness so we have data for testing

## How to test

Seed a iaso database via the command or create a whole planning with proper teams and assignment
Go to the completeness stat page

2023-06-29 16:56 UTC, Corona79 commented
Good work

2023-06-30 06:57 UTC, olethanh commented
forgot to mention but we now also delete the `unkown_` type after a dhis2 import if there is no orgunit with this type. This is related to the previous change in dhis2 import where we deduced the type from the orgunitlevels api in DHIS2

2023-07-14 08:03 UTC, quang-le requested changes
If you select a form and a planning not linked to that form, you get a 500:

https://github.com/BLSQ/iaso/assets/38907762/e7b2492c-d905-45cd-a598-f0792a8b4732

2023-08-07 07:56 UTC, beygorghor approved these changes

2023-08-07 07:56 UTC, merged