Polio 1071 zooomin lqas global map api
BLSQ/iaso pull request #690
Opened 2023-07-03 09:48 UTC by quang-le

Add a continental map for lqas 
Related JIRA tickets :  POLIO-1070, POLIO_1071

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-07-17 11:51 UTC, beygorghor requested changes, later dismissed
I have a small issue while trying fit to bound on the left map:

https://github.com/BLSQ/iaso/assets/12494624/fe0625c2-bf19-48e0-9783-b89ae9864539

Also i could launch the copy data store script but i have nothing in my maps

2023-07-17 11:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/hooks/useFilterState.ts
> +    setFilters: React.Dispatch<Record<string, any>>;
you can just import dispatch no ?

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/components/MapComponent/MapComponent.js
> +            /> */}
to remove ?

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/hooks/useGetGeoJson.ts
> +        () => getRequest(`/api/orgunits/?${queryString.toString()}`),
i this `toString` necessary ?

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/Map/LqasAfroMapPanesContainer.tsx
> +                    // backgroundLayer={zoominbackgroundShapes}
to remove ?

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/Map/LqasAfroMapPanesContainer.tsx
> +                    // getBackgroundLayerStyle={}
same

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/Map/LqasAfroMapWithSelector.tsx
> +            <Box mb={2} pt={2} ml={2} style={{ width: '50%' }}>
you can use `width="50%"` too here

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/hooks/useAfroMapShapes.ts
> +            selectedRound,
😮

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/hooks/useAfroMapShapes.ts
> +                if (!data) return [];
`data?.results ||  []`

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/utils.ts
> +            },
i'm sure you can make something more generic

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/utils.ts
> +    // return LQAS_DISQUALIFIED;
🗑️

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/utils.ts
> +    // );
🗑️

2023-07-17 11:51 UTC, beygorghor commented on plugins/polio/js/src/pages/LQAS/utils.ts
> +    // return [passed, failed, disqualified];
🗑️

2023-07-17 15:27 UTC, quang-le commented on hat/assets/js/apps/Iaso/hooks/useFilterState.ts
> +    setFilters: React.Dispatch<Record<string, any>>;
Yeah, but I thought it would make it clearer that it's not Redux's dispatch

2023-07-17 15:27 UTC, quang-le commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/utils.ts
> +            },
Yeah, but I don' see the point to be honest

2023-07-18 08:07 UTC, beygorghor commented
This code seems not to work properly:
` store_exists = [local_entry for local_entry in local_store if local_entry["key"] == store["key"]]`
in the `copy_data_store` script.Also you should look the `post_output.stdout` to check api response ( I had Put is not allowed)

2023-07-18 08:09 UTC, beygorghor commented
> I have a small issue while trying fit to bound on the left map:
> 
>  Screen.Recording.2023-07-17.at.13.48.43.mov 
> Also i could launch the copy data store script but i have nothing in my maps

This is solved

2023-07-18 14:23 UTC, madewulf commented on plugins/polio/models.py
> +    # To use in with sorted. returning date.min if ended_at has no value so the method can be used with `sorted`
Comment seems strange

2023-07-18 15:34 UTC, quang-le commented on plugins/polio/js/src/hooks/useGetGeoJson.ts
> +        () => getRequest(`/api/orgunits/?${queryString.toString()}`),
Yes, the variable is badly named

2023-07-18 15:39 UTC, quang-le commented on plugins/polio/js/src/pages/LQAS/LqasAfroOverview/hooks/useAfroMapShapes.ts
> +            selectedRound,
yep, lots of things can force a refetch 🤷‍♂️

2023-07-19 08:07 UTC, quang-le commented
> This code seems not to work properly: ` store_exists = [local_entry for local_entry in local_store if local_entry["key"] == store["key"]]` in the `copy_data_store` script.Also you should look the `post_output.stdout` to check api response ( I had Put is not allowed)

I created a ticket for that https://bluesquare.atlassian.net/browse/POLIO-1104?atlOrigin=eyJpIjoiOGIxNTVkYzFlNTk0NDQ4MDlkZjU5MmY1ODUxNGJmYmEiLCJwIjoiaiJ9

2023-07-19 14:39 UTC, madewulf commented on plugins/polio/api.py
> +        # TODO see if we need to filter per user as with Campaign
IS IT DONE?

2023-07-19 15:10 UTC, madewulf commented on plugins/polio/helpers.py
> +        # TODO put in an enum
IT'S NOT DONE!

2023-07-19 15:18 UTC, madewulf approved these changes

2023-07-19 15:24 UTC, merged