Fix user Cypress test and fix the partial update for a user
BLSQ/iaso pull request #692
Opened 2023-07-03 10:14 UTC by hakifran

Explain what problem this PR is resolving
- There is an error in checking a permission in cypress(Frontend)
- There is also an error while updating a user name in partial update(Backend)
Related JIRA tickets : [IA-2294](https://bluesquare.atlassian.net/browse/IA-2294)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Added user_permissions key in list.json user fixture
- Changed the get into filter on user objects in backend

## How to test
- Run cypress test on user
- Try to update a username of a user

[IA-2294]: https://bluesquare.atlassian.net/browse/IA-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-03 10:14 UTC, hakifran commented
@cypress

2023-07-03 11:55 UTC, hakifran commented
@cypress

2023-07-07 12:41 UTC, quang-le commented
cypress manual test passed https://github.com/BLSQ/iaso/actions/runs/5485691584

2023-07-17 08:11 UTC, beygorghor approved these changes

2023-07-18 11:47 UTC, beygorghor requested changes

2023-07-18 11:47 UTC, beygorghor commented on iaso/api/profiles.py
> +        existing_user = User.objects.filter(username__iexact=username).filter(~Q(pk=user.id))
In fact, i discover now that if you update the username in the same request it crashes the api, we should find a better way to find existing user

2023-07-18 14:28 UTC, beygorghor approved these changes

2023-07-18 14:29 UTC, merged