POLIO-1084: Polio calendar export show wrong vaccines
BLSQ/iaso pull request #699
Opened 2023-07-06 08:34 UTC by hakifran

Explain what problem this PR is resolving
- Polio calendar export show wrong vaccines
Related JIRA tickets : [POLIO-1084](https://bluesquare.atlassian.net/browse/POLIO-1084)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Filter on campaigns which has scopes

## How to test
- Go to the campaign calendar
- Export to xlsx

2023-07-06 09:17 UTC, quang-le commented
I added the missing FR keys and asked Rita to double check the PT

2023-07-07 10:13 UTC, hakifran commented
@cypress

2023-07-07 10:59 UTC, quang-le requested changes
It doesn't work when you have separate scopes per round. See comment for possible solution.

I think you also need to update your tests to cover this case
https://github.com/BLSQ/iaso/assets/38907762/27fe1d79-adee-4d5c-8e88-6f7dae2589fb

2023-07-07 10:59 UTC, quang-le commented on plugins/polio/api.py
> +        vaccines = campaign.vaccines
this is incorrect when we have separate scopes per round.

You need to check if `separate_scope_per_round` is `True` for the campaign. If it's the case, you need to get the vaccines for the round. If not , you can use the campaign vaccines like you do here

We have this PR https://github.com/BLSQ/iaso/pull/683 that has been merged recently and allows you to use `Round.vaccine_names` to get the vaccines associated with round-level scopes

2023-07-10 16:06 UTC, quang-le approved these changes
top!

2023-07-11 13:20 UTC, madewulf approved these changes

2023-07-11 13:20 UTC, merged