IA-2291: Need a read only permission on top of the existing one for accessing the pages
BLSQ/iaso pull request #706
Opened 2023-07-10 15:20 UTC by hakifran

Explain what problem this PR is resolving
- Don't allow everyone to update or delete a page
Related JIRA tickets : [IA-2291](https://bluesquare.atlassian.net/browse/IA-2291)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Added a menupermissions 'iaso_page_write'
- Check if the current user has permissions to delete or to edit page

## How to test
- Create a new user(not an admin one) add all permissions except **edit page** permission
- Login with the user
- Check if the delete and edit icon on pages list is there or not. They should not appear

## Print screen / video
![Peek 2023-07-10 17-18](https://github.com/BLSQ/iaso/assets/19631540/b401b518-55a4-4ec6-bfaa-e849244ef985)

2023-07-11 07:19 UTC, SimonDus requested changes
Seems ok but maybe add a unit test to it ?

2023-08-07 16:57 UTC, mathvdh commented
@hakifran once the tests pass I can accept it ..

2023-08-07 17:04 UTC, hakifran commented
> @hakifran once the tests pass I can accept it ..

@mathvdh tests are already there, you can check in this file iaso/tests/api/test_pages.py

2023-08-07 18:57 UTC, mathvdh commented
@hakifran yes I have seen but last time I looked the tests were not passing in github actions

2023-08-07 18:58 UTC, mathvdh approved these changes
Ok for me on the backend side ! Good job

2023-08-08 07:48 UTC, beygorghor requested changes

2023-08-08 07:48 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/pages/index.js
> +                                'iaso_page_write',
Since Benjamin's PR has been merged you should use constant from `hat/assets/js/apps/Iaso/utils/permissions.ts`

2023-08-08 10:11 UTC, beygorghor approved these changes

2023-08-08 10:12 UTC, merged