IA-2322 user roles fixes front
BLSQ/iaso pull request #720
Opened 2023-07-18 12:33 UTC by beygorghor

Multiple fixes for user roles management

Related JIRA tickets : IA-2316, IA-2317, IA-2318, IA-2319, Ia-2320

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

## How to test

## Print screen / video

https://github.com/BLSQ/iaso/assets/12494624/493af717-e5da-4a73-8d6d-b32c79874a5f

https://github.com/BLSQ/iaso/assets/12494624/b02e68aa-a055-474e-a82b-4b910ca76cd7

2023-07-18 12:56 UTC, beygorghor commented
@cypress

2023-07-18 15:01 UTC, quang-le approved these changes

2023-07-18 15:01 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/userRoles/components/CreateEditUserRole.tsx
> +                            setUserRolePermissoins([]);
Permissoins ??😂

2023-07-18 15:01 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +                    >
I don't understand this change, but why not. It should be extended to the locations as well then. Nothing  blocking

2023-07-18 15:05 UTC, quang-le requested changes
When I create a new user and add a user role, the permissions are not switched:
https://github.com/BLSQ/iaso/assets/38907762/4f6c168e-6e64-4b60-8abd-bca167821f7c

2023-07-18 15:24 UTC, quang-le approved these changes

2023-07-18 15:29 UTC, beygorghor commented
> When I create a new user and add a user role, the permissions are not switched: https://github.com/BLSQ/iaso/assets/38907762/4f6c168e-6e64-4b60-8abd-bca167821f7c

this is fixed already

2023-07-18 15:32 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/users/components/UsersDialog.tsx
> +                    >
simply avoiding the tab to reload on user intiial state, but i don't think it's necessary anymore

2023-07-19 08:28 UTC, hakifran approved these changes
Good.

2023-07-19 12:23 UTC, merged