Ia 2327 permission iaso submissions should allow the user to see the submission
BLSQ/iaso pull request #730
Opened 2023-07-20 15:49 UTC by hakifran

Explain what problem this PR is resolving
- Before a user who had iaso_permissions without the iaso_update_permission could not see a submission
Related JIRA tickets : [IA-2327](https://bluesquare.atlassian.net/browse/IA-2327)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Check if the connected user has one of the two permissions["iaso_submissions", "iaso_update_submission"] and display the Actions columns
- Check if connected user has iaso_update_submission in every link on button to update the submission, if the user has not the update submission permission those links and button won't appear.

## How to test
- Connect with a user who has not update submission permission
- Access to the submissions list
- It will be possible to see submission's details(eye icon)

## Print screen / video
![Screenshot from 2023-07-20 17-47-13](https://github.com/BLSQ/iaso/assets/19631540/14ec380f-c3eb-4722-9bfb-5af624e30354)

[IA-2327]: https://bluesquare.atlassian.net/browse/IA-2327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-20 15:49 UTC, hakifran commented
@cypress

2023-07-24 09:30 UTC, beygorghor requested changes

2023-07-24 09:30 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.instances.modificationDateTo": "Modification date to",
Those translations are missing in french

2023-07-27 10:18 UTC, beygorghor approved these changes

2023-07-31 11:20 UTC, merged