IA-2043: Create a new permission - limit data sources access to view only
BLSQ/iaso pull request #736
Opened 2023-07-27 16:58 UTC by hakifran

Explain what problem this PR is resolving
- Before every user has access to read and write data source permissions
- The changes will allow to restrict some user to read only permissions

Related JIRA tickets : [IA-2043](https://bluesquare.atlassian.net/browse/IA-2043)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Added iaso_write_sources permission
- Added a button to see data source details
- Created a page to display data source details
- Let some user to be able to edit a data source and other to only read the data source details

## How to test
- Create or edit users add iaso_write_sources permissions and for other remove it
- Go to data source list
- Check which operations accessible to a user

## Print screen / video
![Peek 2023-07-27 18-57](https://github.com/BLSQ/iaso/assets/19631540/725000d9-23ac-410d-8507-4e8a29f2a2b4)

2023-08-07 16:40 UTC, mathvdh approved these changes
Seems fine for me on the backend side

2023-08-08 09:48 UTC, mathvdh approved these changes

2023-08-08 09:51 UTC, beygorghor requested changes
@hakifran just remove double use of same hook please !

2023-08-08 09:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/dataSources/components/DataSourceInfo.tsx
> +                    <>
you can remove this fragment

2023-08-08 09:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/dataSources/details.tsx
> +    const intl = useSafeIntl();
❗️ you are using twice the same hook here

2023-08-08 09:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/dataSources/hooks/useGetDataSources.ts
> +            staleTime: Infinity,
This means it will never refetch data until we reload the page or invalidate it. We are using a real value on other calls, maybe use the same

2023-08-08 09:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/dataSources/index.js
>      const intl = useSafeIntl();
const {formatMessage} = useSafeIntl()

2023-08-08 09:51 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/dataSources/utils.js
Good point of get those methods out of the component 👍 
Next time you can use typescript to make it more robust !

2023-08-08 10:51 UTC, beygorghor approved these changes

2023-08-08 11:06 UTC, merged