IaA0591 fix marking data source version as default
BLSQ/iaso pull request #74
Opened 2022-10-18 09:30 UTC by olethanh

The default version for an account couldn't be changed anymore.

I trace this regression back to :
https://github.com/BLSQ/iaso/commit/75a780e0690c45e4fdba9432200cf86c9050cc6a

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are there enough tests 
## Changes

Fixed the bug by removing the bugging and unused field from the Account Serializer.
Added a log of test around this API endpoint since there wasn't any

## How to test
- On the Web, go on the data source page.
- Open a data source dialog. Mark a version as default if there is none already
- Then check the Default data source checkbox
- Save.

What happened before :
There is one success snackbar and one error one : Respectively the  save on data source edit but the mark as default fail

What should happen now :
 Both request succeed and the source is the new default for the account

In general check there is no regression with the account feature

2022-10-20 10:59 UTC, beygorghor approved these changes

2022-10-21 06:59 UTC, niconoe requested changes
Thanks a lot, @olethanh! It's great that you took some time to increase the test coverage, too. My only (minr) remark is that for some test methods, the docstring says "should result in a 403", while the code actually checks for status 405. Can you clarify? thanks!

2022-10-21 08:17 UTC, olethanh commented
@niconoe You are right, corrected it

2022-10-21 10:05 UTC, niconoe approved these changes
Brilliant, thanks!

2022-10-24 08:44 UTC, merged