Polio 1141 refresh dashboard api
BLSQ/iaso pull request #763
Opened 2023-08-23 17:10 UTC by quang-le

refreshing prepâredness data from the Ui doesn't update the endpoint used for the powerBi dashboards

Related JIRA tickets :  POLIO-1141

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [X] Is my code clear enough and well documented
- [X] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [X] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Add endpoint to launch `refresh_data` and pass it an `obr_name` (to avoid refreshing all campaigns, which takes about an hour)
- Update front-end code to post on new endpoint when clicking "refresh" button.

## How to test

- Start a worker (see README for the command)
- Go to polio
- Find or create a campaign wit at least 1 round in the future
- Select campaign go to preparedness tab
- Select the future round and click "generate spreadsheet"
- Open the sheet in a new tab. Fill in some values
- Go back to polio,  and click "Refresh preparedness data"
- When the data has finished refreshing, go to Tasks
- You should see a `refresh_data` task with a timestamp matchiing your refresh (see video)

You can also open the browser inspector and check that a call to `tasks/create/refreshpreparedness` is made when you click "Refresh preparedness data".

## Print screen / video

https://github.com/BLSQ/iaso/assets/38907762/b068481d-a429-401b-8217-155fd4f38d14

2023-08-24 10:53 UTC, beygorghor approved these changes

2023-08-29 09:20 UTC, mathvdh requested changes
Except for my minor comment, It's a great job!
Also, I was wondering if we shouldn't rate-limit this endpoint @quang-le as it's launching a task in the background. Or at least maybe check if an existing task is not running already for this obr_name ? (Not sure how long the task take in background..)

2023-08-29 09:20 UTC, mathvdh commented on plugins/polio/tasks/api/create_refresh_preparedness_data.py
> +logger = logging.getLogger(__name__)
You don't seem to be using it ...

2023-08-29 09:21 UTC, mathvdh commented on plugins/polio/tasks/api/create_refresh_preparedness_data.py
> +logger = logging.getLogger(__name__)
I mean the "logger"

2023-08-29 13:38 UTC, quang-le commented
> Except for my minor comment, It's a great job! Also, I was wondering if we shouldn't rate-limit this endpoint @quang-le as it's launching a task in the background. Or at least maybe check if an existing task is not running already for this obr_name ? (Not sure how long the task take in background..)

The task is very short when you only run it for one round:
![Screenshot 2023-08-29 at 15 36 04](https://github.com/BLSQ/iaso/assets/38907762/93487ec6-c02f-4d9d-ba16-d61830a7a7d1)

Also the button is deactivated while refreshing the data, so multiple clicks should not happen (the other query takes longer than the task):

https://github.com/BLSQ/iaso/assets/38907762/5a77b169-f8f9-410b-bfa8-e7bb3bf06527

2023-08-29 13:51 UTC, mathvdh approved these changes

2023-08-29 13:51 UTC, merged