Polio-1129 vaccine auth front end
BLSQ/iaso pull request #766
Opened 2023-08-25 16:59 UTC by quang-le

Explain what problem this PR is resolving

Related JIRA tickets : POLIO-1129

## Self proofreading checklist

- [X] Did I use eslint and black formatters
- [X] Is my code clear enough and well documented
- [X] Are my typescript files well typed
- [X] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Add pages for nOPV2 Authorisation: list, details + create/edit modals
- Modal has a validation that prevents setting a date in the future if status is EXPIRED
- There's an ugly redirection with `useEffect` to add the `order`, pageSize` and `page` params when they're missiing. Couldn't use the 'redirections' of vanilla iaso, so 🤷‍♂️

## How to test

- Go to polio > vaccine module > nOPV2 Authorisations
- Check the table and filters
- Click on a row to go to details view (per country)
- Try adding, editing and deleting an authorisation

⚠️ This PR merges into  https://github.com/BLSQ/iaso/pull/751, which will fix the block of countries filter, and the table sorting⚠️

## Print screen / video

https://github.com/BLSQ/iaso/assets/38907762/5419adc9-356d-41c4-bb06-754f2a407407

2023-08-31 10:09 UTC, beygorghor requested changes
Some minor remarks, but i could not test the front locally
I don't have vaccination module in my DB and the admin is not loading correctly to add it manualy. Am I missing something ?

2023-08-31 10:09 UTC, beygorghor commented on hat/assets/js/apps/Iaso/utils/requests.js
> +};
❤️

2023-08-31 10:09 UTC, beygorghor commented on plugins/polio/api.py
> +            or request.method == "DELETE"
i'm wondering if we are using other methods

2023-08-31 10:09 UTC, beygorghor commented on plugins/polio/js/src/pages/VaccineModule/Nopv2Authorisations/Table/Nopv2AuthorisationsTable.tsx
> +    // Waiting for backend API fix to uncomment
?

2023-08-31 10:09 UTC, beygorghor commented on plugins/polio/js/src/pages/VaccineModule/Nopv2Authorisations/hooks/api.ts
> +const createEditNopv2Authorisation = body => {
no typings for this ?

2023-08-31 10:09 UTC, beygorghor commented on plugins/polio/js/src/pages/VaccineModule/Nopv2Authorisations/hooks/statuses.ts
> +                label: formatMessage(MESSAGES[status]),
better return the key if the backend return unknown status no ?

2023-08-31 10:09 UTC, beygorghor commented on plugins/polio/js/src/pages/VaccineModule/Nopv2Authorisations/hooks/validation.ts
> +            }
for this, you are using local time with a date saved in DB, are you sure this is going to work while the DB date has been saved in an other time zone ?

2023-09-01 07:56 UTC, quang-le commented on plugins/polio/api.py
> +            or request.method == "DELETE"
ping @SimonDus

2023-09-01 07:57 UTC, quang-le commented on plugins/polio/api.py
> +            or request.method == "DELETE"
But my stance would be: we'll add other methods when we need them

2023-09-01 08:20 UTC, quang-le commented on plugins/polio/js/src/pages/VaccineModule/Nopv2Authorisations/hooks/statuses.ts
> +                label: formatMessage(MESSAGES[status]),
I don't know, we don't fetch the statuses from the backend so, it will not really be dynamic anyway

2023-09-01 08:47 UTC, quang-le commented on plugins/polio/js/src/pages/VaccineModule/Nopv2Authorisations/hooks/validation.ts
> +            }
We only compare dates from the browser so I think it's fine

2023-09-01 09:32 UTC, merged