IA-2239: improve setup
BLSQ/iaso pull request #770
Opened 2023-08-29 09:50 UTC by beygorghor

Currently, if you setup an admin account on iaso, you will get this as homepage

The next step is to connect to /api/setupaccount/ and setup your first account. 

We should replace the content of the page above by a form with the same content as `/api/setupaccount/` and a logout button that allows to switch to the newly created account when it’s done. 

This account setup should also automatically create:
- a data source
- a project
Also only superuser or staff user without `iaso_profile` should be able to see account setup page

Related JIRA tickets : IA-2239

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Allow user without `iaso_profile` to access the react application (routes, redirections, ...)
- new domain for setup 
- setup page with 3 different views: 
     1. Not admin (superuser or staff)
     2. Admin view with account setup form
     3. Success message         
- added logout button to topbar
- allow user to switch the language without `iaso_profile`
- change api validation message in order to display translated message in the front
- update bluesquare-component to use the correct icon on password field

## How to test

Create three users without `iaso_profile`: staff, superuser and a normal one
Access to the dashboard with those profiles.
Normal user should only see a message saying you should contact an admin
Both staff and superuser should be able to create an account and see the success message
Try also to switch the language.
Try to create an account or a user with an already existing account name or user name.

## Print screen / video
<img width="1680" alt="Screenshot 2023-08-29 at 11 17 33" src="https://github.com/BLSQ/iaso/assets/12494624/43ff8854-7757-4139-bada-10543ac82f9a">

<img width="1673" alt="Screenshot 2023-08-29 at 11 18 19" src="https://github.com/BLSQ/iaso/
<img width="1674" alt="Screenshot 2023-08-29 at 11 16 42" src="https://github.com/BLSQ/iaso/assets/12494624/5c2dee3e-1060-4364-b4db-6a748a000bc3">
assets/12494624/bdcb58a9-2e30-4042-afa9-8be8e6a7a664">

<img width="1679" alt="Screenshot 2023-08-29 at 11 17 45" src="https://github.com/BLSQ/iaso/assets/12494624/294484e1-8e66-49d2-bb9f-b1cfead4d18c">

2023-09-07 11:10 UTC, mathvdh approved these changes
Backend-wise this seems OK to me

2023-09-12 10:15 UTC, quang-le requested changes
Some minor improvements and typos in the French translations. otherwise nothing blocking front-end side. 

I get a 403 for a super user that has not staff status. I don't know if that's the expected behaviour

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/index.js
> +        [plugins, hasNoAccount],
Not blocking, but this could be in a hook (as well as the code of `getBaseRoutes` above)

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.setup.accountSetup": "Configuration de compte",
Configuration DU compte

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/en.json
> +    "iaso.setup.accountNameAlreadyExist": "Account name already exists",
This account name is already taken

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.setup.accountNameAlreadyExist": "Le nom du compte existe déjà",
Un compte avec ce nom existe déjà

Il y a déjà un compte avec ce nom 

Ce nom n'est pas disponible

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
>      "iaso.runs.dialog.deleteRunTitle": "Etes-vous certain de vouloir effacer cet exécution d'algorithme ?",
Êtes-vous certain de vouloir effacer cette exécution d'algorithme

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.setup.dataSourceNameAlreadyExist": "Le nom de la source de données existe déjà",
Il y a déjà une source... cf account name

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
> +    "iaso.setup.notAdmin": "L'utilisateur \"{displayName}\" n'a pas de compte et de profile.",
L'utilisateur \"{displayName}\" n'a pas de compte et ni de profil.

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/setup/validation.ts
> +    );
❤️

2023-09-12 10:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/routing/redirections.tsx
> +    // eslint-disable-next-line no-unused-vars
es-lint can't handle currying, how annoying

2023-09-13 13:51 UTC, quang-le approved these changes

2023-09-13 13:52 UTC, merged