IA-2410 Add a `Project` filter on forms page
BLSQ/iaso pull request #788
Opened 2023-09-05 15:02 UTC by kemar

Add a `Project` filter on forms page.

Related JIRA tickets : [IA-2410](https://bluesquare.atlassian.net/browse/IA-2410)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] Are there enough tests

## Changes

- front-end
    - add a new multi select input to filter by `projects`
    - small UI revamp to realign buttons
- back-end
    - filter queryset by `projects` in `FormsViewSet` when required

## How to test

N/A

## Print screen / video

![ui](https://github.com/BLSQ/iaso/assets/281139/01b8545b-dd0f-4244-8fe0-a801d2d72336)

## Notes

N/A

2023-09-06 09:17 UTC, quang-le requested changes
Looks good to me code-wise. 

I would move the checkbox back under the "Search"  input field though.

2023-09-06 11:59 UTC, kemar commented
> I would move the checkbox back under the "Search" input field though.

@quang-le is there a reason for that? Because it looks to always appear along with the buttons elsewhere. See the following screenshots:

![a](https://github.com/BLSQ/iaso/assets/281139/8883cb17-1329-4d08-a701-b0ca1b8576d2)

---

![b](https://github.com/BLSQ/iaso/assets/281139/762190fd-f655-4b21-8a10-a332c9164baf)

---

![c](https://github.com/BLSQ/iaso/assets/281139/6c4913ed-9c95-4c20-a958-c461f4f3b2d5)

2023-09-06 15:31 UTC, kemar commented
> I would move the checkbox back under the "Search" input field though.

Done https://github.com/BLSQ/iaso/pull/788/commits/609532cd0f9e5f78513c36da10d1c7a6a5848b2f

2023-09-07 08:19 UTC, quang-le approved these changes

2023-09-07 08:20 UTC, merged