POLIO-1211 add Authorization start date
BLSQ/iaso pull request #837
Opened 2023-09-27 16:12 UTC by SimonDus

New field on VaccineAuthorization model.

Related JIRA tickets : POLIO-1211

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Add a New field starting date to vaccine authorization

## How to test

Check the tables in vacc auth and details, the field should be there. Create/edit n authorisation and the new required field must be in the modal

## Print screen / video

https://github.com/BLSQ/iaso/assets/45785235/cd0df7de-6648-4d7d-8c5f-d3b8684b2e0a

2023-09-28 13:54 UTC, hakifran requested changes
@SimonDus while testing I saw that we can add next expiration date which is inferior to start date. For example : 
![Screenshot-from-2023-09-28-15-49-14](https://github.com/BLSQ/iaso/assets/19631540/fb6eca24-f65a-42db-9baf-bbd250fd8c8e). Is it the way it should work?

2023-09-28 13:54 UTC, hakifran commented on plugins/polio/js/src/constants/messages.js
> +        defaultMessage: 'Starting Date',
I checked in the whole code and most of the time it's translated into "Start Date" instead of "Starting Date". @beygorghor can confirm.

2023-09-28 13:54 UTC, hakifran commented on plugins/polio/js/src/constants/translations/en.json
> +    "iaso.polio.label.vaccineAuthStartingDate": "Starting date",
Same as the above comment

2023-09-28 13:54 UTC, hakifran commented on plugins/polio/js/src/constants/translations/fr.json
> +    "iaso.polio.table.label.vaccineAuthStartingDate": "Date de début",
This is not translated in en.json and there is no id and default message defined for this. I think is the cause of the js test failure

2023-09-28 14:17 UTC, SimonDus commented on plugins/polio/js/src/constants/messages.js
> +        defaultMessage: 'Starting Date',
Variable are named start_date but the text is Starting Date. Is that what you mean ?

2023-09-28 14:19 UTC, SimonDus commented on plugins/polio/js/src/constants/translations/fr.json
> +    "iaso.polio.table.label.vaccineAuthStartingDate": "Date de début",
It is

2023-09-28 14:22 UTC, hakifran commented on plugins/polio/js/src/constants/messages.js
> +        defaultMessage: 'Starting Date',
No it's not what I mean, you can check in the code every where they use start date, they use the same translation in english "Start Date".
![Screenshot from 2023-09-28 16-21-47](https://github.com/BLSQ/iaso/assets/19631540/59048cf9-2a8c-424e-b8f4-b01eaf6f3414)

2023-09-28 14:23 UTC, hakifran commented on plugins/polio/js/src/constants/translations/fr.json
> +    "iaso.polio.table.label.vaccineAuthStartingDate": "Date de début",
@SimonDus this has been fixed. it's okay now it's translated in en.json too

2023-09-29 08:07 UTC, hakifran requested changes

2023-09-29 08:07 UTC, hakifran commented on plugins/polio/js/src/domains/VaccineModule/Nopv2Authorisations/hooks/validation.ts
> +            .checkDateForStart(MESSAGES.invalidDate),
You passed the wrong parameter. I fixed it for you

2023-09-29 08:07 UTC, hakifran commented on plugins/polio/js/src/domains/VaccineModule/Nopv2Authorisations/hooks/validation.ts
> +    function checkDateForStart(formatMessage) {
Is it possible to make one Method that can do both checkDateForStart and checkDateForExpired to avoid to repeat the same code twice. thank you

2023-09-29 08:07 UTC, hakifran commented on plugins/polio/js/src/constants/messages.js
> +        defaultMessage: 'Start date must be anterior to Expiration date',
The capital letter in the middle of the phrase should be removed.

2023-09-29 08:07 UTC, hakifran commented on plugins/polio/js/src/constants/translations/en.json
> +    "iaso.polio.error.startDateAfterExpiration": "Start date must be anterior to Expiration date",
Same here

2023-09-29 08:07 UTC, hakifran commented on plugins/polio/js/src/constants/translations/en.json
> +    "iaso.polio.label.vaccineAuthStartDate": "Starting date",
Starting date <=> Start date

2023-10-04 08:10 UTC, hakifran approved these changes
good for me.

2023-10-04 08:22 UTC, merged