IA-2454 iaso landing page
BLSQ/iaso pull request #839
Opened 2023-09-28 09:12 UTC by beygorghor

Providing a default home page for IASO

Related JIRA tickets : IA-2454
## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- make a view "home_iaso" available while not connected
- create a new home domain with a default page to display (using custom logo and App label"
- default page displays burger menu or login button if the user is authenticated or not
- allow to override home page in the plugin config
- redirect to the user home url if the user have one in his profile (only on first load)
- add a link to home on the sidebar menu
- add infot tooltip on home page input while editing a profile

## How to test

- make sure your profile doesn't have a home page 
- visit "http://localhost:8081/" while connected, you should see the home page with the sidebar menu
- visit it not connected again, you should see the home page with a login button
- eventually change logo and label of the app with ENV variables:
```
APP_TITLE="Coda 2"
FAVICON_PATH="images/coda/favicon.png"
LOGO_PATH="images/coda/logo.svg"
```
- uncomment line 540 in plugins/polio/js/config.js, revisit "http://localhost:8081/", you should see a single text saying "HOME POLIO"
- add "forms/list" has home page in your profile, revisit "http://localhost:8081/", you should **not** see home page at all and be redirect to the list of forms. Home page should be accessible if you click on the iaso logo in the sidebar menu

## Print screen / video
![Screenshot 2023-09-28 at 10 59 20](https://github.com/BLSQ/iaso/assets/12494624/beac8549-e137-455f-88eb-29ef5cd4ee72)
![Screenshot 2023-09-28 at 10 59 11](https://github.com/BLSQ/iaso/assets/12494624/2fa84b35-e7f6-4cef-a727-a6530eb87487)
![Screenshot 2023-09-28 at 10 58 59](https://github.com/BLSQ/iaso/assets/12494624/0bc62da3-d62d-410a-bc78-08d04efb9e79)

2023-10-05 11:06 UTC, quang-le requested changes
I personally don't like the flow where you login and land on a "useless page". Also it's not so clear to me that I'm actually logged in as I see the exact same page, just without the button.
I think having a default landing page by default per account was a good feature. Polio users would land on Campaigns by default, without any additional setup. Now it's either one more click away, or requires a manual setup step.

I think we shouldn't use `APP_TITLE`. the way it's currently setup, it wouldn't work well for polio. 

Sorry if it comes out a bit harsh. I think the feature fits well for vanilla iaso, but it needs some tweaking for specific cases like polio

We should also be able to change the description message: "Geo microplanning and monitoring for data collection" doesn't really describe what the polio does.
https://github.com/BLSQ/iaso/assets/38907762/606b4405-ee92-49b4-b6eb-b18d5a20679d

2023-10-05 11:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/index.js
> +    // const dispatch = useDispatch();
🗑

2023-10-05 11:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/index.js
> +import Home from '../home/index.tsx';
Please use named export

2023-10-05 11:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/home/hooks/useGetCurrentUser.ts
I like this one, It could replace `useCurrentUser` in the long run.
If we don't want to refetch everytime, we could store it in a `Context`, then we'd have feature parity with the current redux implementation

2023-10-05 11:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/images/images.d.ts
This file is empty, is it normal?

2023-10-05 11:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/routing/redirections.tsx
> +    userHomePage?: string,
So this replaces the `overrideLanding` feature if i get it right?

2023-10-05 11:06 UTC, quang-le commented on hat/assets/js/apps/Iaso/routing/redirections.tsx
> +                userHomePage && userHomePage !== ''
do you need both checks?
It seems to me that if `userHomePage === ''`,  then it will be falsy. Maybe I'm missing an edge case or something

2023-10-05 11:06 UTC, quang-le commented on plugins/polio/js/config.js
> +    // homeComponent: () => <div>HOME POLIO</div>,
Unless I missed something, it seems to me that polio users are not redirected to the Campaigns page by default. That would be a problem.

2023-10-18 09:32 UTC, beygorghor commented
PR update:
- Split home into home offline and home online
- In order to see Online home you need to set the correct feature flag on the account
By default it will use Iaso Landing page, you can overwrite it in a plugin config using `homeOnline`
- to see Offline page set homeOnline in a plugin config
- by default it will display login page if not connected and no offline page
- if connected and no account landing is setup page
- if connected and no `homeUrl` is set in a plugin config, it will display forms list as landing
- if connected and `homeUrl` is set in a plugin config, it will display the homeUrl as landing
- if connected and `homeUrl` is set in a plugin config but user sets a custom home url in his profile, it will display the custom home as landing

2023-10-19 11:15 UTC, quang-le approved these changes
Great feature, I really like the use of hooks, it makes everything very easy to understand.

Some nitpicking, but nothing blocking

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/hooks/useRoutes.tsx
> +        },
I think this is not needed

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/hooks/useRoutes.tsx
> +                const renderProtectedComponent = props => (
nitpick: this a FunctionComponent, so you could name it `ProtectedComponent`. I think it would be clearer

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/hooks/useRoutes.tsx
> +                const { allowAnonymous = false, component } = routeConfig;
See my other comment, but  `const { allowAnonymous = false, component:Component } = routeConfig;` would allow 

```javascript
                const page =
                    allowAnonymous || hasNoAccount
                        ? Component
                        : ProtectedComponent;
```

on line 150-153

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/hooks/useRoutes.tsx
> +                const { allowAnonymous = false, component } = routeConfig;
nitpicking, really

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/app/hooks/useRoutes.tsx
> +    const pluginRoutes = usePluginsRoutes();
❤️

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/home/hooks/useHomeButtons.tsx
> +                userHasOneOfPermissions(button.permissions, currentUser),
I have the feeling users will ask to be able to configure the widgets they see, browser-style.

The annoying part is it's just different enough from the menu.tsx entries that you can't just re-use them and generate that dynamically without some annoying refactoring

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/routing/useRedirections.tsx
> +const getPaginationParams = (order = 'id', pageSize = 20) =>
don't we have something like that in table utils? If not it would be better there I think

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/routing/useRedirections.tsx
> +];
This I would put in a constants file in the setup domain. But I really mind if it stays here

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/routing/useRedirections.tsx
> +) => ReactElement[] = (
maybe make a custom type for legibility

2023-10-19 11:15 UTC, quang-le commented on hat/assets/js/apps/Iaso/utils/featureFlags.js
We should really have an endpoint that sends us all feature flags with their translations

2023-10-20 10:26 UTC, merged