POLIO-1145 Vaccine Supply Chain Backend
BLSQ/iaso pull request #860
Opened 2023-10-12 13:12 UTC by mathvdh

Backend for Polio's Vaccine Supply Chain 

Related JIRA tickets : POLIO-1145, POLIO-1144

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Remove the old Vaccine Management Tab (in the Campaigns modal window).
Rest is WIP

## How to test

WIP

2023-11-30 17:08 UTC, kemar reviewed
Only surface comments and suggestions at the moment.

Review still in progress (because it's big).
I'll continue next week with the business logic.

2023-11-30 17:08 UTC, kemar commented on plugins/polio/admin.py
> +class VaccineRequestFormForm(forms.ModelForm):
```suggestion
class VaccineRequestAdminForm(forms.ModelForm):
```

2023-11-30 17:08 UTC, kemar commented on plugins/polio/admin.py
> +admin.site.register(Round, RoundAdmin)
The [register decorator](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#the-register-decorator) allows to keep things closer:

```django
@admin.register(Round)
class RoundAdmin(admin.ModelAdmin):
```

2023-11-30 17:08 UTC, kemar commented on plugins/polio/migrations/0155_merge_20231124_1047.py
> +    operations = []
Migration files could be merged in one altogether.

2023-11-30 17:08 UTC, kemar commented on iaso/api/common.py
> +        if request.method == "GET":
Do we want `HEAD` and `OPTIONS` to be forbidden?

Otherwise [this could allow](https://github.com/encode/django-rest-framework/blob/0abb84fa3955956fc6156cc2c51222cd4ceae783/rest_framework/permissions.py#L8C17-L8C41) `GET` + `HEAD` + `OPTIONS`:

```suggestion
        if request.method in permissions.SAFE_METHODS:
```

We could have `can_read` and `can_write`.

2023-11-30 17:08 UTC, kemar commented on plugins/polio/api/campaigns/campaigns.py
> +                # "destructions",
Comments could be deleted (here and at other places below).

2023-11-30 17:08 UTC, kemar commented on plugins/polio/models.py
> +        return DOSES_PER_VIAL[self.request_form.vaccine_type]
Shouldn't this be a method of `VaccineRequestForm`?

2023-11-30 17:08 UTC, kemar commented on plugins/polio/tests/test_vaccine_supply_chain.py
> +        print(res["arrival_reports"])
You could probably remove those `print` statements.

2023-11-30 17:08 UTC, kemar commented on plugins/polio/api/vaccines/supply_chain.py
> +                print(pre_alert.errors)
You could probably remove this `print` statement (here and elsewhere) or use a logger?

2023-12-04 10:21 UTC, kemar requested changes
Requested changes:

- merge migration files
- remove `print` statements and unused things

The rest is not blocking and would be "nice to have":

- adding a desc to the PR :)
- more comments about the business logic and abbreviations used in models
- tests for the validation logic of serializers
- ensure that performance is not a problem without prefetching related fields

2023-12-04 10:21 UTC, kemar commented on plugins/polio/models.py
> +    comment = models.TextField(blank=True, null=True)
It's difficult for someone new to the field to understand the abbreviations used in field names:

- `_vrf_`
- `_dg_`
- `_orpg_`
- `_rrt_`

2023-12-04 10:21 UTC, kemar commented on plugins/polio/models.py
> +        return f"VFR for {self.get_country()} {self.campaign} {self.vaccine_type} #VPA {self.count_pre_alerts()} #VAR {self.count_arrival_reports()}"
`VFR` or `VRF` (as used in `wastage_rate_used_on_vrf`)?

2023-12-04 10:21 UTC, kemar commented on plugins/polio/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Don't we need to store `created_by`?

2023-12-04 10:21 UTC, kemar commented on plugins/polio/models.py
> +    lot_number = models.CharField(max_length=200, blank=True, null=True, default=None)
`CharField` doesn't need to have `null=True`.
https://sentry.io/answers/django-difference-between-null-and-blank/

2023-12-04 10:21 UTC, kemar commented on plugins/polio/tests/test_vaccine_supply_chain.py
> +
```suggestion
        self.assertEqual(res["pre_alerts"][0]["request_form"], request_form)

```

2023-12-04 10:21 UTC, kemar commented on plugins/polio/tests/test_vaccine_supply_chain.py
> +
```suggestion
        self.assertEqual(res["arrival_reports"][0]["request_form"], request_form)

```

2023-12-04 10:21 UTC, kemar commented on plugins/polio/api/vaccines/supply_chain.py
> +def validate_rounds_and_campaign(data, current_user=None):
This could be tested since the logic isn't trivial?

2023-12-04 10:21 UTC, kemar commented on plugins/polio/api/vaccines/supply_chain.py
> +class NestedRoundPostSerializer(serializers.ModelSerializer):
This looks unused.

2023-12-04 10:21 UTC, kemar commented on plugins/polio/api/vaccines/supply_chain.py
> +        arrival_reports = obj.vaccinearrivalreport_set.all()
This access to `m2m` (and others above) will potentially generate a lot of queries.
You should probably use `prefetch_related` at some point and test the number of queries unless it's not critical.

2023-12-05 09:51 UTC, mathvdh commented on plugins/polio/models.py
> +    comment = models.TextField(blank=True, null=True)
I don't even know what they mean myself.

2023-12-05 09:51 UTC, mathvdh commented on plugins/polio/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
It was not requested ...

2023-12-05 09:53 UTC, mathvdh commented on plugins/polio/api/vaccines/supply_chain.py
> +class NestedRoundPostSerializer(serializers.ModelSerializer):
Removed

2023-12-05 10:06 UTC, mathvdh commented on plugins/polio/models.py
> +    lot_number = models.CharField(max_length=200, blank=True, null=True, default=None)
Dans la prochaine PR ceci a été changé en lot_numbers (backend part 2) (plusieurs donc voilà cela sera corrigé là)

2023-12-05 10:21 UTC, kemar approved these changes
LGTM, you could have squashed migrations down to one or two files though ;)

2023-12-05 10:24 UTC, merged