IA-2423 Get one Org Unit Change Request
BLSQ/iaso pull request #871
Opened 2023-10-17 09:55 UTC by kemar

Get one Org Unit Change Request.

Related JIRA tickets:

- [IA-2423](https://bluesquare.atlassian.net/browse/IA-2423)
- [IA-2229](https://bluesquare.atlassian.net/browse/IA-2229) (Epic)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [x] Are there enough tests
- [x] Documentation has been included (for new feature)

## Changes

Implement [`GET /api/orgunits/changes/{change_id}/`](https://github.com/BLSQ/iaso/blob/1daf727c40a4546c78c0070270f1a57f03df0fb1/docs/pages/dev/reference/API/org_unit_registry.md#get-apiorgunitschangeschange_id):

- new API endoint `/api/mobile/orgunits/changes/id`
- new `ThreeDimPointField` serializer field

## Important notice

Unfortunately, `accuracy` is not included [as originally planned](https://github.com/BLSQ/iaso/blob/1daf727c40a4546c78c0070270f1a57f03df0fb1/docs/pages/dev/reference/API/org_unit_registry.md?plain=1#L40-L45).

Note that it [was inconsistent](https://github.com/BLSQ/iaso/blob/1daf727c40a4546c78c0070270f1a57f03df0fb1/docs/pages/dev/reference/API/org_unit_registry.md?plain=1#L175-L179) between models.

I used a custom DRF `ThreeDimPointField` to group attributes of a GeoDjango `PointField` used with `dim=3`:

- it makes it easier to manipulate a `PointField` in a DRF serializer in both **read** and **write** mode
- reusability and validation are built in
- it will benefit the rest of the project

## How to test

1. Create `OrgUnitChangeRequest` objects in admin:

    - http://localhost:8081/admin/iaso/orgunitchangerequest/
    - Follow requirements of `OrgUnitQuerySet.filter_for_user_and_app_id` for ACL compliance

1. Test API with DRF UI:

    - Get:
        - http://localhost:8081/api/orgunits/changes/id

## Screenshot

![screen](https://github.com/BLSQ/iaso/assets/281139/083062c2-abd5-47b6-899f-83c55ad21b6b)

2023-10-19 14:28 UTC, madewulf approved these changes

2023-10-19 15:49 UTC, madewulf requested changes
Please add the id to the groups too. Don't use just the names.
![image](https://github.com/BLSQ/iaso/assets/185797/ac608e59-25af-4c47-b7c5-f1aed177ad7f)

2023-10-23 08:43 UTC, kemar commented
> Please add the id to the groups too. Don't use just the names.

Done in #883.

2023-10-23 17:19 UTC, madewulf approved these changes

2023-10-24 08:14 UTC, merged