IA-2345: Permissions grouping for IASO admin
BLSQ/iaso pull request #872
Opened 2023-10-17 14:21 UTC by hakifran

Explain what problem this PR is resolving

- Group permissions into modules
- Limit the access of permissions bye modules

Related JIRA tickets : [IA-2345](https://bluesquare.atlassian.net/browse/IA-2345)(Permissions grouping for IASO admin)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [x] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [x] My migrations file are included
- [x] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Added modules and their linked permissions in constants
- Link Account with modules through ArrayField
- Create modules to all existing Accounts
- Add modules JsonField on setup_account
- Edit filter_permissions to take in account modules
- Display on the front end modules(those activated for the account and the other not activated
- Filter on permissions related to current account modules when creating or editing a profile

## How to test
- Go in admin/iaso/account/
- Create an account with some modules
- Create a user with the account
- Check in menu which menus is accessible

## Print screen / video
![Screenshot from 2023-10-17 16-17-06](https://github.com/BLSQ/iaso/assets/19631540/2a5f6869-cce4-4f10-b094-234cb
![Screenshot from 2023-10-17 16-17-44](https://github.com/BLSQ/iaso/assets/19631540/ed8aeb8a-ee18-4d6c-9a8f-b1753d58bb62)
f9d98e3
![Screenshot from 2023-10-17 16-18-27](https://github.com/BLSQ/iaso/assets/19631540/576ba2b0-4dbf-4053-b705-5e81f2ad86b7)
)
![Screenshot from 2023-10-17 16-19-52](https://github.com/BLSQ/iaso/assets/19631540/2d5172cf-5517-4504-ab68-3f826d357f59)

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-10-17 17:07 UTC, hakifran commented
@cypress

2023-10-18 08:00 UTC, hakifran commented
@beygorghor cypress test succeed in local but not on git when launched manually and there is GET /api/entitytypes/?order=name 500 34.038 ms - - on each cypress page test

2023-10-20 08:23 UTC, beygorghor requested changes
I have a permission error while trying the setup account page:
![Screenshot 2023-10-20 at 10 22 12](https://github.com/BLSQ/iaso/assets/12494624/64d89e38-36f9-4910-b254-0ffaf3c446b6)
Also @madewulf i'm not getting the point of displaying modules list without any action on this page:

<img width="1669" alt="Screenshot 2023-10-20 at 10 20 29" src="https://github.com/BLSQ/iaso/assets/12494624/1c463d42-9058-4ccf-83f3-a4bba1b0361f">

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
Please double check your translations, codename is missing for instance

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/modules/components/ModulesFilters.tsx
> +                container
i don't think the container is required here

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/modules/config.tsx
> +        return columns;
you can directly return the array without using a variable

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/modules/types/modules.ts
> +};
We probably have this one somewhere else

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/setup/index.tsx
> +            modules: [],
You have to add modules in `useAccountValidation`

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/setup/index.tsx
> +            setFieldValue(keyValue, value.split(','));
`commaSeparatedIdsToArray`

2023-10-20 08:23 UTC, beygorghor commented on hat/assets/js/cypress/fixtures/permissions/list.json
> -            "name": "Unités d'organistations",
😇

2023-10-20 08:50 UTC, hakifran commented
> I have a permission error while trying the setup account page: ![Screenshot 2023-10-20 at 10 22 12](https://user-images.githubusercontent.com/12494624/276869166-64d89e38-36f9-4910-b254-0ffaf3c446b6.png) Also @madewulf i'm not getting the point of displaying modules list without any action on this page:
> <img alt="Screenshot 2023-10-20 at 10 20 29" width="1669" src="https://user-images.githubusercontent.com/12494624/276869389-1c463d42-9058-4ccf-83f3-a4bba1b0361f.png">

@beygorghor for the question about the displaying modules list, I added it regarding this mockup https://whimsical.com/iaso-admin-screen-6hGzbQA4F2AKAEu8wFGL8y

2023-10-20 08:58 UTC, hakifran commented
> I have a permission error while trying the setup account page: ![Screenshot 2023-10-20 at 10 22 12](https://user-images.githubusercontent.com/12494624/276869166-64d89e38-36f9-4910-b254-0ffaf3c446b6.png) Also @madewulf i'm not getting the point of displaying modules list without any action on this page:
> <img alt="Screenshot 2023-10-20 at 10 20 29" width="1669" src="https://user-images.githubusercontent.com/12494624/276869389-1c463d42-9058-4ccf-83f3-a4bba1b0361f.png">

@beygorghor for the error that you don't have the permission, are you using a superUser? if not the user you are using should have iaso_modules permission

2023-10-20 09:08 UTC, hakifran commented on hat/assets/js/apps/Iaso/domains/app/translations/fr.json
@beygorghor pour les codename j'ai gardé ainsi parce que dans le code on les utilise tel qu'ils sont. Mais je vais les traduire en fr. Merci

2023-10-24 09:42 UTC, beygorghor commented
> > I have a permission error while trying the setup account page: ![Screenshot 2023-10-20 at 10 22 12](https://user-images.githubusercontent.com/12494624/276869166-64d89e38-36f9-4910-b254-0ffaf3c446b6.png) Also @madewulf i'm not getting the point of displaying modules list without any action on this page:
> > <img alt="Screenshot 2023-10-20 at 10 20 29" width="1669" src="https://user-images.githubusercontent.com/12494624/276869389-1c463d42-9058-4ccf-83f3-a4bba1b0361f.png">
> 
> @beygorghor for the error that you don't have the permission, are you using a superUser? if not the user you are using should have iaso_modules permission

@hakifran  The user is a user without profile then without permission. It's a staff user status, not super user, but staff can access this page too.
<img width="683" alt="Screenshot 2023-10-24 at 11 40 45" src="https://github.com/BLSQ/iaso/assets/12494624/c2b28e8d-47fc-4555-a7bd-4f43801261cf">

2023-10-24 09:42 UTC, beygorghor approved these changes
Except the staff user error, it's ok for me

2023-10-26 06:09 UTC, madewulf commented on iaso/api/permissions.py
> +                modules_permissions = modules_permissions + MODULE_PERMISSIONS[module]
Toute petite remarque, pas bloquante: ici, tu pourrais un jour avoir deux modules qui incluent la même permission, et dans ce cas, tu pourrais finir avec la même permission qui appraîtrait 2 fois dans modules_permissions. Je ne pense pas que ça pose problème plus loin (tu fais _in=modules_permission) mais j'aurais eu tendance à utiliser un set plutôt qu'une liste pour éviter les doublons.

2023-10-26 06:12 UTC, madewulf commented on iaso/api/setup_account.py
> +        for module in account_modules:
Ce code est beaucoup répété, ça aurait sans doute mérité une petite fonction utilitaire

2023-10-26 07:29 UTC, madewulf commented
> > > I have a permission error while trying the setup account page: ![Screenshot 2023-10-20 at 10 22 12](https://user-images.githubusercontent.com/12494624/276869166-64d89e38-36f9-4910-b254-0ffaf3c446b6.png) Also @madewulf i'm not getting the point of displaying modules list without any action on this page:
> > > <img alt="Screenshot 2023-10-20 at 10 20 29" width="1669" src="https://user-images.githubusercontent.com/12494624/276869389-1c463d42-9058-4ccf-83f3-a4bba1b0361f.png">
> > 
> > 
> > @beygorghor for the error that you don't have the permission, are you using a superUser? if not the user you are using should have iaso_modules permission
> 
> @hakifran The user is a user without profile then without permission. It's a staff user status, not super user, but staff can access this page too. <img alt="Screenshot 2023-10-24 at 11 40 45" width="683" src="https://user-images.githubusercontent.com/12494624/277617323-c2b28e8d-47fc-4555-a7bd-4f43801261cf.png">

For that point, I tend to agree that it's not super useful, but I think we can keep it and just add a small explanation. 

Something like: "You can see here the feature modules that are activated for your account. Contact an admin of your instance if you wish to activate additional features" at the top.

2023-10-26 07:34 UTC, merged