Upgrade material ui
BLSQ/iaso pull request #895
Opened 2023-10-25 14:44 UTC by beygorghor

Explain what problem this PR is resolving

Related JIRA tickets : IA-XXX, WC2-XXX, POLIO-XXX

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub already provides a full diff), but to help the reviewers better understand:
- which specific file changes go together, e.g: when creating a table in the front-end, there usually is a config file that goes with it
- the reasoning behind some changes, e.g: deleted files because they are now redundant
- the behaviour to expect, e.g: tooltip has purple background color because the client likes it so, changed a key in the API response to be consistent with other endpoints

## How to test

Explain how to test your PR.
If a specific config is required explain it here (dataset, account, profile, ...)

## Print screen / video

Upload here print screens or videos showing the changes

## Notes

Things that the reviewers should know: known bugs that are out of the scope of the PR, other trade-offs that were made.
If the PR depends on a PR in bluesquare-components, or merges into another PR (i.o. main), it should also be mentioned here

2023-11-10 10:04 UTC, hakifran commented
[Screencast from 2023-11-10 11-49-01.webm](https://github.com/BLSQ/iaso/assets/19631540/186df7a3-5b50-4465-a859-e9219e5b8a68)
[Screencast from 2023-11-10 11-50-01.webm](https://github.com/BLSQ/iaso/assets/19631540/6d72e87b-2924-42d3-9305-0d50488c4b80)
@beygorghor  on these two pages there is a problem and I think is related to the upgrade

2023-11-28 11:48 UTC, beygorghor commented
> [Screencast from 2023-11-10 11-49-01.webm](https://github.com/BLSQ/iaso/assets/19631540/186df7a3-5b50-4465-a859-e9219e5b8a68) [Screencast from 2023-11-10 11-50-01.webm](https://github.com/BLSQ/iaso/assets/19631540/6d72e87b-2924-42d3-9305-0d50488c4b80) @beygorghor on these two pages there is a problem and I think is related to the upgrade

@hakifran this is fixed now

2023-11-28 12:53 UTC, hakifran commented
@beygorghor there is another style issue but this one is not blocking  
![Screenshot from 2023-11-28 14-47-12](https://github.com/BLSQ/iaso/assets/19631540/99e66d5f-67cd-4384-acc2-dc49cd1a3f7c)

2023-11-28 12:57 UTC, hakifran approved these changes
A part from the style problem on the sidebar at the bottom, everything seems to me working fine.

2023-12-01 14:14 UTC, quang-le requested changes
Huuuuge job. I've gone through as much as possible. Couldn't test polio plugin though.


I get this error when trying out with polio plugin:

![Screenshot 2023-12-01 at 15 02 20](https://github.com/BLSQ/iaso/assets/38907762/56990deb-cf16-4db0-8a12-e39d513511b9)

Some margins have been lost between button:
- Error snack bar:
![Screenshot 2023-11-30 at 16 54 31](https://github.com/BLSQ/iaso/assets/38907762/2064d6b2-1489-4dc0-aa66-7020f96c37b3)
- CSV/xlsx export, eg: beneficiary details:

![Screenshot 2023-11-30 at 18 31 27](https://github.com/BLSQ/iaso/assets/38907762/7116a554-80dc-4cee-ab48-715e8475363a)

- Org units map edition:
![Screenshot 2023-11-30 at 17 36 32](https://github.com/BLSQ/iaso/assets/38907762/0987a820-ec1d-4a8a-a734-032fbb4ec6f4)



A few things in Assignments:

![Screenshot 2023-12-01 at 13 55 47](https://github.com/BLSQ/iaso/assets/38907762/d03b584a-78ba-44e4-b22b-db411ef0aa27)

Planning modal: too little space between fields:
![Screenshot 2023-12-01 at 13 51 24](https://github.com/BLSQ/iaso/assets/38907762/7fc1d657-7bf0-487c-9320-3da02661d962)

Org Units:
- when we have multiple active searches, closing a tab will generate an error (in the console):

https://github.com/BLSQ/iaso/assets/38907762/30f0a024-793b-4436-a45b-d8ef4895761d

- Tabs are more compact than before, and the marker for active tab is not visible anymore:

https://github.com/BLSQ/iaso/assets/38907762/b653c4ad-aaae-449e-a311-8e29259ca5c4

- Rule of hooks error when searcing with Treeview:

https://github.com/BLSQ/iaso/assets/38907762/b1d82d3c-d36a-4e00-b2d5-f00067841618

Treeview: link to org unit broken:


https://github.com/BLSQ/iaso/assets/38907762/f3e3ef5e-f5f6-44c5-a655-f1e2900d4b60

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/files/LazyImagesListComponent.js
> +import { grey } from '@mui/material/colors';
not related but we should probably have a `colors.ts` file. I don't know how many different greys we have in iaso now...

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/snackBars/useSnackBars.tsx
> +let displayed: Notification[] = [];
It seems weird to me to have this here, especially since it looks like it should be in the deps array of `closePersistingSnackBars`. Maybe I'm too used to do everything in React.

I guess the point is to have the same value accessible for every instance of `useSnackBars`. My instinct would be to put it in a context and to access it with `useContext` and put `displayed` in `useCallback`'s deps array, so we're sure React keeps `closePersistingSnackBars` in sync for every `useSnackBars`.

(That's more or less what I had in mind when I was thinking about refactoring the snackbars)

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/snackBars/useSnackBars.tsx
> +                message = 'Error';
This could still be translated

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/snackBars/useSnackBars.tsx
> +                message = 'Error';
I would put all that logic in a function, so we can use early returns
```typescript
const translateMessage = (notification, formatMessage) => {
    if (notification.messageObject) {
        if (typeof notification.messageObject === 'string') {
            return notification.messageObject;
        }
        if (notification.messageObject.id) {
            return formatMessage(notification.messageObject);
        }
        console.error(
            `Invalid translation message for snackbar ${notification.messageObject}`,
        );
        return formatMessage(MESSAGES.error); // some message here
    }
    if (notification.messageKey) {
        if (MESSAGES[notification.messageKey]) {
            return formatMessage(MESSAGES[notification.messageKey]);
        } else {
            console.error(
                `Translation ${notification.messageKey} not present in SnackBar messages`,
            );
        }
    }
    return formatMessage(MESSAGES.error); // handle case with no messageKey  and no messageObject
};
```

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/teams/components/UsersTeamsCell.tsx
>  // @ts-ignore
this one can go too 😀

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/cypress/fixtures/orgunittypes/page2_limit20.json
What's this for? Is it just a reformat?

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/cypress/integration/11 - submissions/list.spec.js
Is this related to the upgrade of MUI?

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/cypress/support/commands.js
> +    cy.get('[role="tooltip"]').should('be.visible').should('contain', content);
I have nothing against theses changes but, what does it do and why?

2023-12-01 14:14 UTC, quang-le commented on package.json
> +        "@emotion/styled": "^11.11.0",
What's this lib again?

2023-12-01 14:14 UTC, quang-le commented on plugins/polio/js/src/domains/Campaigns/VaccineManagement/ShipmentForm.tsx
this will be deleted in my next PR 🤷‍♂️

2023-12-01 14:14 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/snackBars/useSnackBars.tsx
> +            if (displayed.find(s => s.key === notification.key)) return;
if (!displayed.find(s => s.key === notification.key)){
 }

2023-12-05 13:03 UTC, beygorghor commented on hat/assets/js/apps/Iaso/components/snackBars/useSnackBars.tsx
> +                message = 'Error';
mhhh this is a a console warning, it was like that before and this is a technical warning, there is no point to translate it for the user

2023-12-05 13:09 UTC, beygorghor commented on hat/assets/js/cypress/fixtures/orgunittypes/page2_limit20.json
adding a second page fore pagination tests

2023-12-05 13:10 UTC, beygorghor commented on hat/assets/js/cypress/integration/11 - submissions/list.spec.js
i wanted to make sure all tests are passing

2023-12-05 13:10 UTC, beygorghor commented on hat/assets/js/cypress/support/commands.js
> +    cy.get('[role="tooltip"]').should('be.visible').should('contain', content);
aira)described has been removed in mui 5

2023-12-05 13:11 UTC, beygorghor commented on package.json
> +        "@emotion/styled": "^11.11.0",
another way to create styling, i had to include it

2023-12-19 16:09 UTC, quang-le approved these changes

2023-12-19 16:09 UTC, merged