IA-2390: Configuration of completeness thresholds legend per form
BLSQ/iaso pull request #922
Opened 2023-11-14 12:05 UTC by beygorghor

[Mock-ups](https://whimsical.com/legend-thresholds-per-form-UrGwEAJ9TmGsm5SYVtoMKk) 

Related JIRA tickets : IA-2390

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes

- Change of behaviour of number input to set field in error state (going with [this](https://github.com/BLSQ/bluesquare-components/pull/134))
- Legends components using number input to edit/create a legend using scale threshold of type:
```
{
  "range": [
    "#b71c1c",
    "#ff9800",
    "#43a047"
  ],
  "domain": [
    70,
    99
  ]
}
```
- Adapt org unit marker input to set field in error mode and block save
- migrate form model to add `legend_threshold` Json field

## How to test

Open the detail of a form, create a new legend, save it, edit it

## Print screen / video

https://github.com/BLSQ/iaso/assets/12494624/d8990218-5d3f-4fc6-889e-4cc28bdb17f6

## Notes

Merge bluesquare-component [PR](https://github.com/BLSQ/bluesquare-components/pull/134) and upgrade it on Iaso

2023-11-19 18:24 UTC, madewulf approved these changes

2023-11-27 11:23 UTC, quang-le requested changes
Nice feature. Please check the 2 suggestions I made for bug fixes.

We should discuss the new `NumberInput`.

I think some code could be simplified by using more of the formik features available. I won't block over it (maybe I missed something), but if it can be done, we should put it in a tech debt ticket.

Otherwise very nice feature. Some gymnastics `RangeValues` and `ScaleTreshold`, that's never easy to handle. Reminds me of Lqas...

Well done

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/Index.tsx
file name should be lower case

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/Dialog.tsx
side note: I really prefer when we include the domain in the file name, e.g: `LegendBuilkderDialog`, it makes finding the file easier in the IDE

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormLegendInput.tsx
> +            {!isFormLoading && currentForm.legend_threshold?.value && (
```suggestion
            {!isFormLoading &&
                currentForm.legend_threshold?.value !== undefined && (
```

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormLegendInput.tsx
> +            {!isFormLoading && currentForm.legend_threshold?.value && (
The suggestion fixes the bug below. It's because `onCancel` sets `currentForm.legend_threshold?.value` to `null`
https://github.com/BLSQ/iaso/assets/38907762/d3b74bbb-56d4-444e-95f2-2a50e6b24708

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.tsx
>                                  label={MESSAGES.singlePerPeriod}
```suggestion
                                withMarginTop={false}
                                label={MESSAGES.singlePerPeriod}
```

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.tsx
>                                  label={MESSAGES.singlePerPeriod}
For better alignment

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/Dialog.tsx
> +    const getScaleThreshold = useGetScaleThreshold();
These functions don't need to be wrapped in hooks: they can be imported directly.
(Which makes me think it's probably the same with `useUrlParams` and `useApiParams`)

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/Dialog.tsx
> +    }, [errors]);
Formik should spare you the trouble of writing these

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/LegendRange.tsx
> +            </Grid>
I have the feeling you could use formik's `Field` and use:
```typescript
<Field
name={`rangeValues[${index}].percent`}
// other props
/>
```

that would probably also spare you the custom `errors` and `setFieldError`

The `rangeItem.id` is directly derived from the array index, and you don't use when converting back with `useGetThreshold` so I think it should work

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/hooks.ts
some comments as to why we convert `ScaleThreshold` to `RangeValue` and back would help

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/hooks.ts
> +};
These functions don't need to be wrapped in hooks, we can just import them directly

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/completenessStats/index.tsx
> +    }, [forms, selectedFormsId]);
you could memoize the treshold directly, `selectForm` isn't used anywhere else

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.tsx
> +    createStyles({
So THAT's how you fix this bloody TS error. You should add it to the guidelines.
Although, I'm not sure importing and running that function is worth the hassle to be honest

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/detail.tsx
> +};
should go in bluesquare-components

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/forms/types/forms.ts
> +};
❤️

2023-11-27 11:23 UTC, quang-le commented on hat/assets/js/apps/Iaso/domains/orgUnits/components/orgUnitMap/MarkerInputs.js
> +    );
see NumberInput PR

2023-11-27 11:23 UTC, quang-le commented on iaso/tests/api/test_forms_serializers.py
> +            "legend_threshold": None,
maybe add a `legend_treshold` to `self.form` and test that it is returned?

2023-11-28 13:01 UTC, beygorghor commented on hat/assets/js/apps/Iaso/domains/forms/components/FormFormComponent.tsx
> +    createStyles({
the createStyle is not mandatory here

2023-11-30 12:25 UTC, beygorghor commented
bluesquare-components has been updated

2023-12-01 12:42 UTC, quang-le requested changes
There's just this one left I think: 
https://github.com/BLSQ/iaso/assets/38907762/5ff4f061-2795-415a-8b55-88bb8b0d4b03

2023-12-01 12:42 UTC, quang-le commented on hat/assets/js/apps/Iaso/components/LegendBuilder/LegendBuilkderDialog.tsx
> +const LegendBuilkderDialog: FunctionComponent<Props> = ({
lol

2023-12-04 12:14 UTC, quang-le approved these changes

2023-12-04 12:14 UTC, merged