IA-2517: Invitation link leads to unusable page
BLSQ/iaso pull request #929
Opened 2023-11-21 19:15 UTC by hakifran

Explain what problem this PR is resolving
- The expired or already used link lead to None page
- This ticket is about to display a message to let the user know that the link has been expired
Related JIRA tickets : [IA-2517](https://bluesquare.atlassian.net/browse/IA-2517)

## Self proofreading checklist

- [ ] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [x] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Made a check on the form if it's None
- If it's None display a message

## How to test
- Create a user and send a reset password through email
- Open the link and just modify on character in the token number and check the displayed message

## Print screen / video
![Screenshot from 2023-11-21 21-14-57](https://github.com/BLSQ/iaso/assets/19631540/c8a70650-9d03-4fdf-b004-fece286f0321)

2023-11-23 16:30 UTC, quang-le approved these changes

2023-11-23 16:35 UTC, quang-le requested changes
Can't we add a button/link to immediately generate a new password reset link?

2023-11-24 12:19 UTC, hakifran commented
> Can't we add a button/link to immediately generate a new password reset link?

Done

2023-11-27 08:26 UTC, quang-le approved these changes

2023-11-27 13:36 UTC, merged