IA-2542: Permission "Submissions - Read and Write" only (without permission "Submissions - Read only") does not show in menu entry
BLSQ/iaso pull request #958
Opened 2023-12-05 08:29 UTC by hakifran

Explain what problem this PR is resolving
- User with read and write submission permission only had not access to the submission menu
- The PR is about to let a user with read and write access the submission menu

Related JIRA tickets : [IA-2542](https://bluesquare.atlassian.net/browse/IA-2542)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Added the SUBMISSION_UPDATE permission in instancePath

## How to test
- Update or create a user with submission read and write permission but without submission read only permission
- Check if the use has access to the submission on the sidebar menu

2023-12-07 14:01 UTC, beygorghor approved these changes

2023-12-13 10:47 UTC, quang-le requested changes
Users with the read write permission get a 403 on `/api/sourceversions` when the data sources  page loads. 
![Screenshot 2023-12-13 at 09 18 23](https://github.com/BLSQ/iaso/assets/38907762/9f7fb114-470b-479b-82ca-05157e26957f)

2023-12-13 12:10 UTC, hakifran commented
> Users with the read write permission get a 403 on `/api/sourceversions` when the data sources page loads. ![Screenshot 2023-12-13 at 09 18 23](https://private-user-images.githubusercontent.com/38907762/290162794-9f7fb114-470b-479b-82ca-05157e26957f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjkyNjQsIm5iZiI6MTcwMjQ2ODk2NCwicGF0aCI6Ii8zODkwNzc2Mi8yOTAxNjI3OTQtOWY3ZmIxMTQtNDcwYi00NzliLTgyY2EtMDUxNTdlMjY5NTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEyMDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZmUxNjM2ZDZmNzQ1MjZkZDdhMjU5OWRlMmRkZWRmNjc4YmY1ZWM5MDY4YjBhMGEyOTVmNzBmMmM4YmM0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CZXaHzy07d4v-_IyAEfmmqorSEo-WQOH67345vKq-RI)

@quang-le is this

> Users with the read write permission get a 403 on `/api/sourceversions` when the data sources page loads. ![Screenshot 2023-12-13 at 09 18 23](https://private-user-images.githubusercontent.com/38907762/290162794-9f7fb114-470b-479b-82ca-05157e26957f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Njk2NTIsIm5iZiI6MTcwMjQ2OTM1MiwicGF0aCI6Ii8zODkwNzc2Mi8yOTAxNjI3OTQtOWY3ZmIxMTQtNDcwYi00NzliLTgyY2EtMDUxNTdlMjY5NTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEyMDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYmJhYzgyZWRhMDRiZWM3MTVhYjIzODRlODIwYzZmMTNjM2Q5NWJhYjVjNTY2MDQ5MWQ0YjRjM2YyOWNkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AR6B1u3h5fZA6gz6_QmKnGaxR1m3QmFfG2DHyHLiiDA)

@quang-le is this comment related to this PR or is for https://github.com/BLSQ/iaso/pull/960?

2023-12-14 11:49 UTC, quang-le approved these changes

2023-12-14 11:49 UTC, merged