IA-2546: Data Source read-write permissions
BLSQ/iaso pull request #960
Opened 2023-12-05 14:02 UTC by hakifran

Explain what problem this PR is resolving
- The Geo data sources - Read and Write was missing in the permissions list
- This PR is for adding the missing permission
Related JIRA tickets : [IA-2546](https://bluesquare.atlassian.net/browse/IA-2546)

## Self proofreading checklist

- [x] Did I use eslint and black formatters
- [ ] Is my code clear enough and well documented
- [ ] Are my typescript files well typed
- [ ] New translations have been added or updated if new strings have been introduced in the frontend
- [ ] My migrations file are included
- [ ] Are there enough tests
- [ ] Documentation has been included (for new feature)

## Changes
- Adding the **Geo data sources - Read and Write** permission in the MODULE_PERMISSIONS
- Add the permission in the datasourcePath

## How to test
- Edit or create a user
- Check if the permission is in the list

## Print screen / video
![Screenshot from 2023-12-05 15-40-18](https://github.com/BLSQ/iaso/assets/19631540/917764a5-def5-4b77-b24e-8c54fcaba876)

[IA-2546]: https://bluesquare.atlassian.net/browse/IA-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-07 14:05 UTC, beygorghor approved these changes

2023-12-13 08:23 UTC, quang-le requested changes
Users with just the `SOURCE_WRITE` permission get a 403 on `/api/sourceversions` I think we should add the `SOURCE_WRITE` to the permissions' list for the sourceversions endpoint

2023-12-13 11:49 UTC, hakifran commented
> Users with just the `SOURCE_WRITE` permission get a 403 on `/api/sourceversions` I think we should add the `SOURCE_WRITE` to the permissions' list for the sourceversions endpoint

Fixed!

2023-12-14 11:40 UTC, quang-le approved these changes

2023-12-14 11:40 UTC, merged