Polio 671 step node deletion
BLSQ/iaso pull request #97
Opened 2022-10-21 09:13 UTC by olethanh

Make the api not crash when it cannot found a node or a step. (When they get  removed or deleted)

## Self proof reading checklist

- [x] Did I use eslint and black formatters
- [x] Is my code clear enough and well documented
- [ ] Are there enough tests

## Changes

When we cannot found the transition or node to show the label we return the key itself as a fallback value

## How to test

Use the budget workflow. Then in the workflow definition  the current state of a campaign  and the last step

2022-11-04 10:50 UTC, niconoe requested changes
Thanks @olethanh!

2022-11-04 10:50 UTC, niconoe commented on plugins/polio/budget/serializers.py
> +            return {
Can we specify which specific exception(s) we expect here? thanks!

2022-11-07 15:53 UTC, quang-le approved these changes
Works on my machine!

2022-11-07 15:55 UTC, olethanh commented on plugins/polio/budget/serializers.py
> +            return {
Will do it in a later pr. need to strenghten the whole system more in any case

2022-11-07 15:55 UTC, merged